### ISSUE TITLE
Make new Ver 5.0.201 desktop type form setting optional

### ISSUE THREAD

**Issue by DanLauer** [VFPX/GoFish#1]
When I'm working on my laptop with VFP maximized, this new setting inadvertently made the GoFish main window "always on top" for me, which is really not the best. On my desktop machine, I've wanted this feature for a long time. If it were optional/configurable, that would be ideal.

**Comment by rschummer** [comment]
It is designed for dual monitors. Opening up source from the search results also opens underneath the GoFish window so I have to move it or minimize it to get to the source. I agree with making it an option.

**Comment by PatrickvonDeetzen** [comment]
No idea why this issue is still open. 

This got already changed in version 5.0.202!

![2022-08-14_12h05_28](https://user-images.githubusercontent.com/74181432/184532083-25ca0160-391d-4c41-9e15-78cd2103b39a.png)
