### ISSUE TITLE
GF error first time running GF 6

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#103]
## ℹ Computer information

- VFP version: 9
- GoFish version: 6.2.02
- Last GoFish version w/o bug (if available): 5.

Having had issues getting started with GF6, finally got to try it today.

1)  Using GF5, I deleted all search history.
2)  Ran CFU to get latest version of GF6
3)  Opened GF6 and tried a simple search
4)  Got error as shown below.

NOTE:  The error shows that it is looking for this file in my folder commonapps.  This is a problem.  I do not want GF to store any files in my folder (unless you provide an option allowing this to happen). Previous versions used Home(7) and GF6 should continue to do so.

![image](https://github.com/VFPX/GoFish/assets/81179335/ce4837b2-b372-41ac-93c9-eb351561fa5d)

**Comment by lscheffler** [comment]
Hi @Jimrnelson any chance we can do this remote? It will not happen on my comp, and I have not the slightest idea why it happens.   
And I burn to get it solved.

There is a option to place the settings, history etc. local to  foxuser, i.e. not in home(7), but this should not run yet.

**Comment by lscheffler** [comment]
@Jimrnelson    
Fancy. There is nothing that should call like `.UseTable("GF_Search_History", "csrSummarySearchResults")` I see. What is the value of *tcTable* in your example?     
A picture of the calling method, as many vars as possible and the debug stack, for starters, might be very helpfull. Thank you

**Comment by Jimrnelson** [comment]
![image](https://github.com/VFPX/GoFish/assets/81179335/e3cb30af-5d80-477e-8cab-9f11951ec4ce)

![image](https://github.com/VFPX/GoFish/assets/81179335/e03e44fa-1799-40a8-9d1d-b8ed3ea2aa39)

**Comment by Jimrnelson** [comment]
Also, oddly enough, on my "Options" screen, "Code References" page appears but is disabled.

![image](https://github.com/VFPX/GoFish/assets/81179335/8369d169-ce5a-42a4-b252-7e5c8e9c15ba)

**Comment by Jimrnelson** [comment]
> Hi @Jimrnelson any chance we can do this remote? 

Hi Lutz --

Unfortunately, my current circumstances make that impossible.

**Comment by lscheffler** [comment]
Sad, that remote is no option. But I can understand.

----
Code References is disabled by default, because it changes the behaviour in a way some might not like, and it was cheapest to have a general option. To turn it on, go to Options, Advanced, Global Settings, Allow Code References ..; restart GF.

----
So, you say at least GF is starting. Fine, so far.

----
There should be a DBC **gf_result** open and active, the table is in this DBC. Is the database  open, and if not, does the database (and the table GF_Search_History) exists in Home(7)+"GoFish_"?

**Comment by lscheffler** [comment]
@Jimrnelson, what is the value of `This.cCR_StoreLocal`

**Comment by Jimrnelson** [comment]
I suspect the problem may be a failed installation from few months ago (which did not complete).

Are all your settings in `Home(7)+"GoFish_"`    ?

**Comment by lscheffler** [comment]
Yes, all settings (iow GF Data) should be there. The folder should be open via Options, Advanced, Open Folder  and should look more or less like   
![grafik](https://github.com/VFPX/GoFish/assets/27769909/2bbf6dcd-819c-4b04-b049-38edfa04d21c)



As long as not turned to relative to foxuser.dbf, where you can choose freely. Only available if Code References is turned on, available on Advanced page.  But this should not be the case yet.

**Comment by Jimrnelson** [comment]
All seems to be well now.

I erased your new folder and re-installed.  A few odd messages along the way, but it seems to be working.

**Comment by Jimrnelson** [comment]
I am convinced that this issue was a direct result of a partial upgrade from version 5 to version 6.   

That upgrade was interrupted (reasons no longer relevant). 

I resolved this by removing the new GoFish_ folder in Home(7) and upgrading using CFU.  

All seems to be working well.
