### ISSUE TITLE
Please restore feature from GoFish5 that managed positions of controls across top of GF form.

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#105]
In GF5,  if your form was not too wide, all the controls at the top of the screen responded as expected, with anchors, so that the search textbox and scope combobox expanded as the width was increased, and the controls to the right moved farther to the right.

However, when the form got to be sufficiently wide, the anchor effect stopped.  The textbox and combobox stopped expanding and the other controls stopped moving.  This allowed the textbox and combobox to be sufficiently wide without moving the other controls too far.  Here's what this looks like on my laptop, (GF5)

![image](https://github.com/VFPX/GoFish/assets/81179335/ca2ade93-fbb3-41a0-8337-09a028c57c7f)

However, this effect is now lost in GF6.  The textbox and combobox keep expanding and the other controls move farther.  Again, on my laptop (GF6)

![image](https://github.com/VFPX/GoFish/assets/81179335/b3446341-f95b-4440-981e-c48249c141a1)

This is annoying as the group of most frequently used controls have moved to the most inconvenient position.

This will be greatly exaggerated when I can get back home to double monitors.  My GF form occupies one and a half monitors, and those special controls will be isolated far off to the right on my second monitor.  (The textbox will have a width of about 2200).

Please restore this feature.   / Thanks / Jim

**Comment by lscheffler** [comment]
@Jimrnelson ,
Define *sufficent*.    
I can see what you mean, but for me, the controls are just on the right border of the form, I feel real odd if they stop moving and stuck in the middle of nowhere.    
Also it was a lot of odd calculation, now it's a simple ANCHOR, so there is no elegant way to do both.   
What do you think if we go the other way around, place the controls left and let the combos resize?

There is no hurry, I will be BOK not before Monday.

**Comment by Jimrnelson** [comment]
@lscheffler 

> @Jimrnelson  I can see what you mean, but for me, the controls are just on the right border of the form, I feel real odd if they stop moving and stuck in the middle of nowhere. 

Yes, it is unusual for seemingly anchored controls to stop expanding or moving as you expand the width of a form.

However, the result in my environment now is a bizarre and really unusable form that has these peculiar features:

- a textbox and combobox that are each wider than a monitor and spill onto the second monitor.  (Each has a width of over 2000, many times larger than what I have ever seen or could be of use.)
- the dropdown arrow for the combobox is way off on the second monitor.
- the most important other controls for the form appear way off to the right on the second monitor, as if hidden.

> Also it was a lot of odd calculation, now it's a simple ANCHOR, so there is no elegant way to do both. 

There is no need to find an elegant solution when there is a previously existing solution (Yes, there will need to be some minor tweaking due to the two new controls you added for selecting a project or folder).

> What do you think if we go the other way around, place the controls left and let the combos resize?

Oh my gosh, no!  My whole issue is to leave the existing UI as is.  We users are comfortable and accustomed to the UI for GF, having used it for many years.    We are grateful for your improvements to GF and at the same time expect that features we are accustomed to and rely on will not disappear.

**Comment by Jimrnelson** [comment]
@lscheffler 

> Also it was a lot of odd calculation, now it's a simple ANCHOR, so there is no elegant way to do both.

Lutz, you were particularly kind in your characterization of this code.  I would describe it as outstandingly inelegant and opaque.  I am sure that modifying it would be quite painful.  And it is some embarrassment that I acknowledge that it is my code (from my younger days).

So, I offer the code below, for the form's Resize method.

It's pretty straightforward.  If the form width is 1400 or less, then the controls move normally based on their anchors.  If more than 1400, the controls are moved/resized as if the form width is 1400.

You might be curious about the rather arbitrary value of 1400.  When we (Matt and I) were working on this, we decided that allowed the textbox and combobox to be as wide as would ever be needed.

	With ThisForm
		lnChange	= .Width - 1400
		If m.lnChange > 0
			.ButtonContainer.Left = .ButtonContainer.Left - m.lnChange
			.editSearch.Width = .editSearch.Width - m.lnChange
			.comboSearchExpressionHistory.Width = .comboSearchExpressionHistory.Width - m.lnChange
			.comboSearchScopeHistory.Width = .comboSearchScopeHistory.Width - m.lnChange
			.comboSearchExpressionHistoryDropDownArrow.Left = .comboSearchExpressionHistoryDropDownArrow.Left - m.lnChange
			.imgProj_Pick.Left = .imgProj_Pick.Left - m.lnChange
			.imgFolder_Pick.Left = .imgFolder_Pick.Left - m.lnChange
		Endif

	Endwith

**Comment by lscheffler** [comment]
Thanks, this is from commit 726d4aa4471, Dougs latest. I have a *git worktree* on that commit. ;)

**Comment by lscheffler** [comment]
> ...
> This will be greatly exaggerated when I can get back home to double monitors.  My GF form occupies one and a half monitors, and those special controls will be isolated far off to the right on my second monitor.  (The textbox will have a width of about 2200).

Shudder.   
I'm just curious. Why this? I normally have it around 1000px in width on my (scaled) 4k.

**Comment by lscheffler** [comment]
@Jimrnelson I understand your problem, but I'm not sure if this is good for general audience. At least odd to me. Would it work for you if we put a hidden setting in the XML, that switches from Anchor to the Resize?

**Comment by Jimrnelson** [comment]
No, don't go back to that commit.  The controls atop the form have changed since then.

Use the code I supplied to you earlier in this thread.

**Comment by Jimrnelson** [comment]
> Shudder. I'm just curious. Why this? I normally have it around 1000px in width on my (scaled) 4k.

Because I prefer it that way.

De gustibus non est disputandum.

**Comment by Jimrnelson** [comment]
> @Jimrnelson  I'm not sure if this is good for general audience. At least odd to me. Would it work for you if we put a hidden setting in the XML, that switches from Anchor to the Resize?

Lutz, you're really missing the point that this is the way GF has operated for about ten years.  The general audience has already accepted it.  I am not introducing new behavior, you are.  

What seems odd to you, I think, is the code, not the way the form looks when the code runs.  My form width is about 2800 -- have you tried a form of that width to see how weird it looks?

Users don't know or care if you are using Anchors or Resize (or a combination), nor should they.  They care about what their form looks like.  And I am telling you, yet again, that forms that are very wide are unusable if you only use Anchors.  You don't see that since your forms are never wide enough for the Resize event to have any effect (it only does so if the form is wider than 1400)

No, please do not make this some sort of private option.  Use the code I have provided in this thread so that it works as it did in GF5 (and don't make an option to control it).  Those (possibly few) of us who use wide forms will be grateful.

**Comment by lscheffler** [comment]
> > Shudder. I'm just curious. Why this? I normally have it around 1000px in width on my (scaled) 4k.
> 
> Because I prefer it that way.
> 
> De gustibus non est disputandum.

That was clear as blue sky. You understand, I ask to learn, not to criticise. Just like with the menu and the html and the *Match Type* column. No question, no answer, nothing learned. :)

I mean, if I ask why is something is doing `If lVar=.t.` (heavy used in GF) it might be a bit of critique, but I remember me doing this on my first lines of code too. Until somebody told me.

**Comment by lscheffler** [comment]
> @Jimrnelson I understand your problem, but I'm not sure if this is good for general audience. At least odd to me. Would it work for you if we put a hidden setting in the XML, that switches from Anchor to the Resize?

No, no, I said: I have to code available, it is all on git, and I'm familiar with git. So I can pick it there, and I know the commit. One can open many commits from the same repository at the same time. Called git worktree. It might not be available on a git-GUI.

**Comment by Jimrnelson** [comment]
> No, no, I said: I have to code available, it is all on git, and I'm familiar with git. So I can pick it there, and I know the commit. One can open many commits from the same repository at the same time. Called git worktree. It might not be available on a git-GUI.

Of course the old code is available in git.  However, the old code would have to be modified since you have added two new buttons in the top section and the width of one of the controls was changed to make room for the new buttons.

I have provided you with modified code that works so you would not have to wrestle with that ugly old code.

**Comment by Jimrnelson** [comment]
> > > Shudder. I'm just curious. Why this? I normally have it around 1000px in width on my (scaled) 4k.
> > 
> > 
> > Because I prefer it that way.
> > De gustibus non est disputandum.
> 
> That was clear as blue sky. You understand, I ask to learn, not to criticise. Just like with the menu and the html and the _Match Type_ column. No question, no answer, nothing learned. :)

My VFP session is of width about 3,000.  I use it because it's available.

My GF form occupies all that space.  There are about a dozen columns in GF that make any sense at all.  I have all of them visible, even though there are some that I rarely use  I take full advantage of all the information about a match that GF provides.

I have re-ordered the columns and changed their widths to fit my needs.

I feel constrained working on my laptop (as I have been for the last two months) as the width is only 1,920.  I have to scroll to see many of the columns to the right.

**Comment by lscheffler** [comment]
> > > > Shudder. I'm just curious. Why this? I normally have it around 1000px in width on my (scaled) 4k.
> > > 
> > > 
> > > Because I prefer it that way.
> > > De gustibus non est disputandum.
> > 
> > 
> > That was clear as blue sky. You understand, I ask to learn, not to criticise. Just like with the menu and the html and the _Match Type_ column. No question, no answer, nothing learned. :)
> 
> My VFP session is of width about 3,000. I use it because it's available.
> 
> My GF form occupies all that space. There are about a dozen columns in GF that make any sense at all. I have all of them visible, even though there are some that I rarely use I take full advantage of all the information about a match that GF provides.
> 
> I have re-ordered the columns and changed their widths to fit my needs.
> 
> I feel constrained working on my laptop (as I have been for the last two months) as the width is only 1,920. I have to scroll to see many of the columns to the right.

My _VFP is on the 4k too, and I have 3 monitors more. Guess how laptop feels ...    
I'm used to CodeReferences, found that way before GoFish, and GoFish was (to me) unusable with this single set of options/storage, so I'm comfortable with minimum.   
There is a bunch of hidden columns in teh table. You could turn on dlDebug in GF_ResultsForm.FormatGrid and recompile. See https://github.com/VFPX/GoFish/blob/master/docs/New_6.md#visibility, the picture is missing:   
![GF6_AllFields](https://github.com/VFPX/GoFish/assets/27769909/51085196-7a66-4cb1-a1c5-35be62fb6674)

**Comment by Jimrnelson** [comment]
@lscheffler @DougHennig 

Lutz --

I have decided not to participate in any more discussions about GF6.

While I respect the time and effort you have invested in creating GF6, I find the discussions with you to be not worth my time or effort, as you make it clear time and again that only your judgement matters, no matter how whimsical that judgement might be.

I have experienced this on a number of different issues with you, but will use the issue in this thread as a case in point.

The topic does not affect you directly (since your GF form is normally not wide enough to see any difference), nobody has reported a problem or asked a question about this, you've been told that the issue was a product of discussion and conscious design by the implementers, the code in GF5 has been running for about a decade (so it is certainly well established), and one user in particular (me) has told you that the change you want to make will simply make the GF form unusable.

And yet you insist on imposing your will to change it.

So, I've had enough.  I wish you good luck in your continuing work with GF6.

**Comment by lscheffler** [comment]
I'm sorry that you see it that way, only things are changing, or we still would work like WordStar or vi. Sometimes it breaks behaviour. You are free to like it or not.     
I have a general schedule, and what ever will happen, this isuue will not be implemented this month. I stuck with a different problem, this is not about this topic.   
You are the only one complaining, so maybe it's not that urgent? You are *one* and I'm *one*, and **I** see things different. So there is time, I see your point - but mine is as valid. If somebody else jumps in, I'm willing to change, but not something I hate for one single user. 

I'm sorry you will leave, you gave a lot of help and insight. Fell free to change your mind at any time.

**Comment by lscheffler** [comment]
@Jimrnelson please check #155. What do you think about just turning resize off?

**Comment by Jimrnelson** [comment]
@lscheffler 

I thought I would like turning anchors off, until I looked at what the default would be. 

![image](https://github.com/VFPX/GoFish/assets/81179335/34243f96-0518-4996-8ad6-213a32df25e2)

For me, that does not leave enough room for the scope, so that would not an improvement.

For my own personal use, I have implemented some simple code, similar to what I referred to earlier in this thread, that allows the anchors to work for a while as the grid is expanded, but then stops and acts like there aren't any anchors.

The code (which admittedly has dependency on some fixed values) looks like this (I would suggest having the value of 1400 being an option, with a very large initial value so that it would not affect anything.)

	loGoFish = _Screen._GoFish.oResultsForm

	lnChange = m.loGoFish.Width - 1400
	If m.lnChange > 0

		For Each m.loControl In m.loGoFish.Controls FoxObject
			With m.loControl
				Do Case
					Case .Top > 36 && skip

					Case .Left > 500
						.Left = .Left - m.lnChange
					Case .Width  > 200
						.Width = .Width - m.lnChange
				Endcase
			Endwith
		Endfor

		loControl = Null

	EndIf
	
	loGoFish  = Null

**Comment by Jimrnelson** [comment]
A few more comments on the code I supplied for the anchored controls atop the form:

[1]  It that code is used in the Resize event of the form, the resizing works smoothly (no herky jerky movements).

[2]  The effect looks like normal anchoring (controls expand/contract) for form width < 1400.  Once form width > 1400, it looks like the the controls are no longer anchored.

[3]  The value of 1400 was a completely arbitrary value Matt Slay and I chose so that we thought the controls on the left would be "wide enough".

**Comment by lscheffler** [comment]
Possibly the old way of things, then. Clearer and better self documenting code.

Fancy. I would never enter a search, catch the mouse and move to this fish button. It's just search_string+enter. And then it's no problem, aside that the big boxes are ugly.

**Comment by Jimrnelson** [comment]
@lscheffler 

I certainly agree that if all you're doing is string_search+enter then the position of the controls on the right is immaterial.

However, those controls are there to be used -- and the one I use most often is the dropdown for the scope.  Mousing way over to the far right for that is indeed annoying.

BTW, Happy New Year.

**Comment by lscheffler** [comment]
That was the noise last night about.  The stone finished another orbit. Thank You! A Happy New Year to you as well!

**Comment by Jimrnelson** [comment]
@klepetox 

This feature from Version 5 has been re-implemented in Version 7, released 2024-03-08.

It works like this:

- If the form width of GF is 1500 or less, the controls atop the form respond normally to their Anchor properties.
- If the form width of GF is more than 1500, the controls atop the form respond as if the form width is 1500.

This feature appears to be a duplicate of #155.
