### ISSUE TITLE
Soft bug:  "Replace Line" column not being filled in to show what replacement will look like

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#106]
## ℹ Computer information

- VFP version:  9 SP2
- GoFish version: 6.2.002
- Last GoFish version w/o bug (if available): 5

## 📝 Provide detailed reproduction steps (if any)

When in Replace mode and rows are selected to be replaced, the "Replace Line" column no longer shows what the replacement will be:

![image](https://github.com/VFPX/GoFish/assets/81179335/1df7a999-483f-44c9-a5dc-4729c482a62f)

This is what it looked like in GF5:

![image](https://github.com/VFPX/GoFish/assets/81179335/74fb41f0-b0d3-4873-ba61-34037a9b8831)

**Comment by lscheffler** [comment]
Does it help to turn *preview* on?   
![grafik](https://github.com/VFPX/GoFish/assets/27769909/35558bc9-cf0e-417f-8cca-121839699202)

**Comment by Jimrnelson** [comment]
Yes, that does help.

HOWEVER, I should not have to turn that option on.  You should have it turned on by default.

The previous behavior was to show the preview.  

When a user starts using Replace mode, they should start off seeing the same behavior in V6 as they did in V5 (as much as that is possible).

With your new option, the user can indeed decide they no longer wants to see the preview, However, you should not be forcing them to find and use an option to get back to what they have been seeing for as long as they were in V5.

**Comment by lscheffler** [comment]
Speed considerations.    
Setting should be saved. ¯\_(ツ)_/¯

**Comment by Jimrnelson** [comment]
> Speed considerations.

Speed considerations are secondary to having GF perform as it did before (except for added functionality).

If some user is concerned about speed, you have provided them with a way not to see the replace line, but you should not be changing the behavior for all other users.

> Setting should be saved.

It's not clear to me what this statement means.

>  ¯_(ツ)_/¯

I suggest you not assume that we all know what this means.

**Comment by lscheffler** [comment]
The setting of *Preview* is stored with the settings, and will be available next time you use it.

You are right, this is misspelled, it should be:  [¯\\_(ツ)_/¯](https://www.google.com/search?client=firefox-b-d&q=+%C2%AF%5C%28%E3%83%84%29%2F%C2%AF)

**Comment by Jimrnelson** [comment]
> The setting of _Preview_ is stored with the settings, and will be available next time you use it.

The issue is not whether its saved (I assumed it is), but that the initial value is wrong.  It should be on initially, not off, so that users see the familiar behavior from GF5.  Users who don't want to see it (speed issues) can turn it off.
