### ISSUE TITLE
Soft bug:  Code view not showing replacements

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#107]
## ℹ Computer information

- VFP version: 9 SP 2
- GoFish version: 6.2.002
- Last GoFish version w/o bug (if available): 5 

## 📝 Provide detailed reproduction steps (if any)

When a row is selected for replacement, the Code View window does not show the old/new text.

Here's what it should look like, from Version 5:

![image](https://github.com/VFPX/GoFish/assets/81179335/d8ab0eec-ae55-411c-9099-95dacc280cf4)

**Comment by lscheffler** [comment]
see #106
