### ISSUE TITLE
Window position openening code from GoFish

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#11]
## 📝 Provide detailed reproduction steps (if any)

1. Search something
2. double click in grid

### ✔️ Expected result

Should open code window on position last time used with last size

### ❌ Actual result

Will open on top left corner, on visual classes both the class window and the code window.

#### Update:   
Right now only the code window moves top left (it visually moves, it instantiates on the position stored and then moves)

**Comment by rschummer** [comment]
The code window is moved to the upper right corner after it is originally displayed in the location stored in the FoxUser file. I am wondering if code was added when the Desktop feature was added to position the window. Note, if you are opening a VCX-based class, the Class Designer remains in the last position. It is just the code editor windows that seem to move to the 0,0 spot.

**Comment by lscheffler** [comment]
@rschummer After I figured out my local repo remote still pointed to Matt I've tried to look it up through  git history. It's impossible to trace changes - sometimes there is a change to the FoxBin2Prg files, sometimes not, sometimes total rewritten files. 
:(

**Comment by lscheffler** [comment]
The culprit is in Method _EditFromCurrentRow_ of _GoFishSearchEngine_ in _gofishsearchengine.prg_

At the end of the method is an if block
```
		If m.lcExt = 'PRG' Or Not Empty(m.lcMethodString)
			This.ThorMoveWindow()
		Endif
```
It even assumes that the PRGs are opened inside VFP - something I do not for decades. TEDIT

**Comment by DougHennig** [comment]
Commenting out the call to This.ThorMoveWindow resolved the issue. I'll push the changes once we have some of your other issues resolved.

**Comment by lscheffler** [comment]
@Doug I already made it an option and will push to my fork. :)
