### ISSUE TITLE
Unable to convert GoFish5 to GoFish6

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#110]
Could you please make an issue here for helping fix this upgrading issue? Where to send attachments etc.

**Comment by lscheffler** [comment]
Hi Mike, on GF 6 try `MODIFY FORM gf_migrate_6.scx method init`, the mail address is provided there. This is the migrate form that was shown before migrating.

**Comment by myearwood1** [comment]
You really do not care at all about making the life of the users easy, do you? I should not be ordered by you to go look in your code to find information that should be here. When I said go back to 5, I misspoke. What I mean is you should not have forced the upgrade from 5 to 6. You should have pushed aside the 5 files. Installed 6 cleanly in a way that it did not share the locations of the 5 files. Leaving both 5 and 6 viable. Then offer an optional upgrade. If that is too much work, then explain that instead of just disregarding my input.
