### ISSUE TITLE
Problem in Thor Tools

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#111]
@Jimrnelson, I need some help.
## ℹ Computer information

- GoFish version: Before 5.*

## 📝 Provide detailed reproduction steps (if any)

1. Check Thor\Tools\ for Thor_Tool_GoFish5.ERR / Thor_Tool_GoFish5.prg
3. There is an odd ENDPROC after the DEFINE
4. seems to be added by Thor, but I guess it's about odd GoFish code
5. see GoFish(5).prg RegisterAppWithThor, it defines this class as CODE property, without the ENDPROC

_What is the expected way to create the plugin / code thing?_

**Comment by Jimrnelson** [comment]
Actually, this only a problem if you try to open the PRG and save it manually.  I have known about this for years and just ignore the errors.

The PRG is actually created when you run GF (it tries each time!) and it works fine.  

The problem where is a TEXT/ENDTEXT that where the contents have PROC/ENDPROCs and DEFINE CLASS/ENDDEFINE blocks.  Apparently VFP is enable to properly diagnose which blocks are simply text and which are real code.

So, in essence, just ignore the problem.  It works and has been working for a long time.

**Comment by lscheffler** [comment]
First, ok, I can ignore this further on.
Somehow it compiles and run, even with the error.

The TEXT/ ENDTEXT is not the problem. This block is inside the DFEINE / it's INIT method and closed well. The class closes well.
The prog is  like
```
main

procedure ToolCode
..
endproc

Define Class clsGoFishFormatGrid As Custom
..
  procedure init
     text
     endtext
  endproc
enddefine

EndProc 
```
The final ENDPROC is added by Thor

I guess, the definition from GoFish adds the ENDPROC for ToolCode, then the class, and Thor thinks it just gets some additional code to ToolCode and tries to close the procdure.

I guess cheapest might be to add a "*;" after the enddefine, that will fix it. :)

Thanks for listening.
