### ISSUE TITLE
VarType error on GF Open & After search

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#116]
## ℹ Computer information

- VFP version: 9 w/ SP 2
- GoFish version: 6.2.002

## 📝 Provide detailed reproduction steps (if any)

Still getting errors when I first open GF:
	gf_ResultsForm1.PopulateTreeView
		If Vartype(m.loNode)="O" Then
				loTree.SelectedItem	= m.loNode
		*move search area in visible focus
	loTree is .Null.
If I ignore this and the two folllow-on errors, all seems well.

Have the same situation after the search is complete.

I'm presuming that this is particular to my system...
?1. If reinstalling a clean version might fix the issue, how do I remove ALL GF components?
?2. Otherwise, what info can I give you to help identify the cause?

Update:   
This is more or less a duplicate of #96?

**Comment by lscheffler** [comment]
Closed, OP can not reproduce any more.
