### ISSUE TITLE
Cannot find entry point SetClrVersion in the DLL (wwdotnetbridge)

### ISSUE THREAD

**Issue by matthewaceware** [VFPX/GoFish#117]
## ℹ Computer information

- VFP version: 9sp2
- GoFish version: latest
- Last GoFish version w/o bug (if available): new install

## 📝 Provide detailed reproduction steps (if any)

Trying to launch GoFish from the Thor menu.

### ✔️ Expected result

GoFish

### ❌ Actual result

Error message, "Cannot find entry point SetClrVersion in the DLL." Points to the line:
SetClrVersionApi(lcVersion)
in wwdotnetbridge.prg.

I'm sure this is a blocked DLL, but I can't find where the DLL is. This is a fresh install of VFP, Thor, GoFish, etc. on a new machine. Not sure where to go from here, though. Any help is appreciated.

**Comment by DougHennig** [comment]
wwdotnetbridge isn't used in Thor or GoFish so something else is going on.

**Comment by lscheffler** [comment]
@DougHennig There is some use of wwdotnetbridge to get better use of .Net, see https://github.com/VFPX/GoFish/blob/master/docs/Changes.md#ver-62001

@matthewaceware This should be located in Thor install in *Thor\Tools\Apps\GoFish5\SF_RegExp*, or using Thor its Menu Thor/Folders/App, and there *GoFish5\SF_RegExp*

**Comment by Jimrnelson** [comment]
Yet another example of why debug windows would be so helpful in diagnosing problems.

**Comment by lscheffler** [comment]
@Jimrnelson Not really, this is simple in wwdotnetbridge.prg as you can see in OM.    
```
PROTECTED FUNCTION SetClrVersion(lcVersion)
DECLARE Integer SetClrVersion IN WWC_CLR_HOSTDLL AS SetClrVersionApi string
SetClrVersionApi(lcVersion)
ENDFUNC
```
So it does not see  WWC_CLR_HOSTDLL -> clrhost.dll, what is inside the directory from above.

**Comment by Jimrnelson** [comment]
Yes, really, it does help to always ask for as much information from a user as possible.

Even if, in this case, you did not need it.

**Comment by matthewaceware** [comment]
So, there are no dlls in this folder. I'm trying to track them down, now.

**Comment by matthewaceware** [comment]
I've downloaded the three dlls that I am seeing in this repo in that folder. I am still getting the same error. DLLs are unblocked.

**Comment by lscheffler** [comment]
@matthewaceware Download https://github.com/VFPX/GoFish/blob/master/Source/Source.zip and expand to the GoFish5 folder. Seems related to https://github.com/VFPX/Thor/issues/143

**Comment by lscheffler** [comment]
@Jimrnelson As much as possible. Hm, there is the problem with getting a message at all. See the problem in FoxBin2prg where it runs fine on all my systems, and the user with odd code page can nit do simple tests. So, I call it even. And the message here was one of the good.

**Comment by matthewaceware** [comment]
I've downloaded that folder. unblocked it, and then overwrote everything in that folder. I'm starting VFP fresh and then calling up Thor. Then I try to run GoFish and I hit the error. If I ignore 3 times, I can get into the application. Haven't tried in searches, yet.

**Comment by lscheffler** [comment]
@matthewaceware  As Jim suggested, please give a snapshot of debuggers call stack for the first call, and the recent directory. If possible, check the calling parameter of `SF_RegExp`

**Comment by lscheffler** [comment]
Could you give me your OS? What .NET versions are installed?

**Comment by matthewaceware** [comment]
Win 11. .NET 4.8.09032
And the problem becomes obvious when I look at sf_regexpath. There is a Thor folder inside of my Thor folder. Not sure why. But apparently GoFish is looking at the wrong one (or Thor is, not sure which it is at this point). So, if I copy from one thor to the other, I get the application up without an error.

**Comment by lscheffler** [comment]
Something is odd. Possibly GoFish is started from an odd place.   
There is a place where Thor.App is, and next to this is a Thor folder. Inside this folder there should be no extra Thor folder. Just like:   
![grafik](https://github.com/VFPX/GoFish/assets/27769909/0de4cb96-1c37-475a-ba71-65fe0e1a696a)

**Comment by lscheffler** [comment]
For https://github.com/VFPX/GoFish/issues/117#issuecomment-1675405866. Is this a GoFish installed without Thor self-integrating to Thor?

**Comment by matthewaceware** [comment]
That directory matches mine except that I have a Tools in the top thor folder as well as the second thor folder. Both have Apps. Both have GoFish listed in there.

I'm not sure what you are asking with your latest comment, but I'll take a guess. I installed Thor first. I then asked it to install GoFish for me. I hope that answers your question.

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.
