### ISSUE TITLE
After applying a filtering, treeview still shows files that the filter removed

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#118]
## ℹ Computer information

- VFP version: 9 SP2 build 7423
- GoFish version: 6.2.002
- Last GoFish version w/o bug (if available): Don't know

## 📝 Provide detailed reproduction steps (if any)

1. Run a search with a lot of results
2. Apply a filter that removes some of the results.

### ✔️ Expected result

The treeview would only show files that contain a result that matches the filter

### ❌ Actual result

Treeview appears to be unchanged. When I click on a file that isn't in the filter, the Code View pane says "Not in filter." This makes filtering pretty much useless, since I still have to wade through all the files to find the ones I'm interested in. (Yes, I could look in the results grid, but when I have some idea what I'm looking for, being able to see the file names is important.)

**Comment by TamarEGranor** [comment]
Yes, if I pick something not in the filter from the treeview, the grid becomes empty.

I'm emailing you the folder you want.

**Comment by lscheffler** [comment]
@TamarEGranor If you have a result with classes and non-classes and filter out the results in the classes, do the classes in the ClassLib/Filename nodes disappear? (you could not expand those nodes anymore)

**Comment by lscheffler** [comment]
How about the node named "Classes", it should show the files, but nor the classes (right now).

**Comment by TamarEGranor** [comment]
It shows the names of the classes, but when I click on them, as before, empty grid and "Not in filter."

**Comment by lscheffler** [comment]
Odd. Possibly I had something already changed something.

**Comment by lscheffler** [comment]
Should be fixed in 6.2.004
