### ISSUE TITLE
Error opening menu editor by clicking on the row in the grid with results

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#119]
## ℹ Computer information

- VFP version: 09.00.0000.7423
- GoFish version: 6.2.002
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Grid with results, when I click on the row with code from menu (any menu), menu designer is open, but with error.
2. When I click on the menu in the tree view, menu designer is open without error.

### ✔️ Expected result
Open menu designer

### ❌ 
Open menu designer with error: "Alias 'CSRSUMMARYSEARCHRESULTS' is not found."

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.
