### ISSUE TITLE
error "invalid path or file name" 

### ISSUE THREAD

**Issue by PatrickvonDeetzen** [VFPX/GoFish#120]
## ℹ Computer information

- VFP version:  09.00.0000.7423
- GoFish version: 6.2.002
- Last GoFish version w/o bug (if available): 5.X 

## 📝 Provide detailed reproduction steps (if any)

1. Start "GoFish5.APP"

### ✔️ Expected result

- GoFish start as usual 

### ❌ Actual result

- GoFish shows error "invalid path or file name" and form "Migrating to Version 6" shows up giving some information (TLDR: "i know this error exists, i got no no idea how to fix this, just click ignore, please be gentle")

**Comment by lscheffler** [comment]
Do I understand your fix in  #121, that you run GoFish.prg instead of the app?

**Comment by DougHennig** [comment]
I believe this is fixed in GoFish 6.2.005.
