### ISSUE TITLE
Stop on first find

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#129]
Sometimes I'm trying to find an example of how the people I inherited this massive rat's nest from did a thing. I can only remember part of the command. It would be nice if GoFish could stop on the first instance found.

**Comment by Jimrnelson** [comment]
You can achieve this by setting the value of "Maximum number of results to find" on the Options form to 1.

![image](https://github.com/VFPX/GoFish/assets/81179335/02cf1cc8-6366-4acc-9884-5ddf12e2bbf7)
