### ISSUE TITLE
GoFish and GoFish5 both open Gofish 6.2

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/GoFish#130]
GoFish and GoFish5 both open Gofish 6.2 ?

![image](https://github.com/VFPX/GoFish/assets/31514812/a69217ff-8896-431a-bf2b-14d8e7055eaf)

Warm regards,
mk.

**Comment by DougHennig** [comment]
We're working to resolve this.

**Comment by DougHennig** [comment]
This has been resolved.
