### ISSUE TITLE
Error during Check For Updates for latest version of GF

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#131]
## ℹ Computer information

- VFP version: 7423
- GoFish version:  latest after CFU download
- Last GoFish version w/o bug (if available): 5.1.009

## 📝 Provide detailed reproduction steps (if any)

Running CFU to install latest update

### ❌ Actual result

After it appears that the download of all files into the GoFish folder, I get the following obscure error message:

![image](https://github.com/VFPX/GoFish/assets/81179335/bfd3ccff-0b74-4c11-9eb4-c2faab44fd34)

I have verified that this occurs when GoFish is trying to register its tool for Thor (Thor_Tool_GoFish.prg) which is invoked from the Thor Updater:

![image](https://github.com/VFPX/GoFish/assets/81179335/bee33119-abf1-43ab-8e0d-3c0853957626)

I have found that if I call the new version directly, like this, I still get a similar same error.

![image](https://github.com/VFPX/GoFish/assets/81179335/2cdc2ec9-9892-40b9-9e16-372b4ecd5387)

![image](https://github.com/VFPX/GoFish/assets/81179335/f385bd1e-b33a-435c-92ee-2bdb7587b76f)

Thus, right now, GF v6 is not usable.

**Comment by DougHennig** [comment]
Fixed in the latest build
