### ISSUE TITLE
Gofish Error

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/GoFish#132]
Gofish Error as Attached

![image](https://github.com/VFPX/GoFish/assets/31514812/1ceb6518-aabe-4d12-ac7a-1bb6b7ea672f)

Warm regards,
mk.

**Comment by mksharmamk** [comment]
![image](https://github.com/VFPX/GoFish/assets/31514812/b43389ab-379e-458f-bda4-d4aaf51384ce)

Warm regards,
mk.

**Comment by mksharmamk** [comment]
To reproduce 1St error:-
1. Start Vfp
2. Start Gofish 
3. close Gofish  
4. Start Gofish classic 

Now it is showing error.

To reproduce 2nd error
1. Start Vfp
2. Start Gofish classic 
3. close Gofish  classic 
4. Start Gofish 

Now it is showing error.

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

Clearly there is a problem with the interplay between using GoFish v6 and GoFish Classis v5.1 in the same session.

I suggest using one or the other in the same session, but not both.

I have no intent on ever making any changes or updates to GoFish Classic v5.1 -- it is what it was as of earlier this year.

**Comment by DougHennig** [comment]
Fixed in the latest version.
