### ISSUE TITLE
Gofish not showing in the list of check for Updates

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/GoFish#134]
Gofish not showing in the list of check for Updates

![image](https://github.com/VFPX/GoFish/assets/31514812/9fceddee-88df-4efe-83ba-ce66d3fcb3fb)

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

There have been problems with the most recent update to GoFish, so the update to it has temporarily been removed.

It should be back within a day or so.

**Comment by Jimrnelson** [comment]
This problem (GoFish not appearing in CFU) has been fixed.
