### ISSUE TITLE
Gofish Versions

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/GoFish#138]
Gofish Showing 3 projects in menu
1. Gofish - This open the Version 6.2.005
2. Gofish Classic - This open the Version 5.1.009
3. Gofish5 - This open the Version 6.2.002

Which Version should we use ?

![image](https://github.com/VFPX/GoFish/assets/31514812/3e4996ca-3295-485b-b2b0-b3d4c2aa4ceb)

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

**GoFish** is the current version of GoFish.  It was given this new name a few weeks ago.  (The current version is 6.2.005 so calling it GoFish5 was certainly confusing.)  There will be updates / enhancements / corrections over time.

**GoFish5** was the version before the name change.  There will be no updates. It is frozen.  (The name change did not remove this older name.)

**GoFish Classic** is the latest version of GoFish v5, released for use by those who had troubles installing or using the newer version of GoFish V6.  There will not be enhancements to it, so it is essentially frozen as well, except possibly for bug fixes.
