### ISSUE TITLE
Go Fish button on main screen vs on Advanced screen.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#143]
The Go Fish button on the main screen should do a default search of everything for the settings on the main screen. On the advanced page, that "Go Fish" button should search the advanced settings.

This would be more like Google search where you can do a simple search OR an Advanced search. The two modes should not affect each other.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Normal searches would be the outcome of the main page. Advanced searches would be the outcome of the advanced page. Retain the settings of each independently so the user might re-do a recent advanced search, while having a separate default search.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
The "Advanced" screen is the place for advanced and thus less frequently modified settings.

A long time ago, the only controls atop the main screen were the search phrase and scope.  All other settings lived in the Advanced screen.

Over time, many of these settings were replicated on the main screen.  This creates some confusion as these settings are visible in two different places.

That is why the Advanced screen was recently modified (Version 7.0.17 - 2024-03-23) to only show those options not already appearing on the main form.

**Comment by myearwood1** [comment]
Sounds right!
