### ISSUE TITLE
Crash on Advanced search with UDF replace

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#148]
## ℹ Computer information - Windows 10 is otherwise Irrelevant unless you have multiple machines and can match mine for testing.

- VFP version: 9
- GoFish version: 6.2
- Last GoFish version w/o bug (if available): I cannot go back and try other versions because I only found it in the latest version I have. Apparently you are not restricting updates to GitHub and that is a violation of the spirit of GitHub.

## 📝 Provide detailed reproduction steps (if any)

Do a search. I searched for REPORT FORM
Click Replace View
Click advanced replace
Click OK on the warning screen.
check one entry in the replace column.
Create a UDF
Click replace checked
Crashes on line 45 in gofishsearchengine.prg,GoFishSearchEngine,BackupFile

GF_Write_Readme_Text(4, Addbs(m.lcBackupFolder) + 'README.md', .T.)
The lcBackupFolder variable does not yet exist. ccBackupFolder is a constant. Is lcBackupFolder supposed to be ccBackupFolder?

**I replaced lcBackupFolder with ccBackupFolder and the crash did not happen. It seemed to carry on properly. So not only do I report the bug, but I provide the repair, something very few of the reported issues have.**

✔️ Expected result
It should not crash.

❌ Actual result
It crashes.

I am capable of contributing to this project. I RESENT the mistreatment I have received from members of this community. However, GitHub's rules and enforcement are better than those of the FoxPro sites and the bias has been reported.

I would offer a truce, but having criminal LIBEL made against me and the perpetrator not punished leaves me little choice but to work toward his removal.

Your call Doug

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.
