### ISSUE TITLE
Options to seach Comments

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#150]
## 📝 Description of the new feature

Adding an option to alter to Comments Option in Advanced 
- without Comments
- with Comments
- in Comments only

For an idea how to code *Comments only*, see https://github.com/VFPX/GoFish/discussions/97#discussioncomment-7536969
 
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
This feature has been implemented in Version 7, released 2024-03-08, as a filter option.

Once a search is complete, the new filter "Comments Only" is available.

![image](https://github.com/VFPX/GoFish/assets/81179335/465a8324-af14-4a1c-bf65-27e43c51bb2f)
