### ISSUE TITLE
Mode Plain/Wildcard/Regex

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#152]
## 📝 Provide a description of the new feature

If the user search string contains no wildcard characters, why does it not default to the plain search? If the user search string only contains wildcards but no regexp, why not default to wildcard? 

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Easier use of GoFish, less need to make searches. Like GMail, maybe put in a special identifier for the search type. ~~* is a wildcard * and ~~? is a wildcard single char. Is there not already something that must indicate regexp? Neither of these is then a plain search.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
What has been implemented in Version 7, released 2024-03-08 is the following:

If regular expression search is chosen and the search expression doesn't contains special characters for regular expressions, plain search is used instead.  This results in searches that are about four times faster then regular expression search.

No change is made if wild card search is chosen and no wild card characters are used as there is no perceptible speed advantage in doing so.
