### ISSUE TITLE
Add ProjectEditor as scope

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#156]
## 📝 Provide a description of the new feature

Now the scope can be either a directory (tree) or a project.   
Since there is ProjectExplorer with multiple projects, this could be a possible scope.

---
If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by DougHennig** [comment]
Behind the scenes, Project Explorer opens any projects in the solution (MODIFY PROJECT NOSHOW) so perhaps the scope should be all open projects. That way, it is generic and not specific to Project Explorer but will work with any projects open in a PE solution.

**Comment by lscheffler** [comment]
I think this (*All projects open in IDE*) would be an additional scope. (you might add a feature request)

What I think why it should remain as single PE:
- we could have multiple PE open 
- we could have PE and PJX outside PE open

**Comment by Jimrnelson** [comment]
This feature has been implemented indirectly in Version 7, released 2024-03-08 with the new Search Mode combobox.

Project Explorer opens and hides all projects in a solution, so this has the desired effect:

![image](https://github.com/VFPX/GoFish/assets/81179335/de4a338e-a020-44c5-affc-033feae37dc4)
