### ISSUE TITLE
Options Dialog Desktop checkbox crashes on InteractiveChange code

### ISSUE THREAD

**Issue by ToniKoehler** [VFPX/GoFish#162]
## ℹ Computer information

- VFP version: 9.0.0.7423
- GoFish version: 6.2.007
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Run GoFish for my first time
2. Open Options dialog
3. Toggle Desktop checkbox

### ✔️ Expected result

To be able to toggle the Desktop checkbox without an error message.

### ❌ Actual result

Program Error
File 'GF_Results_Form_Settings.xml' does not exists.

The problem is, that ADDBS(HOME(7)) + 'GoFish' is not in my SET('PATH').
After I click "Ignore" the GF_Results_Form_Settings.xml will create in my SET('PATH') and I can save the Deskop-Property.

## 📷 Screenshots

![image](https://github.com/VFPX/GoFish/assets/44064940/e7fe3f35-9856-48c7-9aad-9861b8808578)
![image](https://github.com/VFPX/GoFish/assets/44064940/50fd4786-e6f8-46c8-92a2-ef2814248837)

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.
