### ISSUE TITLE
color-settings will not affect the search-result inside the grid

### ISSUE THREAD

**Issue by ToniKoehler** [VFPX/GoFish#163]
## ℹ Computer information

- VFP version: 9.0.7423
- GoFish version: 6.2.007
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish
2. Open the Option-Dialog
3. Change the colors under TAB Colours

### ✔️ Expected result

The color will change like my settings.

### ❌ Actual result

The color-settings will not affect the search-result.

## 📷 Screenshots

![image](https://github.com/VFPX/GoFish/assets/44064940/76f53401-d50e-4329-a779-2c7460c6686e)

**Comment by ToniKoehler** [comment]
Current workaround is to change the color by Plug-In.

![image](https://github.com/VFPX/GoFish/assets/44064940/20093513-a5fa-4568-bed2-874dece2a834)

**Comment by Jimrnelson** [comment]
@ToniKoehler 

Actually, that "workaround" is an enhancement, available through Thor, to allow you to write to set dynamic forecolors and backcolors to fit your taste.  

The color selection provided by GF is limited in that it assumes that you want to assign colors based on the file extension and/or replacement information.  This may be satisfactory, of course, but there could be other criteria.

For me, personally, I use a number of criteria, including the type of match.  I also bold some lines.

I have attached the version that I use.  (You'll want to paste its contents in, it's not usable directly.)

[Gofish_Formatgrid.txt](https://github.com/VFPX/GoFish/files/14380635/Gofish_Formatgrid.txt)

**Comment by ToniKoehler** [comment]
@Jimrnelson 
Yes I know that the colors based on the file extensions, but without the Plugin every line inside the grid is colored black. The color settings won't have affect.

![image](https://github.com/VFPX/GoFish/assets/44064940/4a47ed0f-b87e-4950-9c9f-15f46a94e7b9)

**Comment by Jimrnelson** [comment]
@ToniKoehler 

I have no experience with that part of GF (since I use the plug-in)

I'm wondering if perhaps the changes do not take effect until you close and reopen the form.  Just a wild guess.

In any case, this looks like something that needs to be looked into

**Comment by Jimrnelson** [comment]
Yup, this is a bug.

I expect to have it fixed in the next update to GF.

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.
