### ISSUE TITLE
Type Mismatch error on open

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#171]
## ℹ Computer information

- VFP version: 9 SP2
- GoFish version: 6.2.007
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish

### ✔️ Expected result

_What is the expected result of the above steps?_
App opens w/o error
### ❌ Actual result

_What is the actual result of the above steps?_
OLE error "Type mismatch"
Have been getting this error for quite some time.
If I 'Ignore" (for this and the next two errors) everything is AOK.
## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
![image](https://github.com/VFPX/GoFish/assets/34778960/1da2f495-1263-4326-9404-5a953fa748cc)
NOTE: loNode is an object; loTrree.SelectedItem is .NULL.

**Comment by Jimrnelson** [comment]
Bob --

Please supply more information on this, as the following images would all be helpful:

- The actual error screen
- The locals list from the debugger
- The call stack from the debugger

Thanks.

**Comment by BobWilkes** [comment]
And today when I open it, I don't get the error.
Stay tuned...
Bob

**Comment by Jimrnelson** [comment]
Bob--

I am releasing a major upgrade to GoFish, Version 7, early tomorrow morning.  

I am going to close this item and ask that you create a new issue for it if it still happens in the new release.
