### ISSUE TITLE
What does the yellow strip in color settings mean?

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#174]
This is not a bug, but what is the yellow vertical strip for?

## 📷 Screenshots

![1](https://github.com/VFPX/GoFish/assets/142881527/d76e1bf2-47d2-41c9-b616-6a5ca15ce432)

**Comment by Jimrnelson** [comment]
@klepetox 

That's a very odd display.  It is not part of the that form, so I can't explain it.

It looks somewhat like something is bleeding through from behind the form.

Does it move when you move the form?  Is it still there if you close VFP and restart?

**Comment by klepetox** [comment]
Does it move when you move the form? - YES
Is it still there if you close VFP and restart? - YES (version 6 and 7)

My display DPI is 144 (150 %). When I set basic DPI 96 (100 %), the yellow strip dismissed. But then is back again.

**Comment by Jimrnelson** [comment]
This sounds like it's a funky behavior as a result of your use of DPI and not anything in GF itself.

**Comment by klepetox** [comment]
I've got it! It's a fragment of picture "browsefolder.bmp" on [...] buttons, that is partly visible in higher DPI, you can try it yourself. The higher DPI, the more visible it is.

**Comment by Jimrnelson** [comment]
Good catch!  I'll do so in the next release.

**Comment by klepetox** [comment]
Thanks for your outstanding work.

**Comment by Jimrnelson** [comment]
You're welcome!  Your acknowledgement is certainly apprecidated.
