### ISSUE TITLE
New button to click project doesn't actually set project

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#178]
## ℹ Computer information

- VFP version: VFP 9 SP2 Build 7423
- GoFish version: 7.0.12

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish
2. Type in a search string
3. Set scope to Browse Project, if it isn't already
4. Click the button immediately to the right of the Project/Folder dropdown (with tooltip "Click to pick project")
5. Navigate to a project file and click OK

### ✔️ Expected result

The project/folder dropdown to be populated with the chosen project.

### ❌ Actual result

The Project/Folder dropdown is empty. If you try to search now, you'll get an error.

### Notes
I see a similar, but slightly different problem when I use the next button ("Click to pick folder"). It, too, fails, but the dropdown seems to go back to a previously chosen folder. 

Sorry for missing this in beta testing. I don't remember noticing these buttons before today.

**Comment by Jimrnelson** [comment]
Just when I thought my Issues list was shrinking!  Good catch!

**Comment by Jimrnelson** [comment]
This bug fixed in Version 7.0.14 - 2024-03-15.
