### ISSUE TITLE
Code browser zoom factor doesn't work

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#179]
I'd like to have a little small font in code view window. If I set it smaller in settings, it doesn't have any effect. I have my set point to comma, I tried to set it to point, but without any conclusion. It is not a bug, but can you look at that?

**Comment by Jimrnelson** [comment]
@klepetox 

Actually, this is a bug.  No matter what is set in the options form, the code view pane remains the same.

And, this is an OLD bug. I have an old version of GF, 5.0.170 from 3/24/2021, and it failed back then as well.  My guess is that is has not worked since then (at least)

I will leave this issue open but without any real hope of correcting the problem, as I have no knowledge of how to apply zoom factors to a browse.

**Comment by klepetox** [comment]
This is really not important. I'd rather set the fontsize in CSS. But GoFish_.css in HOME(7) is now ignored. Modifying CSS in GoFish\Source\CSS has also no effect. But there is no need to solve this.

**Comment by Jimrnelson** [comment]
I'll see if I can get that private CSS file fixed for next release.

Can you attach your file so I can try it myself?

**Comment by klepetox** [comment]
This is my HOME(7)\GoFish_\GoFish_.css from version 6. In version 7 it is ignored:

`<style type="text/css">

         body {
           font-size: 12px;
         }

		.matchline {
			border-width: 1px;
			border-style: solid;
			border-color: gray;
			background-color: FFFF80;
			margin-top: -17px;
			margin-bottom: -32px;
			padding-top: 0px;
			padding-bottom: 1px;
		}

		.matchline pre {
			margin-top: -15px;
			margin-bottom: 0px;
			padding-top: 0px;
			padding-bottom: -5px;
		}

		.strikeout {
			border-width: 1px;
			border-style: solid;
			border-color: gray;
			background-color: lightgrey;
			margin-top: -17px;
			margin-bottom: -32px;
			padding-top: 0px;
			padding-bottom: 1px;
		}

		.strikeout pre {
			margin-top: -15px;
			margin-bottom: 0px;
			padding-top: 0px;
			padding-bottom: -5px;
		}


		.replaceline {
			border-width: 1px;
			border-style: solid;
			border-color: gray;
			background-color: FFFF80;
			margin-top: 35px;
			margin-bottom: -32px;
			padding-top: -20px;
			padding-bottom: 0px;
		}

		.replaceline pre {
			margin-top: -15px;
			margin-bottom: 0px;
			padding-top: 0px;
			padding-bottom: 0px;
		}

		.matchword {
			background-color: #99FF99;
			font-weight:bold;
		}

		.vfpcode{
			color: black;
		}

		.vfpreserved{
			color: blue;
		}

		.vfpcomment{
			color: green;
		}

		.vfpliteral{
			color: red;
		}

		.vfpstring{
			color: red;
		}

</style>
`

**Comment by Jimrnelson** [comment]
The following will take effect in the next release (Version 7.0.13)

* The "Code Browse zoom factor" spinner has been removed from the Options form, as it wasn't working. (#179)
* Instead, a new spinner, "Code View pane font size (px)" has been added. See Options form, "New in Version 7".
* If option "Use IDE colors in Code View pane" is **not** selected, users may supply their own css file, named `HOME(7) + '\GoFish_\GoFish_.css'`

**Comment by Jimrnelson** [comment]
This bug fixed in Version 7.0.14 - 2024-03-15.
