### ISSUE TITLE
New version of GoFish.app compiled in a different version?

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#18]
Thor Updater showed a new version of GoFish this morning. After installing it, when I try to run GoFish, I get this error:

**Object file d:\fox\vfpx\thor\thor-master\thor\thor\tools\apps\gofish5\gofish5.app was compiled in a different version of FoxPro.**

I'm running VFP 9 Build 7423

**Comment by lscheffler** [comment]
:C     
I try to remember next merge.   
Sorry, I can't bear the FoxBin2Prg and git settings, so I work on a different folder then the forked one. My HiRes screen is best with VFPA. And there is a lot steps to publish all the time, forgot VFP9. I improve CONTRIBUTION.md    
Anyway, push is close ...
