### ISSUE TITLE
Replacing in MNX stopped working

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#180]
## ℹ Computer information

GoFish version:  7.0.12

Replace code in menus doesn't work.

✔️ Expected result

When I confirm "Check all" chkbox, everything is checked and I can replace code.

❌ Actual result

After selecting "Check all" chkbox, there is an error "**Source file has changed since original search:    [File: c:\fox\#ukzuz\ukzuz\hsv\!project\menu\mainmnu.mnx]    [Result Id: 27]**"

PRG, VCX and others are OK. I have tried to reset GoFish to default and it is the same.

**Comment by klepetox** [comment]
Screenshot attached.

![MNU replace](https://github.com/VFPX/GoFish/assets/142881527/f08bc52c-c6a7-4a96-a394-e06f58376d00)

I also tried GoFish 6 without error.

**Comment by Jimrnelson** [comment]
This bug fixed in Version 7.0.14 - 2024-03-15.
