### ISSUE TITLE
Error when running search

### ISSUE THREAD

**Issue by FoxTeamDev** [VFPX/GoFish#181]
## ℹ Computer information

- VFP version: 9.00.0000.7423
- GoFish version: 7.0.12

## 📝 Provide detailed reproduction steps (if any)

1. it happens when pressing gofish to perform any search

### ❌ Actual result
receive error: Message: file 'f:\apps\am\gf_search_history.dbf' does not exist.

_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://github.com/VFPX/GoFish/assets/90854372/f98aebb6-c093-4453-a11e-5012179b9c2f)

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
This bug fixed in Version 7.0.14 - 2024-03-15.

Related errors in #80, #126.
