### ISSUE TITLE
Results in code pane are doubled from MNX

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#184]
## 📷 Screenshots
![1](https://github.com/VFPX/GoFish/assets/142881527/2f653805-fd21-4e31-bdef-99b9a9606734)

**Comment by klepetox** [comment]
Sorry, as I can see now, that it is not a bug, but a feature. You write out the contents of the procedure here, as Prompt, SkipFor... But sometimes procedure has hundreds lines, isn't it useless and confused?

**Comment by Jimrnelson** [comment]
This issue has been corrected in Version 7.0.15 - 2024-03-17.

**Comment by klepetox** [comment]
I confirm that everything is working as it to be. Thank you Jim for your work.

**Comment by Jimrnelson** [comment]
You're welcome!  Actually, it's my pleasure to work with GoFish again.

And I thank you for getting back to me with your comments.  It's very helpful to get feedback.
