### ISSUE TITLE
Sorting MRU list for search dropdown

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#187]
I think that this list should be sorted strictly by last written expressions. For example, try to set only 3 items in Options and start searching with expression - "111", "222", "333", "444", "111" - in this case the last "111" is not in the list at all and you have to write it again and again.

Also there should be some possibility to remove items (typo...) - f.e. Del, Ctrl+Del, Alt+Del (?) in the list.

**Comment by Jimrnelson** [comment]
This problem corrected in Version 7.0.17 - 2024-03-23
