### ISSUE TITLE
Scope All Open Projects doesn't work

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#188]
📝 Provide detailed reproduction steps (if any)
1. I have 2 open projects HSV and HSP, both are in a different location.
2. I select scope All Open Projects for searching.

✔️ Expected result
Results from both project should be displayed.

❌ Actual result
Files from one project are not found, they are searched in the path from the second project.

📷 Debugging Info
![1](https://github.com/VFPX/GoFish/assets/142881527/9c6948a2-0909-44c5-890b-f9d710eefadf)

Or does this option assume that both projects must be in the same folder?

**Comment by Jimrnelson** [comment]
This problem corrected in Version 7.0.17 - 2024-03-23
