### ISSUE TITLE
Strange search behavior regular expression in MNXs

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#190]
📝 Provide detailed reproduction steps (if any)

I'm searching regular expression ^\s*return in menus. Every result should be only Procedure match type. But it is written many times as match type <Clenup, Command, Keylabel, Keyname, Name, Resname, Setup, Skipfor>

Plain search "return" works normally.

📷 Screenshots
![1](https://github.com/VFPX/GoFish/assets/142881527/e4c72ba1-e892-43c2-91de-ddd5ca9f1693)

**Comment by Jimrnelson** [comment]
This problem corrected in Version 7.0.17 - 2024-03-23
