### ISSUE TITLE
Scope combo box error on closing list

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#192]
📝 Provide detailed reproduction steps (if any)

Open Scope combo box (projects, dirs...). Then click outside the list to close it. Not always, but sometimes error 2012 occurs. I'm not sure, but shouldn't .valid code be in .interactivechange?

📷 Screenshots

![1](https://github.com/VFPX/GoFish/assets/142881527/dc8ce8dc-0b93-4ec6-9168-e1b67dc48349)

![2](https://github.com/VFPX/GoFish/assets/142881527/e97c769a-7479-452e-81f1-b020ea812fa3)

**Comment by Jimrnelson** [comment]
Bug fixed in Version 7.0.18 - 2024-03-24
