### ISSUE TITLE
After install of GoFish 7.0.18

### ISSUE THREAD

**Issue by parios815** [VFPX/GoFish#195]
## ℹ windows 11 pro

- VFP version: 
- GoFish version: 7.0.18

## 📝 Started right after update

1. …
2. …
3. …

### ✔️ 
Expected result

missing parts of screen...

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshot
![image](https://github.com/VFPX/GoFish/assets/30445595/303452bb-420f-4469-b96f-555df88f2466)

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
That is intentional.

The "Advanced" page has been simplified to only include those settings not already present on the main form.

**Comment by parios815** [comment]
Thank you please consider issue closed… I could not find this on the website.
Sent from my iPhone, Please excuse my brevity.

On Mar 26, 2024, at 16:39, Jimrnelson ***@***.***> wrote:

﻿

That is intentional.

The "Advanced" page has been simplified to only include those settings not already present on the main form.

**Comment by Jimrnelson** [comment]
@parios815 

Pete --

All changes to GoFish are documented in its [Change Log](https://github.com/VFPX/GoFish/blob/master/docs/ChangeLog.md).

There are a number of places where the Change Log is visible:

At the bottom of Check For Updates:

![image](https://github.com/VFPX/GoFish/assets/81179335/54693539-8cea-4a60-8b17-ee55b7fad64c)

From the link that appears at the bottom left of the main GF form:

![image](https://github.com/VFPX/GoFish/assets/81179335/6d5cb2f7-90b0-40d3-b3a8-ff6b710c02b8)

From the home page for GF:

![image](https://github.com/VFPX/GoFish/assets/81179335/b49dc20c-ebda-484b-96ec-2ace25aa78be)
