### ISSUE TITLE
Codeplex is no longer a thing

### ISSUE THREAD

**Issue by rschummer** [VFPX/GoFish#2]
Nothing urgent or critical, but if anyone is already in the source looking into something else...

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish
2. Open Options dialog, click on Thor page
3. Note language: "You can lean more about Thor at the VFPX.CodePlex.com website."

### ✔️ Expected result

"at the VFPX.CodePlex.com" should be "on VFPX, found on GitHub.com"

### ❌ Actual result

The link following the instructions actually goes to the proper repository on GitHub, so that is set.

**Comment by PatrickvonDeetzen** [comment]
This got already changed in version 5.0.202. 

It now says:
"Visit the GoFish home page on VFPx"
