### ISSUE TITLE
In some cases, Code View shows only matching line and no context at all

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#202]
## ℹ Computer information

- VFP version: 9 build 7423
- GoFish version: 7.0.19

## 📝 Provide detailed reproduction steps (if any)

1. Search for "coluniq" in the VFP home folder
2. Click on GenXtab
3. Click on any of the match lines

### ✔️ Expected result

I'd see the matched line in context.

### ❌ Actual result

I see only the matched line

## 📷 Debugging Info

![image](https://github.com/VFPX/GoFish/assets/30271640/f78e9b32-d6ca-405a-8dea-a09b1aa99bec)

But I tried some other values as well.

## 📷 Screenshots

![image](https://github.com/VFPX/GoFish/assets/30271640/f2076ad0-0361-4f41-9a63-3c82221628eb)

**Comment by Jimrnelson** [comment]
Well, the good news (such as it is) is that is easily reproducible.

**Comment by Jimrnelson** [comment]
> FWIW, I think the source file needs to be large. I first tried to reproduce with a couple of small PRGs and couldn't.

That's correct, if the procedure is too large as well.

This bug fixed in Version 7.0.21 - 2024-04-02
