### ISSUE TITLE
Crash exiting GoFish 7.0

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#205]
## ℹ Computer information

- VFP version: VFP9
- GoFish version: Well - since it crashed with There is not enough memory to complete this operation, and there is no place on the screen giving the full version #, I can only say it's GoFish 7.0

## 📝 Provide detailed reproduction steps (if any)

1. … I did a simple search for "SetBO" on a small project.
2. … I then attempted to exit GoFish
3. … the GoFish Janitor wait window took very long.
4. ... Then it crashed 
![image](https://github.com/VFPX/GoFish/assets/5750619/c9d0757c-b71c-4703-8ea8-72ce53ed3911)

### ✔️ Expected result

_What is the expected result of the above steps?_

A clean shutdown. Unfortunately I already know you don't have the habit of remembering and resetting many settings. Further, I used to be willing to get into the code and help debug, but that ship has long since sailed.

### ❌ Actual result

_What is the actual result of the above steps?_

A crash.

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
The full version number appears in the bottom left corner of the GF screen, along with various links.

Yes, the janitor can be exceedingly slow at times.  This is due to some significant internal structural changes that were part of GF 6.  These included creating thousands of small files in a sub-folder of Home(7) and the janitor could take a long time to clear them out.

I have made considerable progress in re-working this, but I think I have reached the limit of what can be done without discarding all that was done with GF 6.

You can avoid the janitor altogether if you choose not to automatically save past searches.

**Comment by myearwood1** [comment]
If you would look at vfp2c32.fll he has a c++ routine to delete sets of
files.

Like I wrote about timing, if you drop vfp2c32.fll in your source folder
and a little prg I wrote, you can call his routine directly without
altering your procedure libraries.

**Comment by myearwood1** [comment]
I missed the links at the bottom left. Sorry. May I ask why not have the version number in the upper left where you already show GoFish 7.0? It's already used space and the rest of the title bar is unused.

**Comment by Jimrnelson** [comment]
> I missed the links at the bottom left. Sorry. May I ask why not have the version number in the upper left where you already show GoFish 7.0? It's already used space and the rest of the title bar is unused.

That was the convention from earlier versions of GF (5 and 6).  I did not modify that code.

**Comment by myearwood1** [comment]
Why do so many act like convention is sacred? It is logical to use that space, convention be damned.

**Comment by Jimrnelson** [comment]
> Why do so many act like convention is sacred? It is logical to use that space, convention be damned.

It's not.  There's plenty of other things that have captured my attention in GF over a long period of time.  This escaped my notice and, quite frankly, is not worth the effort to change.

**Comment by DougHennig** [comment]
@Jimrnelson There's a problem with using VFP2C32: many people use Carlos Alloatti's ctl32 library, which provides controls like date pickers, status bars, and so on, and Emerson Reed's ThemedControls, which uses the ctl32 library. ctl32 uses version 1 of VFP2C32 whereas the version available from GitHub is version 2, and sadly version 2 is not backwardly compatible with version 1, so anyone using ctl32 will crash if version 2 is installed.

**Comment by myearwood1** [comment]
If GoFish instantiates vfp2c3d.fll from the GoFish folder, it will not interfere with anything else. GoFish should detect if a different fll is loaded from a different path, switch to its own, and restore the previous one(s) when done. That is especially important with such utilities.

**Comment by Jimrnelson** [comment]
> May I ask why not have the version number in the upper left where you already show GoFish 7.0?

This has been addressed in Version 7.0.23 - 2024-04-06 (#212)

**Comment by Jimrnelson** [comment]
I think that this issue can be closed, as there is nothing further to be learned from it.

The topic of the ADir replacement with DIRX is still open in #142.
