### ISSUE TITLE
Add high resolution timing for GoFish performance monitoring.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#206]
## 📝 Provide a description of the new feature

Drew Speedie popularized the idea of running a tiny FoxPro program that instantiates an FLL or DLL or Windows API, so subsequent calls to this same name results in the FLL/DLL/API doing it instead of the .prg. This improves performance and maintainability, and recovers from accidentally removed DECLAREs.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Any time GoFish times how long it takes to execute, the FoxPro code involved can be bypassed and relegated to the Windows API.

As an example, 

`#define knIterations 1000000
LOCAL lcBuffer1, lcBuffer2
store space(8) to lcBuffer1, lcBuffer2

*Rev up the cpu
FOR X = 1 TO 1000000
ENDFOR X

WAIT WINDOW "Started!" nowait

b=0
=QueryPerformanceCounter(@m.lcBuffer1) && Click stop watch on
for x = 1 to knIterations
	CREATE CURSOR C_TEMP (cField1 c(10))
	use in (select('c_temp'))
endfor x
=QueryPerformanceCounter(@m.lcBuffer2) && Click stop watch off
b = m.b + (TicksToSeconds(@m.lcBuffer2) - TicksToSeconds(@m.lcBuffer1))
?"USE IN SELECT",TRANSFORM(m.b) + " secs"
`

You create four little programs in your source folder. For example QueryPerformanceCounter.prg contains this:
```
LPARAMETERS m.lpPerformanceCount
DECLARE INTEGER QueryPerformanceCounter IN kernel32 STRING @lpPerformanceCount
RETURN QueryPerformanceCounter(@m.lpPerformanceCount)
```
If the DECLARE INTEGER has not yet fired, or has been removed, calling QueryPerformanceCounter will re-declare it. This technique is better than DECLARE's all over the place. 

The other programs are QueryPerformanceFrequency.prg
LPARAMETERS m.lpFrequency
DECLARE INTEGER QueryPerformanceFrequency IN kernel32 STRING @lpFrequency
RETURN QueryPerformanceFrequency(@m.lpFrequency)

TicksToSeconds.prg
LPARAMETERS m.tcBuffer
*This is for converting an 8 byte buffer to a number of seconds
*using the highly accurate QueryPerformanceCounter and QueryPerformanceFrequency
*Windows API functions.
LOCAL lcFrequencyBuffer, lnFrequency
store space(8) to lcFrequencyBuffer
IF QueryPerformanceFrequency(@lcFrequencyBuffer) = 0
    ? "Error retrieving performance frequency."
    RETURN -1  && Indicate error
ENDIF
lnFrequency = DWordToDecimal(SUBSTR(m.lcFrequencyBuffer,1,4)) + DWordToDecimal(SUBSTR(m.lcFrequencyBuffer,5,4)) * 2^32
RETURN (DWordToDecimal(SUBSTR(m.tcBuffer,1,4)) + DWordToDecimal(SUBSTR(m.tcBuffer,5,4)) * 2^32) / m.lnFrequency

and DWordToDecimal.prg
LPARAMETERS m.tcBuffer
    RETURN ASC(SUBSTR(m.tcBuffer, 1,1)) + ;
        ASC(SUBSTR(m.tcBuffer, 2,1)) * 2^8 + ;
        ASC(SUBSTR(m.tcBuffer, 3,1)) * 2^16 + ;
        ASC(SUBSTR(m.tcBuffer, 4,1)) * 2^24

You can also do this with SLEEP.PRG
lparameters m.tnMilliseconds
declare Sleep in Win32API LONG
return sleep(m.tnMilliseconds)

You never have to write the declare ever again. Just code SLEEP() and it will load the DLL and defer to it.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
This suggestion does not apply to GF.

First of all, there are no DECLARE statements executed within the search engine, so there will be no improvement to be found there.

Secondly, the only speed measurement is to report to the user (at the top right of the form) how many seconds a search took (to only one decimal place).  This is done by calling Seconds() before and after, which is sufficient for the task.

**Comment by myearwood1** [comment]
There are many declares in GoFish. Each declare is a waste but for the first one, especially in loops. Gofish is not using only the latest best practices.

https://west-wind.com/wconnect/Weblog/ShowEntry.blog?id=949#_697365

There are 2 declares for shellexecute. I see a procedure called playsystemsound. It declares messagebeep each call. How often is that called? 
Procedure DiskFileName declares FindFirstFile, FindNextFile, FindClose. How often is DiskFileName called?
How often is procedure lockwindow called? It repeatedly declares GetDesktopWindow. 

method NewKey in gf_collection_explorer.scx and frmCollectionExplorer both declare CoCreateGuid. The programmer calling newkey has to decide to keep the declares? It is better to declare it once, knowing the next time you call CoCreateGuid it will use the API and not the FoxPro code.

According to Donald Knuth, only programmers are dumb enough to ignore a 12% increase. I don't know if we get any increase, but it's better to do things the right way. The idea of not improving code 97% of the time only applies to expert programmers who already wrote optimized code.

**Comment by myearwood1** [comment]
Best practice is to improve things where even a 12% improvement in any aspect is otherwise ignored by the majority of "developers"/"programmers". Best practice does not refer to just your practices.
