### ISSUE TITLE
How to search and replace all REPORT FORM commands to surround the report name with ". Intent is to support a recompile excluding reports.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#208]
## 📝 Provide a description of the new feature

Reports can be excluded from an exe and shipped separately. If the report form command includes the report name without it being wrapped in quotes, the project manager will add the reports. I want to search and replace all report form commands in the code base to wrap the report name itself in quotes. Then I will delete the report forms from a separate build pjx which should speed up building an exe.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Report form names in the code base will be excluded from automatic addition to the pjx. Programmers can still interact with them in the project manager/source control. However, we will be able to create a separate build pjx and remove them, supercharging the build exe speed.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
@myearwood1 

Mike --

You should be able to handle this with features that GF already provides, in particular the "Advanced Search" option.  (I believe that you referenced this in a previous issue, so I assume it's at least a little familiar).

You can go about this as follows:

1. Do a wild card search for "REPO*FORM"
2. Filter using the "Code only" checkbox.
3. Select Replace Mode.
4. Select "Advanced Replace"

When in "Advanced Replace" mode, you write a UDF (it'll prompt you) which takes a single line of code and the UDF returns the replacement.

If the "REPORT" = first word and "FORM" = second word and third word does not begin with a quote , then
    Replace the third word by wrapping it in quotes and return the modified line.
Else
    Return the original line.

That should do it.

BTW, I think this would make a fine second FAQ (#210)

**Comment by myearwood1** [comment]
As always, the Devil is in the details. The plan will be to find the report forms where the report file name has not already been wrapped in quotes, and apply it to those alone.

There is a snag too. A report file name may include spaces, and will already be wrapped in quotes. Such a report file name needs to be wrapped in a second pair of quotes.

**Comment by Jimrnelson** [comment]
Those details can be addressed in the UDF, so it's no concern of GF.

I have to say I've never seen file names wrapped in a second pair of quotes. Very interesting!

Nonetheless, I think that this issue can be taken care of entirely with features GF already provides and should be closed.

**Comment by myearwood1** [comment]
A report file with spaces would be wrapped in one pair. To suppress that report from being automatically included in the project, we'd have to wrap it with another pair. 

I agree. Thanks kindly for your input.

**Comment by myearwood1** [comment]
I will eventually ask you to add it to the FAQ. I think it would be a nice saving in compile time to create a separate pjx which would automatically not include reports and thereby skip them during compile.
