### ISSUE TITLE
New FAQ link on GF form

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#210]
## 📝 Provide a description of the new feature

@myearwood1, @DougHennig 

Mike's suggested the following as part of closing (#203)

> Please figure out how to add it to documentation.

The documentation for GF is woefully out-of-date and not likely to be updated (well, at least not by me).

I suggest that instead we had a _FAQ_ link at the bottom left of the GF form, where this would be the first entry, presumably with more to follow.

![image](https://github.com/VFPX/GoFish/assets/81179335/d3a49f1d-ea13-4e20-9881-0cdf49c53e26)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by DougHennig** [comment]
Sounds reasonable.

**Comment by Jimrnelson** [comment]
@DougHennig 

This is ready to be implemented once we have any questions!

**Comment by DougHennig** [comment]
What does it link to?

**Comment by Jimrnelson** [comment]
It links to a MD file in the GF GitHub folder.  The file is there, it's just a stub for now.  

It's not clear to me exactly what it should look like, am just waiting for some content (also known as documentation)

**Comment by Jimrnelson** [comment]
@DougHennig, @myearwood1, @klepetox

Hey guys --

I welcome any comments on my first take on the new [GF FAQ](https://github.com/VFPX/GoFish/blob/master/docs/FAQ.md) page.

My first concern is layout and such, because once this is public I will pretty much be stuck with it

Only secondarily do I care actual content (but I certainly do welcome comments on that as well.)

I expect to make that FAQ link visible with the next update.

**Comment by DougHennig** [comment]
Looks good to me.

**Comment by myearwood1** [comment]
Looks good. You typed treaded when you meant treated.

**Comment by Jimrnelson** [comment]
FAQ page for GF released.  

Am planning on keeping it current (assuming further questions arise)
