### ISSUE TITLE
Advanced Replace help

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#211]
## 📝 Provide a description of the new feature

@DougHennig 

One of the most powerful and also least used features of GF (and thus most in need of explanation) is the "Advanced Replace" option.

When selected, one gets this:

![image](https://github.com/VFPX/GoFish/assets/81179335/9e1ca2d4-054b-416a-84ae-36972b433409)

Clicking on the link does nothing.  The original link was this:

![image](https://github.com/VFPX/GoFish/assets/81179335/3e05a8eb-cd74-4a22-8744-c213b06f0e0c)

Am I correct in assuming there is no possibility of recovery?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
The UDF can reference:

`_screen._GoFish.oResultsForm.oSearchOptions`

**Comment by Jimrnelson** [comment]
I retract my earlier message.

For now, try this:

`_Screen._GoFish.oResultsForm.oSearchEngine.oRegExForSearch`

**Comment by DougHennig** [comment]
@Jimrnelson Actually, I have the old CodePlex files and found that page and associated images. I'll send them to you when I get back from my trip.

**Comment by Jimrnelson** [comment]
That would be great!

No hurry, of course, seems a lot brewing these days.

**Comment by DougHennig** [comment]
[gfdocs.zip](https://github.com/VFPX/GoFish/files/14951271/gfdocs.zip)
I uploaded all the GF docs I could find from CodePlex.

**Comment by Jimrnelson** [comment]
At first glance, nothing of value there.  I'll keep looking

**Comment by Jimrnelson** [comment]
I am closing this issue because I did not find anything.  It may well be that this was intended but not implemented.
