### ISSUE TITLE
Copy file name to clipboard - confirmation

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#214]
📝 Provide a description of the new feature

I copy full file name to clipboard from the result tree pane very often. Each time I have to confirm dialog box that is rather annoying. Is it possible to take this information into the WAIT WINDOW box with NOWAIT parameter?

-----------------------

![1](https://github.com/VFPX/GoFish/assets/142881527/240a8d46-e6ad-4095-a204-cedcda6ba7df)

------------------

![3](https://github.com/VFPX/GoFish/assets/142881527/2d31a9bb-bced-472c-a38a-9bd46813d5c0)

**Comment by Jimrnelson** [comment]
@myearwood1 
@klepetox 

I am curious about the use of this.  I must be missing something ... What do you do with this?

**Comment by klepetox** [comment]
I mean this:

`
Messagebox('File name (full path) copied to clipboard', 64, JustFname(m.tcFileName)) 
`

replace with:

`
WAIT WINDOW 'File name (full path) copied to clipboard' NOWAIT
`

in `gofishproc.prg`

**Comment by myearwood1** [comment]
In my case, I am in VFP6, so I have to get the file name from the treeview in GoFish in vfp9, and jump into vfp6 to modify it.

**Comment by klepetox** [comment]
In my case, I copy full name of .prg and then open it in external editor on the second monitor (open file - put it form clipboard). Then I modify .prg file and still see the original in external program.

Sometimes I need a view .scx table. I copy the filename and from command window I write USE <filename.scx - from clipboard> | BROWSE

and there's more...

**Comment by myearwood1** [comment]
@klepetox I could use it to open an .frx. Good idea.

**Comment by klepetox** [comment]
Sometimes a little thing can seem unnecessary. But for many users it can be very helpful. GoFish has a lot of features, it's really a very powerful tool and every feature has a user. I also want to thank Jim for his efforts here. I am most willing to contribute to testing, for which I have a very elaborate system built up over the years.

**Comment by myearwood1** [comment]
I am thankful to Jim too, although I cannot stop confusing his face with the Jim Nelson FoxPro guy I knew in Toronto.

**Comment by Jimrnelson** [comment]
> replace with:
> 
> `WAIT WINDOW 'File name (full path) copied to clipboard' NOWAIT`

Yes, that is what I was planning on.

**Comment by Jimrnelson** [comment]
@klepetox @myearwood1 

> Sometimes I need a view .scx table. I copy the filename and from command window I write USE <filename.scx - from clipboard> | BROWSE

I think that should be an option in the right-click menu.

**Comment by Jimrnelson** [comment]
> Sometimes a little thing can seem unnecessary. 

Far from thinking this was unnecessary, I was trying to learn from you how you guys took advantage of this feature so that I could do so as well.

**Comment by Jimrnelson** [comment]
@klepetox @myearwood1 

> I could use it to open an .frx. Good idea.

You can open a frx right now from the treeview by double-clicking it.

**Comment by Jimrnelson** [comment]
@klepetox, @myearwood1 :

This issue has been addressed in today's update: Version 7.0.25 - 2024-04-14 (#215)

Right-clicking on a node in the treeview gives this:

![image](https://github.com/VFPX/GoFish/assets/81179335/4fea2ea5-6a46-4b31-90f7-2e5e19f35ede)

Similarly, right-clicking on a row in the grid gives this:

![image](https://github.com/VFPX/GoFish/assets/81179335/706c64f3-271d-4a4f-89b3-874f05e81b4e)

**Comment by klepetox** [comment]
Great feature, but if I use it I get an error. After ignoring it, the table is opened correctly by the browse command.

![1](https://github.com/VFPX/GoFish/assets/142881527/951c8802-bf06-466b-80a7-e550f4440631)

**Comment by Jimrnelson** [comment]
LOL!

TAOMB (There's Always One More Bug).

And this one is a left over ancient one from Matt.
