### ISSUE TITLE
Why is RegEx so slow in GF?

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#216]
@DougHennig, @myearwood1, @klepetox

One of the obstacles to using RegEx in GF is that it is so sloooooooow.

In my testing, it has taken between 9 and 14 times longer to do a RegEx search than a wildcard search.

I have assumed all along that the issue had to do with RegExp being so much slower than using LIKE().  I no longer think so.

Having begun to look into it, I have found these comments (undated, from Matt, but from very early on in GF history).  They appear in the code that searches in tables (SCXs, VCXs, etc.)

```
*-- This is an important speed part of GoFish... If the user is not using a regular expression, then we
*-- can use the Locate command to make a quick look for a match anywhere in this column. We will handle the
*-- whole word part later on in the code, but a quick partial match hit helps us skips rows that have not
*-- match at all.
*-- If we find a match, we process it further and then call Continue to look for the next partial and repeat.
*-- This logic is not used if we are doing a Reg Ex search.

```
(I should note that this is actually the _most significant speedup_ that Matt provided, compared to Code References)

For binary files, GF loops through all character fields and finds records that match.  For plain and wild card searches, it can use Locate / Continue to process only the rows with matches.

However, for RegEx searches, it effectively does a Scan, performing RegEx one record at a time for each character field.

It would certainly seem that if we could find a way for RegEx to take advantage of Locate/Continue, that could be a huge savings.

My thought so far on this is that if there was some way for the user to supply something that worked as a wildcard pre-search, this could help a lot.

For instance, Mike supplied an example Regex like this:

    \b(REPORT|REPO)\s+FORM\s+(?!(?:'[^']'|"[^"]")\s*)[^'"\s]+(?:\s+[^'"\s]+)*\b

... which took so long he gave up.

I think this search could be improved dramatically if he could (somehow) do a pre-search looking for `REPO*FORM` to narrow the list of records.

I should make it clear that by 'pre-search' I mean that both the pre-search and the RegEx would be part of a single search routine.

Hope some / any of this makes sense.

**Comment by myearwood1** [comment]
Matt did well to use locate/continue.

**Comment by myearwood1** [comment]
I don't have regex docs in front of me. If there is a function that returns
the number of matches we could

Locate for regex.matches(field)>0

**Comment by Jimrnelson** [comment]
> I don't have regex docs in front of me. If there is a function that returns the number of matches we could
>
> Locate for regex.matches(field)>0

I will be looking into that and any other suggestions.

**Comment by Jimrnelson** [comment]
> Locate for regex.matches(field)>0

Easy to implement and fantastic results:

As currently released:

![image](https://github.com/VFPX/GoFish/assets/81179335/4daae24b-3b5d-45e6-bbd6-408fdfde0b28)

After implementing this suggestion

![image](https://github.com/VFPX/GoFish/assets/81179335/6d5815ea-bddc-483f-a2f1-bde7ca97f7f9)

That is 7 times faster! 

And the code changes were truly minor --

**Comment by Jimrnelson** [comment]
@DougHennig, @myearwood1, @klepetox

> I don't have regex docs in front of me. If there is a function that returns the number of matches we could
>
> Locate for regex.matches(field)>0

Easy to implement and fantastic results:

As currently released:

![image](https://github.com/VFPX/GoFish/assets/81179335/144b3abd-0d94-4c80-bc21-7bf84e15b027)

After implementing this suggestion

![image](https://github.com/VFPX/GoFish/assets/81179335/5b91bda0-6580-4ef2-b4de-80c5e226eefe)

That is 7 times faster!

And the code changes were truly minor --

**Comment by myearwood1** [comment]
You are welcome to my idea. Others in this community are undeserving of my input, because they hold optimizers in contempt.

**Comment by myearwood1** [comment]
Did you release a new set of changes?

**Comment by Jimrnelson** [comment]
@DougHennig, @myearwood1, @klepetox

> Did you release a new set of changes?

Not yet, although I expect to within a few days.  There are a few other small bugs being corrected at the same time.

I will let you all know when I do release another update.

**Comment by Jimrnelson** [comment]
@DougHennig, @myearwood1, @klepetox

This change in RegEx searching available in latest update Version 7.0.26B

**Comment by myearwood1** [comment]
Thanks for taking my advice on this without dismissing it out of hand like far too many do.

**Comment by Jimrnelson** [comment]
@myearwood1 

Mike, you're welcome.  I do not dismiss any suggestions out of hand.

**Comment by myearwood1** [comment]
Then you are rare in this community.

**Comment by myearwood1** [comment]
By the way, the discussion about using FindStr or better yet grep, means that even a regex will take 9 seconds.
