### ISSUE TITLE
Property OBJECTS is not found when launching find in a form

### ISSUE THREAD

**Issue by matthewaceware** [VFPX/GoFish#218]
## ℹ Computer information

- VFP version: 9.00.0000.5815
- GoFish version: 7.0.26

## 📝 Provide detailed reproduction steps (if any)

1. Search for something with results in a form and can be anything on the form (button, event, etc.).
2. Double-click to open the form object with the code I am looking for.
3. Get an error: "Property OBJECTS is not found". The form opens, but not the object.

### ✔️ Expected result

The object opens to the line of code I've searched for.

### ❌ Actual result

Error. Another side effect is that I can no longer open anything else from Go Fish as I have to close out of it and re-search to get it to fire.

## 📷 Debugging Info
Please add screenshots of
![image](https://github.com/VFPX/GoFish/assets/31904139/591b7437-3ece-4d2a-8df2-73798fd3b926)
- Windows from the debugger | Where do I go to get this information?
     - Trace window
     - Locals window
     - Call stack window

**Comment by Jimrnelson** [comment]
Can you tell me what `loObject.BaseClass` is?

Also, if you could send an image of your entire debugger, that would be helpful.  Those three windows are in the debugger.

**Comment by Jimrnelson** [comment]
And also `loParent.BaseClass`

**Comment by matthewaceware** [comment]
Absolutely. You just need to tell me how to find these things.

**Comment by Jimrnelson** [comment]
> Absolutely. You just need to tell me how to find these things.

Matthew --

Press Ctrl+F2.  This opens the command window.
Type DEBUG and enter.
Send a screenshot of the window that opens.

Separately, report the value of `loParent.BaseClass`.

**Comment by matthewaceware** [comment]
Not much here:
![image](https://github.com/VFPX/GoFish/assets/31904139/9d336cbd-a79e-4724-9194-3fcd320c8c6f)

**Comment by Jimrnelson** [comment]
Matthew --

OK, so you get the error "OBJECTS" not found.

Then you click "SUSPEND".

If that isn't what your did, please try that, and then send the debugger image.

**Comment by matthewaceware** [comment]
That got some more info:
![image](https://github.com/VFPX/GoFish/assets/31904139/9f0fc22f-2db1-4385-a753-a6df84e21da9)

**Comment by matthewaceware** [comment]
I might be jumping the gun, but thought you might be interested to see this:
![image](https://github.com/VFPX/GoFish/assets/31904139/5eb219b5-25d9-493a-be21-99aae51e53fa)

**Comment by klepetox** [comment]
@matthewaceware, @Jimrnelson 

> I just got another error message as well: ![image](https://private-user-images.githubusercontent.com/31904139/323006570-7ae64dfe-3abf-4d50-b609-83aad29eb23b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMjc4ODIsIm5iZiI6MTcxMzMyNzU4MiwicGF0aCI6Ii8zMTkwNDEzOS8zMjMwMDY1NzAtN2FlNjRkZmUtM2FiZi00ZDUwLWI2MDktODNhYWQyOWViMjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA0MTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDA3NzRkNDdkNGU4YzY4NGJmM2IxMmM1YWFhY2I4YmI1NTE3ZGY3ODkzZGE4ZGQ4OWFkODgxZjczOGVlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pKB_VkC2GqFNGZ4ooB1C7Kfeniummy61QnHed_n17Nw)

This is the same error I report in another topic and I can replicate it anytime.
[#194](https://github.com/VFPX/GoFish/issues/194#issuecomment-2059341775)

**Comment by matthewaceware** [comment]
Better with the new update. Now I'm getting this when opening a vcx or form:
![image](https://github.com/VFPX/GoFish/assets/31904139/6901f0dd-aadd-4063-a81a-21d844c0c777)
There isn't an option to suspend here, so not sure how I can help you today.

**Comment by Jimrnelson** [comment]
@matthewaceware 

Now THAT's a new one.  Looks like SYS(2015) or something.  

Tell me more about the circumstances.  Does this happen

- All of the time?  
- Some of the time?  
- Both forms and classes?  
- Do you have PEMEditor open?
- Is this only for objects in the form or class? (but not methods in the form or class)

What happens after you click OK?

**Comment by matthewaceware** [comment]
- Yes, all of the time so far.
- Yes, forms and classes. Does not happen with prgs. Hadn't tried mnx files, so just tried that. No error.
- No, I do not have PEM Editor open. I just have the Command Window and the Properties Window. Just tried with the PEM Editor open and got a similar error (the string is different each time).
- Methods in a form or class don't throw the error, just objects. I'd been playing with a lot of objects lately, so hadn't noticed that in this morning's runs.

After I click OK, I am in the proper place I am wanting to be. I can then make my changes and close out of this. Most importantly, I can open other search results and do what I need to do. So, this pop-up is more of an annoyance than anything else.

Thanks,
Matthew

**Comment by matthewaceware** [comment]
Oh, and Go Fish seems slower today than yesterday. Not sure if that is related. Sometimes the Go Fish Janitor hangs there for a long time (minutes even) before it finally closes.

**Comment by Jimrnelson** [comment]
> Oh, and Go Fish seems slower today than yesterday. Not sure if that is related. Sometimes the Go Fish Janitor hangs there for a long time (minutes even) before it finally closes.

That would make sense if you had debugger open.

I am not seeing any degradation on my end.  Of course, Janitor only runs once a day, but I cannot imagine it taking minutes.

**Comment by Jimrnelson** [comment]
@matthewaceware 

> * Yes, forms and classes. Does not happen with prgs. Hadn't tried mnx files, so just tried that. No error.

Grasping at straws here --- any chance that these forms (or classes that are forms) have blank captions?

**Comment by matthewaceware** [comment]
> @matthewaceware
> 
> > * Yes, forms and classes. Does not happen with prgs. Hadn't tried mnx files, so just tried that. No error.
> 
> Grasping at straws here --- any chance that these forms (or classes that are forms) have blank captions?

Nope. I tried three and all have a Caption to them. Even the vcx did.

**Comment by Jimrnelson** [comment]
@matthewaceware 

Matthew --

Is this issue pretty much done?  It seems like there are a number of topics here that have been addressed.

If there are any remaining, please start a new issue.

Thanks
