### ISSUE TITLE
mDot in search edit box

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#22]
## 📝 Provide detailed reproduction steps (if any)

1. Run GoFish
2. Run IntellisenseX by mDot
3. enter m.

### ✔️ Expected result

m.

### ❌ Actual result

m is deleted

Looks like we need to turn this of while in Editbox. Possibly IntellisenseX must learn not to work in editboxes, I think about what is best here.

**Comment by Jimrnelson** [comment]
This is really a problem with IntellisenseX, nor GoFish, and should be reported there.

However, the reproduction steps do not indicate where m. is entered.  (The reference to editbox  doesn't indicate where the editbox is encountered.) 

I think a screenshot would be helpful.

**Comment by lscheffler** [comment]
@Jimrnelson You are right. I just keep it open to do a better issue, and I still have problems to grok where to set issues with IntellisenseX.
