### ISSUE TITLE
Right click on tree view does not always work.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#224]
## ℹ Computer information

- VFP version: VFP9
- GoFish version: 7.0.26b

## 📝 Provide detailed reproduction steps (if any)

1. … Do a search
2. … access a file in the tree view
3. … right click on said file - no context menu appears

### ✔️ Expected result

As featured, a context menu should appear

### ❌ Actual result

Nothing happens at all.

## 📷 Debugging Info
No error happens. It is intermittent.

**Comment by Jimrnelson** [comment]
@myearwood1 

Yes, I can duplicate this and yet I doubt that I can correct it.

The problem has to do with whether the GF form as focus.  If it doesn't, then neither clicking nor right-clicking on nodes has any effect.

Thus, if you focus on something else than GF and click or double-click on a node, nothing happens.

Furthermore, if you right-click on a node, regardless of what option you execute or if you press Escape, GF no longer has the focus .  (I don't have any idea where it goes to.)  The second right-click works.

I am fairly certain there's nothing to be done on this one.

**Comment by myearwood1** [comment]
I restarted GoFish, did a search and got the error property cThorDispatcher is not found. It's in gofishproc in a procedure called GF_GetHackCX. Does that help?

**Comment by klepetox** [comment]
How about try it this way?

```
	*_Screen.Show()

	Define Popup (m.lcMenuName)			;
		shortcut						;
		Relative						;
		From m.loPosition.Row, m.loPosition.Column IN SCREEN

```

**Comment by Jimrnelson** [comment]
@klepetox, @myearwood1

Good catch indeed!  And what a simple fix!

That will be in the next update (later in the day today, Tuesday)

**Comment by Jimrnelson** [comment]
> I restarted GoFish, did a search and got the error property cThorDispatcher is not found. It's in gofishproc in a procedure called GF_GetHackCX. Does that help?

This too will be fixed in the next update (later in the day today, Tuesday)

This one is a little embarrassing, as I should have known better.

Next time there's a bug, it would be helpful to send a screenshot of the error and any relevant debugger windows.  In this case, I don't understand why the error occurred as part of the search.  No matter, easy to fix.

**Comment by myearwood1** [comment]
I know we all make mistakes. I'm always trying to do only "best" practices to save myself grief and get more speed. Many others don't have a clue there are better practices.

**Comment by Jimrnelson** [comment]
The two errors reports in this issue have been taken care of in Version 7.0.29 - 2024-04-23 (#225)
