### ISSUE TITLE
Gofish 5 upgrade?

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#239]
## ℹ Computer information

- VFP version: VFP 9
- GoFish version: 7.1.02

## 📝 Provide detailed reproduction steps (if any)

1. … User (my supervisor who's been waiting to try it!) is running GoFish 5 - left it running and...
2. … Attempted to start GoFish7.app from VFP9 IDE.
3. … He saw something about converting. No available screenshot.
4. ... GoFish5 continues to work.

### ✔️ Expected result

_What is the expected result of the above steps?_

Co-existence of GoFish 5 and 7. 

### ❌ Actual result

_What is the actual result of the above steps?_

GoFish7 starts, but fails to find all results. GoFish7 on my PC with the same files finds all results.

## 📷 Debugging Info

I built the app from the source. I uploaded the app and the grep folder to sourcesafe. We got the latest version of the files to c:\gofish7.
Since he kept GoFish5 loaded, maybe the conversion routine I was shown blew up?

## 📷 Screenshots

Sorry - no screen shots.

**Comment by Jimrnelson** [comment]
@myearwood1 

How was GF7 installed?  

- If installed by Thor, all should be well, as they get installed in different folders.
- If not installed by Thor and in the same folder (on top of each other), I cannot imagine that they would work.

I can tell you that GF7 and earlier versions of GF are not compatible in the same session, as earlier versions leave stuff around (Set Procs, e.g.,) that was attempted to fix in GF7.

I have both GF5 Classic and GF7 alive on my computer, and switch between them but not in the same session.  (I use GF5 Classic to search thru GF7 code).  Thus, I am sure you should be able to have both of them available.

The conversion message merely looked like this:

![image](https://github.com/VFPX/GoFish/assets/81179335/2da3bade-5a79-4c2b-a9b1-04c9e4659cb8)

What surprises me most is this statement: _GoFish7 starts, but fails to find all results._  Is this true not only on his computer fut also on yours?

**Comment by myearwood1** [comment]
Hi @Jimrnelson 

I built the gofish app and named it gofish7.app I put this file in c:\gofish7 along with the grep folder. I have GoFish5 in c:\gofish5. Ideally they should work in a single GoFish folder, but that's not important to me. They are definitely not running in the same vfp 9 session, although, with vfp9 installed, the Tools Options would apply to both.

If you build it as an exe, you can add a config.fpw and control the various environmental settings.

**Comment by myearwood1** [comment]
My PC search everything properly. I suspect my supervisor kept GoFish5 running while starting GoFish7, so the conversion may not have worked.

**Comment by Jimrnelson** [comment]
Hi @myearwood1 

Mike -- 

Can you be more specific about what is going wrong?  You have separate folders for GF5 and GF7 and you run each in search VFP sessions.  That works for me but is not working for you.

But I do not yet understand what you are seeing.  GF7 is running, it seems, ... but what?  (The more details the better, of course)

**Comment by Jimrnelson** [comment]
@myearwood1 

Mike, anything more on this?  

If not (if it's been resolved), I'd like to close this issue.

**Comment by myearwood1** [comment]
It has not been resolved. Is there a way to remove whatever files GoFish is trying to update?

**Comment by Jimrnelson** [comment]
Darn --

All that should be happening is that a new folder is created in Home(7) named `GoFish_`.  (Note the trailing underline).

You should be able to delete that and then GF 7 does not think it is installed.

GF5 and GF7 should be independent, so I am quite interested to learn more about what is not working.

**Comment by myearwood1** [comment]
When I first tried to upgrade to GoFish6 my setup was ruined. I never tried to upgrade from 5 to any other version while 5 was still running. I don't have time to determine what the cause is, I would like to go forward from here.

**Comment by Jimrnelson** [comment]
@myearwood1 

Yeah, the GoFish 6 upgrade was miserable for a lot of us.  You should not have any problems, however, bypassing GF 6 altogether and going straight to GF7.

I suggest these steps:

1. Make a copy of Home (7).  I do not believe that this is necessary but it ensures you can go back to the previous state, as all settings for all versions of GF are saved in Home(7).

2. Unzip the source files (I assume you are not using Thor).

3. Open VFP and without running the old GF, run the newly installed GF7.  

4. You should be able to observe in Home(7) that there is a new folder `GoFish_'.

That should be all you need.  If this fails for any reason, please let me know what you experience (and put that folder created in step 1 back so you were back where you started.)

This is what I have done and the others who never got GF6 to work.  There have been no other reports of problems. although that's not a guarantee of anything.

Good luck.

It would be very disappointing for me as well if this does not work easily.

**Comment by myearwood1** [comment]
No point
