### ISSUE TITLE
Right-Click in results tree view please add juststem filename.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#240]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

We have a few ways to get the file name from the tree view. This is a small addition. The benefit is if I found the .prg, and now I want to find where it is called, most calls do not include the .prg. Yes I can remove it, but it would save me a little time, to select the juststem of the file name from the tree via the right-click menu.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
One of your simpler requests, I will include this in the next release.

Am surprised I guess you didn't ask for another option to search for the file immediately.

**Comment by myearwood1** [comment]
:) What? You only want simple requests? Don't I wish that's all I ever got!

You should not make suggestions if you don't want more work. I didn't think of that! I like it. That would help me climb the hierarchy from the place that crashed, to the form it contains, to the program that called the form, to the menu that called the program, much more quickly.

**Comment by Jimrnelson** [comment]
Implemented in Version 7.1.03 - 2024-06-06

- Two new selections in the right-click context menu for nodes in TreeView
    - Export stem name to clipboard (#240)
    - GoFish for references to the file or class name
