### ISSUE TITLE
Strange thing (not error) in "Path relative to Scope" column when searching in All open projects

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#247]
I have option Show relative path i column "File Name with Path" checked on (very good feature) and search in all open projects. I open two projects, one of them is in the current directory `\hsp\`. When I search, results and everything is correct, but that column shows incorrect relative path.

See screenshot, **current dir and project is `"hsp"`**. Its relative path is incorrect `"..\hsp\"`. The other project is `"hsv"` in `"..\hsv\"` dir - its relative path is incorrect too. No `"..\"` but `"!project\forms\prehldbf.scx"` instead of `"..\hsv\!project\forms\prehldbf.scx"`.

It is not an error, only relative path is not displayed correctly, searching and replacing works well.

![1](https://github.com/VFPX/GoFish/assets/142881527/4657883d-1567-45a4-a8e7-cab5176ddf3e)

**Comment by Jimrnelson** [comment]
@klepetox 

I am not entirely surprised by this one as the "File Name with Path" feature was implemented before "All Open Projects" and was not revisited thereafter.

The behavior I am seeing when I try this feature is that it shows the relative path to the current project.  It seems that you were expecting it to be relative to the current path, correct?

I had not thought about this before, but with multiple projects open, maybe the current path is the only possibility that makes sense.

**Comment by klepetox** [comment]
> It seems that you were expecting it to be relative to the current path, correct?

Yes, it is what I expected. When I have open more projects, which of them is the current one? I suppose that is the one in current dir? But what if none of them is in the current dir? The relative path should be taken from current dir in this case I think.

**Comment by Jimrnelson** [comment]
> Another good way to solve this issue may be to display the full path instead of the relative path when searching in multiple projects. I don't know which is better.

Nah, I disagree.  This is a user selection and I can't assume I can override.

**Comment by klepetox** [comment]
Yes, of course you're right. But relative path in searching in more projects? If not full path only in this case, then relative to the current directory.

When I see relative path now, I can't determine in which directories it is. I see `!project\forms\prehldbf.scx` but it is really in `..\hsv\!project\forms\prehldbf.scx`, which is confusing and I can miss this. Then I rather search in each project separately.

**Comment by Jimrnelson** [comment]
>  If not full path only in this case, then relative to the current directory.

Yes, only relative to current directory makes sense.  And that will be a new option in the grid context menu to make it easier to switch.

**Comment by klepetox** [comment]
OK good global option, and would it be possible to set this option as default when searching across multiple projects without having to choose it in the context menu?

**Comment by Jimrnelson** [comment]
> OK good global option, and would it be possible to set this option as default when searching across multiple projects without having to choose it in the context menu?

You're asking for a new option that only applies when searching multiple projects?  That seems like overkill.

**Comment by klepetox** [comment]
If it is overkill, then leave it as it is. But the relative paths are not correct in this case. But this problem is not really so important.

**Comment by Jimrnelson** [comment]
> But this problem is not really so important.

Well, it was important enough to bring up.

And also applicable to me, so I assume to others as well.

**Comment by Jimrnelson** [comment]
@klepetox 

This will be addressed in the next release (likely this weekend).

**Comment by klepetox** [comment]
Excellent as always, looking forward to…

**Comment by Jimrnelson** [comment]
Fixed in Version 7.1.07 - 2024-06-13

**Comment by klepetox** [comment]
There's an error when I choose "Show relative path..." from grid context menu.

And also this: "Copy full filename (with path) to clipboard" copies file stem only.

![1](https://github.com/VFPX/GoFish/assets/142881527/7f438534-edec-4903-a104-1a42871a355b)

![5](https://github.com/VFPX/GoFish/assets/142881527/73f38e31-1b66-4e2f-9de7-6bef340add75)

**Comment by Jimrnelson** [comment]
@klepetox 

Let's see if I got it right this time.  Version 7.1.08, just released.

**Comment by klepetox** [comment]
Yes, everything seems to be correct now.
