### ISSUE TITLE
'GF_Filter_Form_Settings.xml' does not exist

### ISSUE THREAD

**Issue by PaulBbecker** [VFPX/GoFish#25]
## 📝 Provide detailed reproduction steps (if any)

1. Load GF
2. Go to Options->Advanced and click on the "Delete config files!" button 
3. Click OK
4. Run a search that will produce some results
5. Click on the "Filter" button

### ✔️ Expected result

The filter dialog should appear

### ❌ Actual result

Error message appears saying
'c:\users\myUserName\appdata\roaming\microsoft\visual foxpro 9\GF_Filter_Form_Settings.xml' does not exist.

Screenshots

![image](https://user-images.githubusercontent.com/44329778/197280755-08565be6-0654-4444-8c68-5d1c52fbd84e.png)

![GoFish 5 1 001 Issue 2022-10-21_12-47-26](https://user-images.githubusercontent.com/44329778/197280009-61225db9-046a-41ac-8afd-224f3a086b21.jpg)

https://user-images.githubusercontent.com/44329778/197279796-b31bc4e9-e693-4ba3-85c8-076c4b300ce0.mp4

**Comment by lscheffler** [comment]
@PaulBbecker Could you please give the version number of GoFish. Also please check for latest version, it should be fixed since 5.1.001.

**Comment by PaulBbecker** [comment]
Hi Lutz,

It is 5.1.001. I show the version in the video. Go to time stamp 00:30 in the video and you’ll see it.

Paul

 

Paul Becker

H 707 546-7712 

***@***.***

**Comment by lscheffler** [comment]
Then I must have fixed it doing something else.    
I check if I can do a fix outside the dev.
