### ISSUE TITLE
Add numeric positions for Prompt display for menu item

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#250]
## 📝 Provide a description of the new feature

After doing a search through a .mnx, GoFish shows this prompt - aka the Original Prompt

Prompt    = "\<Order Entry 1 (mx) => Order \<Tracking Menu => \<Order Progress Inquiry"

I would like a change to the Original prompt to make it - aka the Enhanced Prompt:

Prompt    = " **(1)** \<Order Entry 1 (mx) => **(36)** Order \<Tracking Menu => `(2)` \<Order Progress Inquiry"

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Our menu structure is so vast that we sometimes get an unexplained Too Many Windows error when we add a single item. When we look at the above Original Prompt, it still takes time to find the correct entry. If we had the number of the entry, we could just hit the down arrow until we reach the number of the entry in the Menu Designer.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
@myearwood1 

I thought that this was addressed in an earlier issue.

The resolution was to double-click on the item in the grid (like you do for lines in a PRG, SVX, or VCX) and it should automatically use the keyboard buffer to do what you are asking for.

I have verified that this works in my environment but have never had any other feedback.

Does this not work for you?

(I'm not avoiding your request, just wondering about this first.)

**Comment by myearwood1** [comment]
That cannot work for us here. We have to keep the application in vfp6, but run GoFish in 9. We try not to open things in 9 in case they get converted. If only GoFish was not all OOP when it didn't have to be, and was at least backward compatible to 6, I'd be able to use it the way it was intended.

**Comment by Jimrnelson** [comment]
> That cannot work for us here. 

I will look into your suggestion, which would have to be provided as an option.  Clearly, that display would make sense to you, but maybe not to everybody else.  (I would find it confusing.)

> If only GoFish was not all OOP when it didn't have to be, and was at least backward compatible to 6

Ah, a little late for that.

**Comment by Jimrnelson** [comment]
Addressed in Version 7.1.09 - 2024-06-15

![image](https://github.com/VFPX/GoFish/assets/81179335/b8876095-5884-4254-8096-65f3e8e28972)

**Comment by klepetox** [comment]
Is it possible to do this as selectable with possibility not to write "Procedure" section?

`Iif(Empty(Procedure) , '', 'Procedure : ' + Iif(CR $ Trim(Procedure, 1, CR, LF, Tab, ' '), CRLF, '') + Procedure + CRLF)`  in `gofishsearchengine.prg`

See #184

And only marginally (not so important) - the bar numbers a useless for me.  I prefer `Prompt` in this simple format (one row):

`Prompt : Table Maintenance -> Payroll -> Absences Table` 

This maybe usefull for somebody but annoying for others.

**Comment by Jimrnelson** [comment]
@klepetox 

> Is it possible to do this as selectable with possibility not to write "Procedure" section?

Oops! Sorry about that ... corrected in Version 7.1.10 - 2024-06-16

**Comment by klepetox** [comment]
It is OK as before, thank you Jim for quick and positive reaction.

**Comment by myearwood1** [comment]
I could have made the change I requested if I was permitted to participate.

**Comment by Jimrnelson** [comment]
@klepetox 

> It is OK as before, thank you Jim for quick and positive reaction.

You're welcome.

**Comment by myearwood1** [comment]
Why do you block capable contributors?

**Comment by myearwood1** [comment]
I see the numbers in the prompt. If there is supposed to be a switch to control it, I don't see the switch and mine is on, which is what I think @klepetox was saying. Does the gofish.app shipped in the download not have that?

**Comment by Jimrnelson** [comment]
I decided to go without the option.

@klepetox indicated is was of marginal importance to him to exclude the bar numbers.

I thought the new display should be satisfactory for all, guessing that if was the original format there would not have been complaints.

**Comment by klepetox** [comment]
Přece jen ještě drobnosti:

- Mohla by být sekce odvozená pole na začátku místo na konci?
- Je možné z názvů vypustit "\<"?
- Strukturu přece jen vypsat na jeden řádek jako: (1) Bar aaa -> (4) Bar bbb - > (7) Bar ccc (když už tam ta otravná čísla musí být)?

**Comment by klepetox** [comment]
Just a few things:

- Could the section "Related fields" be at the beginning instead of at the end? It is excellent for quick orientation.
- Is it possible to omit the "\\<" from the names?
- After all, the prompt structure could be written out on 1 line as: (1) Bar aaa -> (4) Bar bbb - > (7) Bar ccc (ideally without numbers)
- The Message field should be without quotes, it is an expression, not a string (quotes marks are then doubled, it can be some variable as `gcBarMessage`, string is in the Comment section)
- Maybe to omit the quotes marks from everywhere (?)

![1](https://github.com/VFPX/GoFish/assets/142881527/98eb8d62-bb03-4514-a6d8-07b350a1f4e9)

**Comment by Jimrnelson** [comment]
@klepetox 

Hey, thanks for the comments!   I always welcome all feedback.

> Could the section "Related fields" be at the beginning instead of at the end? It is excellent for quick orientation.

My offhand response is that it took so wiggling to get the display to work even in its current format.  But I will certainly check.

> * Is it possible to omit the "\<" from the names?

Very good point

> * After all, the prompt structure could be written out on 1 line as: (1) Bar aaa -> (4) Bar bbb - > (7) Bar ccc (ideally without numbers)

Rats, it looks like the number thing is too annoying to not have an option.

> * The Message field should be without quotes, it is an expression, not a string (quotes marks are then doubled, it can be some variable as `gcBarMessage`, string is in the Comment section)

Ah, I had never used it.

>  * Maybe to omit the quotes marks from everywhere (?)

That pane is called the "Code View" pane, so it's supposed to look like code (the coloring used can be the same as in your IDE, if you so choose).  My intent was that fields that are clearly character should be in quotes.

**Comment by klepetox** [comment]
OK, I understand that not everything is easy to implement. From me, these are just suggestions to think about, it is not necessary to implement everything.

**Comment by Jimrnelson** [comment]
@klepetox 

Of course!  But this entire project has grown over the years from users' suggestions.  Not all are implemented, but sometimes they open up whole new ideas.

Which is why I also interpret users' comments as suggestions, not directions.

**Comment by Jimrnelson** [comment]
@klepetox 

> * Could the section "Related fields" be at the beginning instead of at the end? It is excellent for quick orientation.

I agree that this would be of great help, but I could not find a way to do it.

**Comment by myearwood1** [comment]
I do not see how the numbers being there or not impacts anyone. If you only have menus with a small amount of items, you don't need the numbers. I need to know where the menu item is in the designer, 1 because we have so many menus with so many items and 2 so we don't edit the wrong menu or go down the wrong path. I was fine with a single line for the prompt.

**Comment by klepetox** [comment]
@myearwood1 I prefer my apps to be user friendly. Today the trend is not to use menus (MS Office...), unfortunately I don't like it, but it's true. My menus are very simple, users prefer shortcuts on the toolbar or shortcuts on the desktop of the program.

**Comment by myearwood1** [comment]
@klepetox. I agree with that. I'm dealing with a legacy application that grew like weeds into a monstrosity. Sometimes we add a menu and run it in the IDE, but when we build an exe and deploy, it runs on the dev machine, but when the user runs it, VFP 6 says Too many windows and dies without firing the errorhandler. My personal choice for menus is to call up the form that does that task. One invoice form does everything related to invoices, creating, editing, searching.

**Comment by klepetox** [comment]
@myearwood1 I understand you, there's a difference developing your own app or taking it as is. And by the way, I appreciate your input with the grep utility.

**Comment by myearwood1** [comment]
Thanks @klepetox. You've shown yourself to be a reasonable person. I have given a lot to this community over many years, but several individuals regularly attacked me until I had enough of it.

**Comment by Jimrnelson** [comment]
@myearwood1 
@klepetox 

See Version 7.1.11 - 2024-06-18

- New option to display the bar number in Code View pane for matches in MNXs (#250)
- 

![image](https://github.com/VFPX/GoFish/assets/81179335/11b75b29-d6ea-4897-9733-d91c9c150941)

**Comment by klepetox** [comment]
Wow, you actually did everything I asked. Great job and thanks again.

**Comment by Jimrnelson** [comment]
We (that is, I) aim to please.
