### ISSUE TITLE
Results form and font size

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#259]
## 📝 Provide a description of the new feature

In the `GF_Results_Form_Settings.xml` file there is an entry `nSearchBoxFontSize` that affects the font size in two comboboxes (blue arrow). Would it be possible to apply the font size to other comboboxes as well (red arrow)? On 4k monitors the font is too small.

![1](https://github.com/VFPX/GoFish/assets/142881527/ae52f46a-7332-40d5-ac3c-f1e02d092d22)

**Comment by Jimrnelson** [comment]
@klepetox 

Implemented in Version 7.1.12 - 2024-06-29.

What I found interesting about this was that you found a reference to a setting for font size in the XML file that was referenced in code but never presented to the user in the Options file.  That has been corrected:

![image](https://github.com/VFPX/GoFish/assets/81179335/0f572c04-65a0-4e72-8aac-144cd32d0d0a)

**Comment by klepetox** [comment]
Great work again! Please extend these comboboxes slightly, I need font size 12 px on 144 ppi (150 % ~ 8*1.5)

![2](https://github.com/VFPX/GoFish/assets/142881527/0f990e9a-c05b-4d62-8529-e07ab0ca06a2)

![1](https://github.com/VFPX/GoFish/assets/142881527/d982ec60-0a69-4acc-bfcc-4639c5e341b3)

**Comment by Jimrnelson** [comment]
@klepetox 

I have taken this suggestion one step further, in that you can now set the default font size for all objects on the main GF results form.  (They all grow proportionately.)

![image](https://github.com/user-attachments/assets/f9ab1636-a1a2-4133-ab87-57738f1e7b96)

For my own use, I have found that a value of 10 makes the form much easier to work with.

**Comment by klepetox** [comment]
Well, this is great. For monitors with higher resolution and higher DPI, this is a great option. I have my own resizer and every properties .fontsize, .top, .left, .height, .width... I calculate this way:

`.<properties_size>*Sysmetric(16)/32*100`

**Comment by Jimrnelson** [comment]
@klepetox 

The algorithm for GF used here also takes care of the necessary adjustments to `.Anchor`

**Comment by klepetox** [comment]
A really big improvement for my 4K monitor, thanks again. GoFish is making great strides in both functionality and user interface.

**Comment by Jimrnelson** [comment]
@klepetox 

Thank you!
