### ISSUE TITLE
Searching for single-character currency symbol returns zero matches when matches should be found

### ISSUE THREAD

**Issue by PGibsonCoUk** [VFPX/GoFish#261]
## ℹ Computer information

- VFP version: 9 (7423)
- GoFish version: 7.1.11

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish 7 (see above version number for specifics)
2. Perform a Plain Search for single character currency symbol, in this case the currency symbol for GBP (£) - without the brackets, just the single character
3. Search completes but informs No matches found.  There are definitely occurrences of that character in the source code, the search should return results.
4. Doesn't matter what the scope is, I've tried Directory and Project.  I've tried wildcard and RegEx searches and not found a way of getting results.
5. If I perform the same search in older versions of GoFish (i.e. 6.2.002) then this style of search does return expected results.
6. If I change the search to "£" (so, the symbol inside quotes) and repeat I do get results, proving that the search without the quotes should also return results.

### ✔️ Expected result

greater than zero search results

### ❌ Actual result

**_No matches found_** prompt

## 📷 Screenshots

Example of the search parameters
![image](https://github.com/VFPX/GoFish/assets/174201085/a8f316ef-3f4f-41a9-9685-78b1836f3645)

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

Fixed in Version 7.1.13 - 2024-06-29
