### ISSUE TITLE
Code View, when using IDE colours, respects foreground colour but not background colour

### ISSUE THREAD

**Issue by PGibsonCoUk** [VFPX/GoFish#262]
## ℹ Computer information

- VFP version: 9 (7423)
- GoFish version: 7.1.11

## 📝 Provide detailed reproduction steps (if any)

1. Use an IDE colour scheme inline with a Dark Mode (i.e. dark background with foreground colours appropriate to the dark background)
2. Use GoFish with the new _Use IDE colours_ option enabled.
3. Perform any search to get some results
4. Click on any result which will display code in the code view.
5. Note, code view shows the code respecting the foreground colours but on a light background.  The combination of which might be unreadable and require the disabling of the new option.  Shame.

### ✔️ Expected result

![image](https://github.com/VFPX/GoFish/assets/174201085/f4481804-c6d7-4296-91d6-e6209a1d1e43)

### ❌ Actual result

![image](https://github.com/VFPX/GoFish/assets/174201085/20b79f6f-e2c6-48d5-90bb-d2d22b175761)

## 📷 Screenshots

![image](https://github.com/VFPX/GoFish/assets/174201085/c9de4b9b-9d0d-4a18-8e8d-aa2fbd943ed0)

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

Unfortunately, the Code View pane is not able to completely replicate what you see in your IDE.  There are simply some combinations, including dark mode, which were beyond what could be provided for,

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 
@billand88 

I've taken a stab with getting GF to handle Dark Mode, although I can't text it very well myself.

If you have a chance, could you try the attached (renaming extension to APP) and let me know how well it does?

Note that GF doesn't know how to recognize Dark Mode programmatically, so you need to go the the Options page to turn it on --- and, it might not take effect until you close/re-oepn GF.

Thanks.


[GoFish.txt](https://github.com/user-attachments/files/17318497/GoFish.txt)
