### ISSUE TITLE
Searches ending in backslash (\) return zero matches, when matches should be found

### ISSUE THREAD

**Issue by PGibsonCoUk** [VFPX/GoFish#264]
## ℹ Computer information

- VFP version:  9 (7423)
- GoFish version: 7.1.13

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish 7, enter search expression that ends with a backslash, like a path, such as c:\ 
2. Perform a "Plain search" with scope "Browse Directory", Whole Word is NOT ticked, Subdirectories IS ticked
3. Search says No matches found
4. Change expression to remove the backslash i.e. c: and repeat the same search
5. Search returns many results which show that the c:\ search should have returned results.
6. Tried double-slash just in case ending with a slash needs escaping, same thing, no matches found.
7. Tried search c:\ in GoFish version 6.2.002 and that does return expected results.  Perhaps another side effect of the Grep integration?

### ✔️ Expected result

Greater than zero search results

### ❌ Actual result

Prompt: No matches found

## 📷 Screenshots

Example of search for c:\ returning zero matches:
![image](https://github.com/VFPX/GoFish/assets/174201085/824e33de-0f18-4db1-be8c-d0e0468983e4)

Example of search for c: returning many matches:
![image](https://github.com/VFPX/GoFish/assets/174201085/0a063f06-0df8-415f-9eb0-6b349acc156d)

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

First of all, I want to thank you for the very detailed explanation of the steps to reproduce the problem.  I believe this is the best I have ever seen; it certainly makes it a lot easier for me when I have such complete information.

And, you even diagnosed the issue:

>  Perhaps another side effect of the Grep integration?

Yes, that's exactly it!  It seems that grep (at least the version used by GF) does not always work when there is a trailing backslash.  Oddly, it does work some of the time -- `:\` for instance.

In any case I hope to have a fix for this out soon.

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

Fixed in Version 7.1.14 - 2024-07-08

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

Thanks so much for the kind words.

It's my belief that devs are somehow transformed into users when reporting issues in VFPX (here or other projects), so they frequently neglect to provide all the information that they themselves would want to receive.

Finally, I am pleasantly surprised to see that you are already taking advantage of the latest little tweaks, adding the Delete Mark and Set Deleted options.  It's nice to know that somebody out there reads the release notes and incorporates them into their usage of GF.
