### ISSUE TITLE
Small improvements for the future

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#268]
## 📝 Provide a description of the new feature

GoFish has made incredible progress since version 6. I hope that I have contributed a little bit with my suggestions and bug reports.

I have one more suggestion for the next improvement, maybe now or in the next version of GoFish8.

I would like to have a user button (maybe 2 or 3) in the results form where I could plug my own code, which would be executed using Execscript. The code would be saved in the settings. Any errors would be ignored.
As an example - set everything to default like this (I would write the program code according to the GoFish source code.):

Scope - Project in current dir
Mode - Plain search
Whole words - off
Match case - off
... and so on

**Comment by myearwood1** [comment]
An ability to save settings to a collection/library would be really good @klepetox

**Comment by Jimrnelson** [comment]
@klepetox 

> GoFish has made incredible progress since version 6. 

Thank you very much!  It is nice to have my work noticed and appreciated.

> I hope that I have contributed a little bit with my suggestions and bug reports.

Yes, you have been very helpful indeed as one of the most frequent posters of late.

**Comment by Jimrnelson** [comment]
@klepetox 

This has been implemented in Version 7.1.16 - 2024-07-16

- Added new "Custom UDF" for modifying any of the search options in GF (#268).
    - The file name is entered on the Options form, "New in V7" page.
    - The UDF is called by either right-clicking or ctrl-clicking on the "Advanced" button.
    - See `Lib\gofishsearchoptions.prg`

The UDF is called directly, not within ExecScript and not within Try/Catch.  

If you want to have different varieties of saved settings, it'll be up to you to manage within the UDF.
