### ISSUE TITLE
Interesting behaviour searching for negative numbers

### ISSUE THREAD

**Issue by PGibsonCoUk** [VFPX/GoFish#272]
## ℹ Computer information

- VFP version: 9 (7423)
- GoFish version: 7.1.16

## 📝 Provide detailed reproduction steps (if any)

1. Launch GoFish 7, enter search expression for a negative number (e.g. `-99`) 
2. Perform a `Plain search`, with a `Directory` scope search for a negative number, Whole Word is NOT ticked, Subdirectories IS ticked
3. Search says No Matches Found
4. Change search expression to remove the minus sign, e.g. change it to `99` and repeat the same search
5. Search returns results that show the previous search (`-99`) should have returned results.
6. Interestingly a `Whole word` search for 99 does return results for -99 (presumably because of _word delimiters_) so that's a workaround of sorts, I can then just disregard the results for the positive number.
7. I could change the search expression to `-*99` and change the mode to `Wildcards` and I will get results showing `-99` but obviously there might be lots of other results that I'm not interested in so this workaround may also return additional results.
8. Perhaps another side effect of the Grep integration WRT how the minus symbol is handled so it might not be restricted to negative numbers and is perhaps to do with any search expression beginning with the minus symbol, just more obvious with negative numbers.

### ✔️ Expected result

Greater than zero search results

### ❌ Actual result

Prompt: No matches found

## 📷 Screenshots

Example of search for `-99`, NOT whole word, returning zero results
![image](https://github.com/user-attachments/assets/776b450d-fd9d-4f70-a605-a9bc03497e9e)

Example of _Whole word_ search for `99` returning results that demonstrate `-99` should have returned results
![image](https://github.com/user-attachments/assets/dbb9a2ee-df28-403e-b777-0d46d0815f4d)

Example of _Wildcard_ search for `-*99` returning results that demonstrate `-99` should have returned results
![image](https://github.com/user-attachments/assets/3bb3b0d2-1ebe-4e5e-8378-c1e4b704b7dc)

**Comment by Jimrnelson** [comment]
@PGibsonCoUk 

Fixed in Version 7.1.17 - 2024-07-18.

Searches expressions beginning with `-` will no longer use grep.

Thanks for bringing this to my attention
