### ISSUE TITLE
GoFish is freezing after the grep, while searching the found files.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#276]
## 📝 Provide a description of the new feature

After the grep process, does gofish scan the detected files in another way? If so, could you have the thermometer box show the filename of each file as it starts scanning? Mine is freezing (correction, took a long time to scan some file) part way through the final scan and I cannot tell why.

I had run gendbcx which produced a very large .prg file. I forgot until I saw it in the results list.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Showing the filenames while scanning can help a developer restore a damaged copy of the file.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Mike, 

There’s already an option for this on the Options form.  



Sent from my iPhone

**Comment by myearwood1** [comment]
Ok. That's cool. Thanks. It does not slow down the search much, if at all. :) It's surprising that grep roared through the large file without a hitch. If you wouldn't mind, having the filename in the thermometer box to the right of Searching might seem a little more polished than the wait window? I'm hopeful to see if you can use the -- to fix grep searching. No hurry.

**Comment by Jimrnelson** [comment]
@myearwood1 

> If you wouldn't mind, having the filename in the thermometer box 

That was a very good idea and implemented in todays release.  Not only that, but it is MUCH faster than Wait Window, with an almost negligible effect on performance.

Thanks again.

**Comment by Jimrnelson** [comment]
@myearwood1 

> I'm hopeful to see if you can use the -- to fix grep searching.

This was part of today's release as well.

**Comment by myearwood1** [comment]
Am I starting to get you to look for performance more often? ;) Drawing a box around some text should take longer than just writing some text. Putting a piece of text at a single location on the foxpro desktop is faster than ?"text" when it causes the window to scroll. Thanks very much for making those changes.

**Comment by myearwood1** [comment]
> @myearwood1
> 
> > If you wouldn't mind, having the filename in the thermometer box
> 
> That was a very good idea and implemented in todays release. Not only that, but it is MUCH faster than Wait Window, with an almost negligible effect on performance.
> 
> Thanks again.
https://github.com/VFPX/GoFish/issues/77#issuecomment-2256659605
