### ISSUE TITLE
Variable 'LCPROJECTPATH' is not found

### ISSUE THREAD

**Issue by salvatoregraf** [VFPX/GoFish#280]
## ℹ Computer information

- VFP version: 9.0 SP2
- GoFish version: 7.1.18

## 📝 Provide detailed reproduction steps (if any)

1. Open a project
2. Set GoFish to search in the active project
3. Search something

### ❌ Actual result
![screen1](https://github.com/user-attachments/assets/a5c02142-7cfc-4739-b040-d48ebcea900b)

## 📷 Debugging Info

**To avoid the error I added the code highlighted in the attached screenshot**

![screen3](https://github.com/user-attachments/assets/bdfcbb8c-02e0-4aa9-964c-6d599c2bc1d2)

**Comment by Jimrnelson** [comment]
@salvatoregraf 

Thanks for the notification and the code fix!

Fixed in Version 7.1.19 - 2024-08-08
