### ISSUE TITLE
Duplicate hot keys in grid right click menu

### ISSUE THREAD

**Issue by billand88** [VFPX/GoFish#282]
![image001](https://github.com/user-attachments/assets/9a18c55c-06be-4c4e-96c0-a703ad45a489)
## ℹ Computer information

- VFP version: 
- GoFish version: 7.1.19

## 📝 Provide detailed reproduction steps (if any)

1. Get some data in the grid
2. Right click on a cell.
3. …

### ✔️ Expected result

Not duplicated hot keys.
More of the menu bars having unique hot keys. There's a ton of text, there should be key uniqueness. I'll find it if you want, just ask.

### ❌ Actual result

Only six of 'em have hot keys and three of them are S. That's not gonna work....

## 📷 Debugging Info
The attached screen shot should show it.

I'm gonna add an enhancement here because I'm too lazy to duplicate everything for the enhancement request. It involves this grid right click menu. I believe this would be quite useful, actually. Highlight some text in the grid, right click. You get the attached menu as expected. If I wish to copy the highlighted text, I need to go to the Edit menu to get to the Copy menu bar. What I would like to see - if text is highlighted in the grid - is an extension to this right click menu. Add a separator and a Copy menu bar. It would be much more convenient to have an additional option here.

## 📷 Screenshots

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by billand88** [comment]
Well, just taking the first letters and capital letters I can get all of them but the last one.

The first letter constitutes the first menu bar and goes down from there.

F/V/T/C/M/S/N/P/B/A/D/E

If the additional Copy is implemented, I'd give that menu bar the "C" and give the 4th one an "R".

**Comment by Jimrnelson** [comment]
That is a context menu, and not all items appear all the time.

There are, in fact, 17 distinct possibilities.

So, I cannot even tell which items you are suggesting without seeing the display ... and then I'll have to find which are not accounted for.

**Comment by billand88** [comment]
>> _So, I cannot even tell which items you are suggesting without seeing the display_<< 

I just went off of the supplied screen shot. I didn't know it wasn't the full set of menu bars.

**Comment by Jimrnelson** [comment]
Here's the whole list,in the order they would appear

Filter by this \<File
Filter by this \<Class
Filter by this \<Method
\<Open Backup Replace Folder
Filter values in this column (remove previous filter)
Filter values in this column (modify previous filter)
Show relative path in column "File Name with Path"
\<Stem to clipboard
File \<Name to clipboard
Full file name (with \<Path) to clipboard
\<Browse as table
Super Browse as table
\<HackCX
DeleteMark
Set Deleted
Copy highlighted \<Text to clipboard
\<GoFish for highlighted text

Please modify as you see fit

**Comment by billand88** [comment]
Are any of the menu bars mutually exclusive with another menu bar on this list? If so, we could double up on the hot keys.

**Comment by Jimrnelson** [comment]
@billand88 

Good question!

No, unfortunately, none of them are mutually exclusive.

**Comment by billand88** [comment]
Well, I will go down different rabbit holes here but it's noted I have work to do on the hot keys.

If one of the menu bars is "Copy highlighted..." how come I'm not seeing it when I highlight text in the grid and right click? If that is supposed to work and it doesn't, that's a bug **and** it would address my original issue.

This is more of a consistency issue but "Stem to clipboard" IMO should read "File Name Stem to Clipboard". I think the others in this grouping should have the N in Name capitalized but I can also make a case for Filename. All I'm after is consistency, and don't really have a preference here.

**Comment by Jimrnelson** [comment]
> If one of the menu bars is "Copy highlighted..." how come I'm not seeing it when I highlight text in the grid and right click? If that is supposed to work and it doesn't, that's a bug and it would address my original issue.

The two "highlighted text" items at the end of the list, while not yet implemented, were included in anticipation of completing your suggestion in this thread.

**Comment by billand88** [comment]
I'll use your naming convention...

Filter by this <File
Filter by this <Class
Filter by this <Method
<Open Backup Replace Folder
Filter values in this column (<remove previous filter)
Filter <values in this column (modify previous filter)
Show relative path in column "File Name <with Path"
<Stem to clipboard
File <Name to clipboard
Full file name (with <Path) to clipboard
<Browse as table
Super Browse <as table
<HackCX
DeleteMar<k
Set <Deleted
Copy highlighted <Text to clipboard
<GoFish for highlighted text

I could probably get all the hot keys to be first letters or capital letters but some of the current keys would change - not worth the trouble...

**Comment by Jimrnelson** [comment]
Thanks, I will be incorporating this into the next release.

**Comment by Jimrnelson** [comment]
Implemented in Fixed in Version 7.1.20 - 2024-08-21
