### ISSUE TITLE
More hot key cleanup...

### ISSUE THREAD

**Issue by billand88** [VFPX/GoFish#288]
Just cuz I can...and actually it does help keyboard around.

Right click in one of the the Grid Headers. Oh, let's give 'em H/S/B or C/R for shortcut keys.

Currently there are hot keys for Comments and Match Case. I'd seriously consider switching them. Give the "M" to Match Case and the "C" to Comments.

Mode can take the "D".

Scope could use a hot key. An underlined "P" is hard to notice, you may have to give that one an "E".

Limit to Home can take the "L".

Down below, Code View Position can take the "V".

That's not all of the controls, but let's see how this shakes out after implementation.

**Comment by Jimrnelson** [comment]
Where are you seeing this?  

None of the items you mention appear in the grid headers context menu (unless this is just one of those days ...)

Maybe a screen shot would help.

**Comment by billand88** [comment]
I wish I could capture it. The Snippet Editor won't save it without removing the context menu.

Right click on the File Name / Containing Class / Match Line or any of the grid's other headers and you should see the context menu.

**Comment by Jimrnelson** [comment]
@billand88 

Bill --

Something weird going on-

In the current version (7.1.21, from 08/23/2024), the context menu when right-clicking on a grid header looks like this:

![image](https://github.com/user-attachments/assets/b7cb7ada-b4f3-4152-90ea-bff96c877592)

Furthermore, I can't find any evidence that those items you refer to have appeared in the grid header context menu for a long time (possibly ever).   They did, however, appear at one time in the context menu on the Advanced button (but no longer)

I am not sure how to proceed with this.

**Comment by Jimrnelson** [comment]
Also, I think that **Windows + Print Screen keys** will capture the entire screen with the context menu.

**Comment by billand88** [comment]
![RightClickHeader](https://github.com/user-attachments/assets/972207c6-c9d7-4935-894b-f899bfda288b)

I have something close to what you see. 

The image is relevant to this comment: >>_Right click in one of the the Grid Headers. Oh, let's give 'em H/S/B or C/R for shortcut keys._<< -- except "H" should be "F". My bad, it should read - Oh, let's give 'em F/S/B or C/R for shortcut keys -

**Comment by Jimrnelson** [comment]
@billand88 

> Right click in one of the the Grid Headers. Oh, let's give 'em H/S/B or C/R for shortcut keys.

This will be implemented in the next update to GF.

**Comment by billand88** [comment]
Well, I'll quote from the original message...

--

Currently there are hot keys for Comments and Match Case. I'd seriously consider switching them. Give the "M" to Match Case and the "C" to Comments.

Mode can take the "D".

Scope could use a hot key. An underlined "P" is hard to notice, you may have to give that one an "E".

Limit to Home can take the "L".

Down below, Code View Position can take the "V".

**Comment by Jimrnelson** [comment]
@billand88 

> Currently there are hot keys for Comments and Match Case. I'd seriously consider switching them. Give the "M" to Match Case and the "C" to Comments.

I have considered this and decided not to.  I am not going confuse those users already accustomed to these access keys (unchanged for a dozen years).

**Comment by Jimrnelson** [comment]
@billand88 

> Mode can take the "D".
> 
> Scope could use a hot key. An underlined "P" is hard to notice, you may have to give that one an "E".
>
> Down below, Code View Position can take the "V".

All three of these controls are comboboxes.  I could not get the access key to work for any of them.  I note that F1 help describes access keys for text boxes and edit boxes, without any mention of comboboxes. 

![image](https://github.com/user-attachments/assets/4df70bfe-17d6-496e-80d7-5a206c263de1)

Is there some trick to this I should be aware off?

**Comment by Jimrnelson** [comment]
@billand88 

> Limit to Home can take the "L".

This will take effect with the next release.

**Comment by klepetox** [comment]
[@Jimrnelson]
> > Mode can take the "D".
> > Scope could use a hot key. An underlined "P" is hard to notice, you may have to give that one an "E".
> > Down below, Code View Position can take the "V".
> 
> All three of these controls are comboboxes. I could not get the access key to work for any of them. I note that F1 help describes access keys for text boxes and edit boxes, without any mention of comboboxes.
> 
> **Is there some trick to this I should be aware off?**

You can access any object with any label by shortcut key. See this picture and form as example.

![2](https://github.com/user-attachments/assets/de606ddc-dca3-45ca-a10d-027ec83ee5a9)

[form.zip](https://github.com/user-attachments/files/16801159/form.zip)

**Comment by Jimrnelson** [comment]
@klepetox 
@billand88 

> Mode can take the "D".
> 
> Scope could use a hot key. An underlined "P" is hard to notice, you may have to give that one an "E".
>
> Down below, Code View Position can take the "V".

"Next object that can have focus" turned out to be incomplete, but led me in the right direction.

What was missing was "and has `.Tabstop = .T.`"

Having corrected that for these three items, these changes will take effect in the next release as well.

**Comment by Jimrnelson** [comment]
Implemented tin Version 7.1.22- 2024-08-31
