### ISSUE TITLE
User preference settings ignored and overwritten

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/GoFish#29]
## ℹ Computer information

- VFP version: 9.00.0000.7423
- GoFish version: 5.1.002
- Last GoFish version w/o bug (if available): 5.0.207 for the grid, earlier for the form size/position

## 📝 Provide detailed reproduction steps (if any)

1. Open the GoFish app
2. Move and resize the GoFish window
3. Do a search if there are no search results yet
4. Move and resize columns
5. Click on Options
6. Select a column to add to the results grid - I selected the _Class_ column
7. Click OK to save the changes

### ✔️ Expected result

1. GoFish window opens to the same size and position
2. Column widths remain as set
3. Column positions remain as set
4. Added column selected would be shown in the results grid

### ❌ Actual result

1. GoFish window always opens to a default size and position
2. Column widths are reset to a default size
3. Moved columns are moved back to a default position
4. For some columns, the added column flashes briefly in the results grid and disappears. Other columns will display when first selected, but do not appear the next time the app is opened.

The screen capture below shows the broken grid behaviors

## 📷 Screenshots

![2022-10-28_13-36-14](https://user-images.githubusercontent.com/9847353/198699874-d0435546-cbc2-426f-a47a-44d44f4f31ec.gif)

**Comment by lscheffler** [comment]
I see the following:
- Size and position of the main form are restored
- column order is restored (Moved columns)
- column width is not restored
- added coluns do not work at all, they even do not appear.
 
@mikepotjer  The behaviour is a bit different here. Could you please test
- do you see the column added?
- if you reopen *Options*, is the column active?
- could you possible zip the GF* files in `HOME(7)`  and send it to me, so that I can check what is different? Mine is minced after all the changes ...

**Comment by lscheffler** [comment]
@mikepotjer would you please chech the Form position and size and notify me about the result? Thanks

**Comment by mikepotjer** [comment]
I installed the new version - 5.1.003
The results grid and column options are behaving correctly now. Thank You!
The form size and position is NOT using the saved settings. I have the Dockable setting set to 1, but it doesn't seem to make any difference what that is set to.
![image](https://user-images.githubusercontent.com/9847353/199020089-f2f90fa0-7e93-4a5a-9dac-8ee31b91656e.png)

If I resize or move the GoFish window, the GF_Results_Form_Settings.xml file in my HOME(7) folder is updated (see the highlighted values in the screenshot below), but when I reopen GoFish, these settings are not used.
![image](https://user-images.githubusercontent.com/9847353/199018403-c4a204ed-af3a-4164-9163-faf4d6bd198e.png)

When I open GoFish the next time, the settings below are what the form is using. These settings were written to GF_Results_Form_Settings.xml when I opened the form and did NOT resize or move it.
![image](https://user-images.githubusercontent.com/9847353/199018991-06bb6749-3c65-42e3-9192-5b8c2d0cf514.png)

If you still want to see them, here are the settings files from my HOME(7) folder.
[GoFish Settings.zip](https://github.com/VFPX/GoFish/files/9901596/GoFish.Settings.zip)

**Comment by lscheffler** [comment]
Thank you. I will have a look to the file. Maybe something is interfering.

**Comment by lscheffler** [comment]
It is dockable. Dockable looks coordinate - wise a bit like desktop - device dependent, at least on my comp. This is your 
FormLeft 3877 above. Then it compares left+width with _screen.width, and if to large keeps original size. Need to look whats wrong.

**Comment by lscheffler** [comment]
I've tested this with  with 5.0.206 as of 2022-09-23. The behaviour is the same.    
Do you have monitor position changed? This happens when VFP is on a secondary, right screen.

Would you mind to test against the old version?
I'm not to warm with github, so possibly 
- clone this repo and checkout SHA1 **726d4aa4471df64366c** named  _Fixed: The View Replace History button wasn't working because of a renamed file._
- or if you understand how to pick directly from this commit, feel free to download `source\gofish5.app`
- run `source\gofish5.app` against the zip from above
- change pos etc

**Comment by lscheffler** [comment]
@mikepotjer update. If you have use ObjectExplorer at hand, you can watch the .LEFT of the form yourself. It stuck where it is because the code runs like
```
.dockable = 0 && from property sheet
.left = 0 && from property sheet
.dockable = 1 &&restore settings
*now internaly .left is changing to something that belongs to the monitors combined
...
If This.Desktop Or .FormLeft + .FormWidth <= _Screen.Width
*we dont reach this line
	This.Left	= .FormLeft
	This.Height	= .FormHeight
	This.Width	= .FormWidth
	Thisform.Resize()
Endif This.Desktop ...

```
.top is (why ever, as if I could not mix up height ...) restored on a different line without test.

**Comment by mikepotjer** [comment]
I did not check for updates for a long time, so I was probably using version 5.0.202 (or earlier) when I updated to 5.1.xxx. I was using dockable and the same window/monitor layout prior to updating and the size and position were restoring to the last settings I used each time. I have a laptop screen and 2 external monitors.
When I get a chance, I can try rolling back to an older version to figure out where it stopped working.

**Comment by lscheffler** [comment]
Or just try to run VFP on the main monitor. This should work.   

I can fix this so far. Only now the next question comes up. On a variable setting like a laptop on dock, the stuff could be restored complete out of sight of any screen. This is true for desktop as well. Guess there was something on West-Wind ...

**Comment by mikepotjer** [comment]
Thanks @lscheffler ! This is behaving as expected now.
