### ISSUE TITLE
Alternate way to specify extensions

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#290]
## 📝 Provide a description of the new fe

Easier than making every combination of upper and lower case extensions.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

I just learned how to handle extensions.

[Pp][Rr][Gg]
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
@myearwood1 

MIke --

Funny we missed that -- I am gonna claim I knew that once.

Looks like it works as expected, should be part of the next update.  And also be invisible.

**Comment by Jimrnelson** [comment]
@myearwood1 

Implemented in Version 7.1.23- 2024-09-06
