### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by lemmeboga** [VFPX/GoFish#291]
## ℹ Core i5 3.0 Mhz 20GB, SSD 500 GB

- VFP version: 9 SP2
- GoFish version: 7.0.31

## 📝I'm getting the same error in each search :
It is the same set of characters that precedes and follows the searched keyword. If I search for "SearchedKeyword" I will get the following error:  Error processing regular expression. ^.*\bSearchedKeyword\b.*$
1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 
![GF_Error](https://github.com/user-attachments/assets/54adf325-f310-4e95-9537-d8bc6b3683e8)
📷 Screenshots

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lemmeboga** [comment]
The keyword searched in the attached image is "idreg". I do get the result I expected but that error windows always shows up

**Comment by Jimrnelson** [comment]
@lemmeboga 

That's an error message I had not encountered before.  It certainly does not reveal much about the problem.

I suggest you install today's update (Version 7.1.23- 2024-09-06), in which the error report provides more information that may be helpful in learning what is going wrong.

If I got it right, it should include the name of the file being searched when the error occurs.  Please attach that file (by dragging it into your response).  If it's a binary file ('SCX' or 'VCX'), please include its other half ('SCT' or 'VCT')

Hopefully I will be able to reproduce the problem once I have in hand that file.

**Comment by lemmeboga** [comment]
@Jimrnelson 
Thanks a lot, I will proceed as you suggest

**Comment by lemmeboga** [comment]
@Jimrnelson 
After installing the new version I don't get the error anymore.
Thanks for your support

**Comment by Jimrnelson** [comment]
@lemmeboga 

Glad this was so easily resolved.  

Closing this issue.
