### ISSUE TITLE
Search for SELECT * doesn't work

### ISSUE THREAD

**Issue by DougHennig** [VFPX/GoFish#294]
## ℹ Computer information

- VFP version: VFPA (not relevant)
- GoFish version: 7.1.24

## 📝 Provide detailed reproduction steps (if any)

Search for SELECT * (to find, for example, SELECT * FROM SomeTable)

### ✔️ Expected result

Only SELECT * statements are found.

### ❌ Actual result

All SELECT statements are found.

I realize this is because * is a wild-card character. Perhaps if there's no text following the *, it could be used as a literal value.

**Comment by Jimrnelson** [comment]
Was this a plain search or wildcard?

If plain, it's a problem.  If wildcard, isn't it doing what you asked for?  (or are you asking for it to be different if wildcard?)

**Comment by DougHennig** [comment]
You're right: I had wildcard selected. If I select Plain Text and turn off Whole Word, it works as expected. Thanks.

**Comment by Jimrnelson** [comment]
Doug --

I wonder why it forces you to turn off "Whole Word".  

Wouldn't it be nice(r) to recognize the whole words in your search phrase?

**Comment by DougHennig** [comment]
Yes, but I'm fine with it the way it is (at least for this search).
