### ISSUE TITLE
String too long to fit error

### ISSUE THREAD

**Issue by billand88** [VFPX/GoFish#295]
## ℹ Computer information

- VFP version: 9 SP2, 3 hot fixes
- GoFish version: 7.1.2.4
## 📝 Provide detailed reproduction steps (if any)

This is happening a lot for me under this scenario...

1. Pull up a project, search by Active Project (I think this may be irrelevant at this point, but now the good stutt) 
2. Scroll down to an entry in the Class Column.
3. Highlight and triple left click (Item appears). Keep focus within the same cell
4. Close item.
5. Now right triple click in the same grid cell.

### ✔️ Expected result

Probably not much of anything.

### ❌ Actual result

Kaboom.

Looks like it's tied to `lcPrompt11`, whose length at this point is 288.

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots
![Screenshot 2024-09-18 045008](https://github.com/user-attachments/assets/fc7695ee-e5d6-46e8-b6b5-b1fa147de8bd)

**Comment by Jimrnelson** [comment]
Fixed in Version 7.1.25- 2024-09-18
