### ISSUE TITLE
GoFish appears to affect VFP's property display

### ISSUE THREAD

**Issue by billand88** [VFPX/GoFish#300]
- VFP version: 9.0, SP2, 3 hot fixes
- GoFish version: 7.1.28

This is a bizarre bug and requires some setup. I'll set this up the way I'm coming across it.

1. Download ChilkatVFP and place in a directory. Note the directory name.
2. Run the Class Browser and load Chilkat.VCX from the same install directory.
3. Run GoFish, set it to Browse Directory. Select the same folder ChilkatVFP is in.
4. Search for a phrase. It doesn't matter, but for the sake of argument, search "PKCS7". You'll get some hits in the Chilkat.VCX file. 
5. Open one of the entries in Chilkat.VCX by double clicking in the grid. Note the class name.
6. Pull up the Property Sheet.
7. Right click on one of the Property Sheet tabs and turn off Non Default Properties Only.
8. Search for chilkatchangelog in the property sheet. It's not there.
9. Close the Class.
10. Bring up the Class Browser and open up the same class.
11. Search for chilkatchangelog in the property sheet. It's there.

**Comment by Jimrnelson** [comment]
Bill --

I could not  reproduce this problem.  

The class I tried was 'email' and the method did in fact appear in the Property Sheet in step 8.

**Comment by billand88** [comment]
>> _I could not reproduce this problem._ << I'm not surprised - but don't misinterpret terseness as sarcasm, this one is weird.

It might be related to the fact that both the CB and GoFish were working on the same file at the same time, I don't know. But I recreated it about 30 times.

Park it for now, when time permits I'll try to make a video of it and link to it at some point...

**Comment by Jimrnelson** [comment]
Bill --

I have tried this again, without having GF involved:

[1]  I opened the class with Modify Class email of chilkat.vcx.  The property sheet shows the method:

![image](https://github.com/user-attachments/assets/eef137bc-5f99-4bd8-a68b-7153deb597e2)

[2]  I then opened the class browser for email of chilkat.vcx and it did NOT appear:

![image](https://github.com/user-attachments/assets/ec31104d-9293-4820-b276-63c3f2fc9832)

I don't know what's going on here, why the property sheet and class browser do not agree, but it does not seem to be an issue with GF.

**Comment by billand88** [comment]
>>  _I don't know what's going on here, why the property sheet and class browser do not agree,_ << 

No, that's how the class browser operates. If you'll note, the property sheet color for ChilkatChangeLog is purple, indicating inheritance. The properties in the right side of the Class Browser were defined in the EMail class. ChilkatChangeLog is defined in the BaseChilkat class.

**Comment by Jimrnelson** [comment]
Bill --

Not surprised to display my ignorance of the class browser, as I never use it.

As to this issue, I have not been able to find a class where that method did not show up in the Property Sheet.

Beyond that, I can't in my wildest imagination think that anything that GF does would affect the Property Sheet.  But that might just demonstrate the limits of my imagination.

**Comment by billand88** [comment]
![1-OperatingOnSameFileAndDirectory](https://github.com/user-attachments/assets/d9055dc3-2090-4e6e-8ddb-d41b60f1d4fc)
![2-ClassBrowserCrypt2](https://github.com/user-attachments/assets/5409849d-7230-429e-8efb-419b7c86658a)
![3-DoubleClickInGrid](https://github.com/user-attachments/assets/bc2851bf-4fe8-4036-a55a-1c818f1ac392)
![4-ChangeChilkatLogPropertyNotThere](https://github.com/user-attachments/assets/944dfca9-2e53-4794-82ee-ba14f86aa100)

These are screen shots of a one minute video (that's simply too big to upload). So to recap, I have the Class Browser holding the VCX in question while the latest GoFish is browsing the same directory, doing code searches and finding hits within the same VCX that the Class Browser is displaying. This may or may not be relevant, just setting the scene.

So I open Crypt2 via the CB and show the ChilkatChangeLog method. Only non-default properties are displayed and there's clearly text in the method. So far, so good.

Close the class, then I click on GoFish and double click in the grid on one of the Crypt2 "hits" in the VCX. Doesn't matter what cell in the grid, nor does the method/property matter. 

Set the property sheet to show all methods by unclicking the Non Default Properties Only option and the ChilkatChangeLog method is nowhere to be found.

One thing I'll add is that the memberdata or whatever the heck it is, is not used. This isn't a case of the method being proper-cased and showing up elsewhere in the property sheet. I don't use memeberdata. And I checked anyway.

**Comment by Jimrnelson** [comment]
Bill --

Did you intend to mark this as closed?

**Comment by Jimrnelson** [comment]
Bill --

Looking at your first image, I see that GF shows lots of duplicate class names in the treeview on the left, most of them twice for the same vcx name.

However, when I run GF on the installed Chilkat (via Thor), I only see one name.

![image](https://github.com/user-attachments/assets/dc493e38-6b9a-4835-8aab-a30d9445ebb8)

Thus, I wonder if you might two have distinct versions of chilkat.vcx in your folder which might explain part of this enigma.

**Comment by billand88** [comment]
>> Thus, I wonder if you might two have distinct versions of chilkat.vcx in your folder which might explain part of this enigma.<< 

Close enough to say you nailed it. I have "check subdirectories" checked. Unchecking it - Hey, there it is!

**Comment by billand88** [comment]
User error for this one.

**Comment by Jimrnelson** [comment]
> User error for this one.

Well, what you were seeing really did not make any sense at all, and it was only because of your detailed explanations and screenshots that we got to the bottom of it.
