### ISSUE TITLE
New in 7.1.24: Context menus now sensitive to default font size

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#301]
I think this modification is counterproductive, Windows sets the font size in the menus itself and correctly. Even for each display size (100, 125, 150... %)/ DPI (96, 120, 144...) In the GoFish environment I have the font set smaller, which is fine, but that size now carries over to the menus, which are too small (my display size is 150 %, DPI 144). Is it possible to make this feature optional somewhere in the settings if I do not want to use it?

**Comment by Jimrnelson** [comment]
@klepetox 

Before I change anything, a couple questions:

- What default font size are you using for GF?
- Is there a larger default font size that displays the menu items  so that they are not too small?

**Comment by klepetox** [comment]
My default font size is 12.

If you omit

`lnBar	   = m.lnBar + 1
lcPrompt2a = 'Stem to clipboard'
Define Bar (m.lnBar) Of (m.lcMenuName) Prompt '\<' + m.lcPrompt2a &lcFont
On Selection Bar (m.lnBar) Of (m.lcMenuName) m.lcChoice = m.lcPrompt2a
`

**Comment by Jimrnelson** [comment]
@klepetox 

When you say "my default size" are you talking about the GF default font size that appears in the Options form?

![image](https://github.com/user-attachments/assets/6ce94e5b-4c60-4ff4-95dd-afaa8b46cadf)

**Comment by klepetox** [comment]
Yes, I mean this Default font size.

**Comment by Jimrnelson** [comment]
In that case, I am a little confused, as the font size for context menus is currently 2 + the GF default font size.

Since you said your value for GF size is 12, I don't see what you're not getting a font size of 14 for your context menu.

In any case, my intent is to allow you to directly change the context menu font size if desired (another spinner on the "New in V7" page).  This should allow you to change it as you need and provide for any other user's needs as well (who also might not find the current method to their liking)

**Comment by klepetox** [comment]
> In any case, my intent is to allow you to directly change the context menu font size if desired (another spinner on the "New in V7" page). This should allow you to change it as you need and provide for any other user's needs as well (who also might not find the current method to their liking)

Yes, this would be a good solution.

> Since you said your value for GF size is 12, I don't see what you're not getting a font size of 14 for your context menu.

This is really strange, I see you add 2 points in context menu. Maybe it depends from the screen DPI? But see these screenshots:

Foxpro default menu
![2](https://github.com/user-attachments/assets/75f1cc7e-d8b0-4145-89f2-e16455d8c9ac)


Gofish context menu
![1](https://github.com/user-attachments/assets/098623fe-6c4d-4448-82ce-a581d1d49efe)

Anyway, I think that the best solution is let system to set menu font size itself.

**Comment by Jimrnelson** [comment]
Hmmm, I can really discern any difference in your two images.  Am guessing that the images auto expanded somehow.

No matter.

I hope to have this update out there this weekend.

**Comment by klepetox** [comment]
You use another font for menu than system, so that the difference in size may be due to the Calibri font, while the default menu font in system (and Foxpro) is Segoe UI.

> Windows 10 uses the Segoe UI font as the default system font. This font is used for icons, menus, title bar text, File Explorer, and more.

So the ideal would be this:
![4](https://github.com/user-attachments/assets/f9358e06-6d4a-4aeb-b219-df5df52c4dda)

**Comment by klepetox** [comment]
Jim, thanks for these edits. I see you're now using the correct Segoe UI font, so the system settings option is a bit meaningless. I will achieve it now by setting the correct font size (14 for DPI 144) without changing font name. However, it would make sense if the font changes in Windows in some future version.

**Comment by Jimrnelson** [comment]
> without changing font name. However, it would make sense if the font changes in Windows in some future version.

I really doubt that this would ever be addressed.  There are already a number of options for setting font sizes in GF; it would be odd indeed to have only one place where one could choose the font name as well.

In any case, thank you for bringing up this topic and identifying the appropriate font.  I have absolutely no recollection how the font I was using was selected, other than to say that it's the same for fonts in Thor (such as for Thor Tools).

**Comment by klepetox** [comment]
I meant that it's better to use the system font for menus, which applies everywhere else in Windows. In Foxpro, the default font is Arial, while the menu is controlled by Windows itself, and in current versions it's the Segoe UI font. If you chose a different one, I'd like to revert back to this default. So this only applies to menus, which is the case here. Anyway, thank you very much, I've also clarified how it actually is.

**Comment by Jimrnelson** [comment]
In that case, is it possible to programmatically determine what the font used by Windows is?  That would be the best solution.

**Comment by klepetox** [comment]
Yes, that would be the best solution, but I don't think there's any way to find out. I went through the entire registry and searched for "Segoe UI". It's nowhere to be found. I think this is perfectly well resolved so far and this issue can be shelved indefinitely.
