### ISSUE TITLE
GoFish 7.1.28 - not returning any results 

### ISSUE THREAD

**Issue by parios59** [VFPX/GoFish#302]
## ℹ Computer information

- VFP version: 09.00.0000.7423
- GoFish version: 7.1.28

## 📝 Provide detailed reproduction steps (if any)

1. …entered a known table name 
2. …scope was current dir
3. …

### ✔️ Expected result
      List of locations of the searched name
_What is the expected result of the above steps?_

### ❌ Actual result  no results

_What is the actual result of the above steps?_

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots

_Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
@parios59 

GF is not a very efficient way to search for file names (if that's all your after.)  It's really there for searching the contents of files.

By default, GF does not search DBFs.  

However, you can cause it to do so by using the "Advanced" form and entering a file template like *.dbf

![image](https://github.com/user-attachments/assets/156c7816-ce56-4488-8daa-ba6504a6097b)

**Comment by parios59** [comment]
Hey Jim,
   This is what I queried for, I was looking multiple files that had
"report form"

2 shots below..
[image: image.png]

looking for list of prgs, scx that had "report form"

[image: image.png]

Pete Rios
***@***.***
760-455-9461

 “Program to an interface, not in implementation!”

- Nick Hodges

*P* *Please consider the environment before printing this e-mail*
CONFIDENTIALITY NOTICE: This email message is for the sole use of the
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized review, use, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message

**Comment by Jimrnelson** [comment]
@parios59 

Oops, sorry, I misinterpreted your original message.

I was not able to see your screen shots; I assume you pasted the images into the email where ever you read it, but the only way that works is to click on the link to View in in Github, at the bottom of the screen, and enter your message there and paste the images in there.

So, please include a screenshot of the GF screen just before you click on GF so I can see what your setup is, along with the other images.  I am assuming that the images are for files in the same directory.

**Comment by parios59** [comment]
![2024-10-07_11-56-55](https://github.com/user-attachments/assets/13017f91-d674-46ac-9093-d2239bd911cb)
![2024-10-07_12-00-17](https://github.com/user-attachments/assets/f7037f3c-ef50-4f88-b771-fab02133534a)


here are the pic...

**Comment by parios59** [comment]
Jim updated w/ pics...

**Comment by parios59** [comment]
![2024-10-07_13-08-58](https://github.com/user-attachments/assets/7ef9d0e5-9c1b-462a-a35a-4b5ac3a3368d)

it is working now... restarted computer is all I did...

**Comment by Jimrnelson** [comment]
> it is working now... restarted computer is all I did...

Woo hoo!  Glad it's been resolved!
