### ISSUE TITLE
Searching with "Whole word" option sometimes doesn't work correctly

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#304]
I search expression `do form` with option "Whole word".

The result:

![1](https://github.com/user-attachments/assets/53d98aed-7327-4039-bcbb-88d0d775897a)

Characters with accent are supposed as word delimiter `lcPattern = '.*\b' + lcPattern + '\b.*'`

I don't think there is a simple solution to this, do you? Fortunately, this is a peripheral issue and does not need to be addressed.

**Comment by Jimrnelson** [comment]
@klepetox 

This looks like something outside of GF's control, as it uses VBScript.RegExp, which, apparently, mis-inteprets the use of characters with accents.

No, I do not think there is a simple solution to this at all.

**Comment by klepetox** [comment]
I think so too, you can close this topic. There is a solution of course, but without a simple regular expression, and it is unnecessarily complicated.
