### ISSUE TITLE
Previous searches should remember text case

### ISSUE THREAD

**Issue by duncanlang1** [VFPX/GoFish#306]
Currently, all previous searches are converted to lower case when you view and select them from the search combo box. They should instead remember the original case they were typed in particularly because of the "Match Case" search option. If you originally searched for something all uppercase with "Match Case" enabled, this would return different results if you select the same search from the combo box as the text will be all lowercase instead.

Text field as I search:
![image](https://github.com/user-attachments/assets/0cd3600a-0187-4c4c-9a3c-628aba0916dc)

Search as saved in the combo box:
![image](https://github.com/user-attachments/assets/9e04fd2a-6a49-4d5a-8373-0897aeed46a2)

**Comment by Jimrnelson** [comment]
Fixed in Version 7.1.30 - 2024-11-01

Frankly, I am somewhat amazed this has not been mentioned before.

An easy one to fix, simply removing one call to `LOWER()`
