### ISSUE TITLE
Expression evaluated to an illegal value error

### ISSUE THREAD

**Issue by billand88** [VFPX/GoFish#308]
## ℹ Computer information

- VFP version: 9.0 SP2 3 hot fixes
- GoFish version: 7.1.30

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish. I had it set at 1250 x 555 width/height on laptop. Probably not relevant.
2. Grab lower right corner of form and pull it northeast.
3. Boom!

OK, here I go "off script". I had a separate laptop that didn't display the issue in 7.1.29, upgraded, to 7.1.30, tried it, hey, no issue. But as you'll see below, there was also no monitor detachment.

So these steps are before # 1. 

Run GoFish attached to a larger monitor. The monitor this was run off of was 3440 x 1440, but there's no driver for that setting. Using _screen I'm getting 2560 x 940. Basically, something beyond the standard stuff.

Hibernate it, but have GoFish at least partially show on a smaller screen.

Detach monitor. Unhibernate it or unsleep it, My option is "Sleep"

Bring it out of hibernation or sleep. 
Center GoFIsh or shorten it enough to be near full screen on the monitor. 
Now try # 1.

### ✔️ Expected result

No boom.

### ❌ Actual result

Error: Expression evaluated to an illegal value.

Here's the problem - it's not just a problem with that specific session. It'll happen over and over and over again. Restart VFP, same thing.

## 📷 Debugging Info

It's not just an obscure bug, it's an obscure bug with a really bad result. The keyboard keys are non-responsive. The only way out of this I found was to Ctrl+Esc to the Windows menu, go to Task Manager and kill the session.

**Comment by Jimrnelson** [comment]
Bill --

Fixed in Version 7.1.31 - 2024-11-04
