### ISSUE TITLE
GF_Search_History_Form_Settings.xml written to default folder

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/GoFish#31]
## ℹ Computer information

- VFP version: 09.00.0000.7423
- GoFish version: 5.1.003
- Last GoFish version w/o bug (if available): something before 5.1.002

## 📝 Provide detailed reproduction steps (if any)

1. Open GoFish
2. Click the _History_ button
3. Move and resize the History window
4. Close the History window

I tried moving the GF_Search_History_Form_Settings.xml file to the HOME(7) folder, but GoFish ignored it. When I opened and closed the History form, it wrote the settings to the default folder again.

### ✔️ Expected result

History window settings are saved in the HOME(7) folder

### ❌ Actual result

History window settings are saved in the VFP default folder: SYS(5) + CURDIR()

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/9847353/199023774-48d2757c-5b83-4a5f-88b2-c3150e0068aa.png)
![image](https://user-images.githubusercontent.com/9847353/199022908-681c860d-f472-4855-9a51-5617e92aa091.png)
![image](https://user-images.githubusercontent.com/9847353/199022979-bda5ff32-6c4a-4322-aa08-7716508157a9.png)

**Comment by lscheffler** [comment]
O.K. I see this one.

**Comment by mikepotjer** [comment]
This didn't happen until later when I set a filter, but GF_Filter_Settings.xml is also writing to the default folder.
![image](https://user-images.githubusercontent.com/9847353/199227904-d258a3d6-5a0d-4719-aafa-af20ab2270a0.png)

**Comment by lscheffler** [comment]
It looks like all settings except options and result

**Comment by mikepotjer** [comment]
Thanks @lscheffler ! This is behaving as expected now.
