### ISSUE TITLE
When editing, select the control where match is found in Options

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#311]
I have switched off item "When editing, select the control where match is found" in Options (I don't want it because saving dialog). But it doesn't work correctly. Base classes Container, Image, Commandgroup... are always selected, while Textbox, Command... are correctly not selected.

**Comment by Jimrnelson** [comment]
@klepetox 

Understood.  That is why the checkbox is provided, so that you can avoid those behaviors.

It is known that sometimes it does not work at all and sometimes it works but causes the saving dialog.  Neither can be predicted.
