### ISSUE TITLE
Scope "Browse Directory" doesn't work correctly sometimes

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#312]
When I set the search area to Browse Directory, the first time the search works. But if I do it again, the thermometer "Creating list of files (using grep.exe)" is displayed (Escape doesn't help) and I have to force quit FoxPro in the task manager. But not always, try it several times or restart GoFish and try it again...

**Comment by Jimrnelson** [comment]
@klepetox 

This is a rough one to diagnose.  I cannot replicate the problem and, quite frankly, cannot imagine why the Esc press does not work.

Hmmm, does it work when you Esc during the processing of files (second progress bar)?  Or does

**Comment by klepetox** [comment]
The progress bar is displayed with no progress, when i press Escape, system Windows froze the whole FoxPro and i must kill it in the task manager.

**Comment by Jimrnelson** [comment]
Got that.  Also, I have no idea what that could be caused by.  (This will require some headscratching).

Nonetheless, you said you can run it the first time, and my question had to do with when you get the second progress bar, whether pressing [Esc] works.

**Comment by klepetox** [comment]
Escape probably has nothing to do with it at all, only the first progress bar appears and that's the end of it. After GoFish button this appears and everything is frozen

![1](https://github.com/user-attachments/assets/ea7b65b5-646b-4b22-ae32-1167ab20f1a6)

And after Escape Windows recognize frozen application

![2](https://github.com/user-attachments/assets/2b561c8a-aace-4af8-a961-7c1f4f8f8c0d)

**Comment by Jimrnelson** [comment]
OK, so you don't want to answer my question about when it gets to the second progress bar.  (You did say it works the first time ...)

In any case, you can disable usage of grep on the Advanced page:

![image](https://github.com/user-attachments/assets/5b6af82c-3a65-4a98-bb4a-b0c7c60267da)

**Comment by klepetox** [comment]
When I don't use Grep, everything is OK, but see my previous comment - edit. There's no second progress bar.

**Comment by klepetox** [comment]
Could it be my settings? The table gf_results_form_settings.dbf is 55 MB, that's too much.

**Comment by Jimrnelson** [comment]
Your original message said this:

> When I set the search area to Browse Directory, the first time the search works

If that is correct, then you can run using grep at least once where it succeeds.  

When that happens, you should see two progress bars, one for grep, the second for the list of files found by grep.

I am asking that in this case you see if pressing [Esc] on the second progress bar works to interrupt execution.

I am trying to determine if the [Esc] button is being handled properly.

**Comment by Jimrnelson** [comment]
> Could it be my settings? 

No, your settings have nothing to do with this.  This has only to do with how the progress bar works and how it is interrupted by [Esc].

> The table gf_results_form_settings.dbf is 55 MB, that's too much.

Unfortunately, that file name is completely wrong.  The contents have nothing to do with form settings.  Instead, the file has to do with saved results from previous searches.  That's not an unreasonable size.  (The file is cleaned up from time to time by the GF Janitor)

**Comment by Jimrnelson** [comment]
> When I don't use Grep, everything is OK, but see my previous comment

Then I suggest you leave grep turned off.  Unless you are searching really large directories, you are unlikely to be distressed by the extra time a search takes.

BTW, note that grep only applies to directory searches, not project searches.

**Comment by klepetox** [comment]
Escape works:

![1](https://github.com/user-attachments/assets/3e942a18-df00-4100-a7d5-0b4395f30235)

I try this:

`*GF_Shell(m.tcBATFile)
! &tcBatFile
`

**Comment by klepetox** [comment]
I have commented this line and it works perfectly now!!!

`* Sleep (250) && quarter second`

**Comment by klepetox** [comment]
The reason for this behavior is simple. I have my universal procedure and function file, where I use also function Sleep() - but the timeout is in seconds, not milliseconds. The Sleep(250) waits 250 seconds then. When I close procedure file (set procedure to), it works. You can close this topic, I'm sorry to have kept you.

**Comment by Jimrnelson** [comment]
> The reason for this behavior is simple. I have my universal procedure and function file, where I use also function Sleep() - but the timeout is in seconds, not milliseconds. The Sleep(250) waits 250 seconds then. When I close procedure file (set procedure to), it works. You can close this topic, I'm sorry to have kept you.

Understood.

I, too, prefer to express the timeout in seconds, not milliseconds.

My procedure is named DELAY, which avoids the conflict with Windows Sleep.
