### ISSUE TITLE
Include files checkbox in Advanced options

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#314]
Would it be too much work to add "Include Files" similar to "Skip Files"? I have some programs and forms that are not related to the project, but when I make replacements, I need to make replacements in them as well. So far I solve this by including the files and forms in the project as "excluded", but it's not very practical.

![1](https://github.com/user-attachments/assets/8672ec04-91d1-485e-814e-17b7d3bc8aff)

**Comment by Jimrnelson** [comment]
Implemented in Version 7.1.33 - 2024-11-19

New feature:
- "Include Files" option added to Advanced screen, to allow searching additional files not part of the normal scope (project or directory).  See also the right-click context menu on the "Advanced" button. (#314)

**Comment by klepetox** [comment]
It works correctly, that is what i need!

But scope "Project in Curdir" is broken. It doesn't work if project is not open (active). I must stay with previous version in the meantime.

**Comment by Jimrnelson** [comment]
@klepetox 

> But scope "Project in Curdir" is broken. It doesn't work if project is not open (active). I must stay with previous version in the meantime.

Yeah, oops! ... Easy bug to fix, I'll try to get to that this weekend.
