### ISSUE TITLE
GoFish doesn't search for .Picture property in class libraries, where base class is Form

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#315]
GoFish doesn't search for .Picture property in class libraries, where base class is Form.

My example:

univcls.vcx -> openfile (form) -> cmdSelectAll.Picture="c:\fox\wuniv\ikony\markall 16x16.bmp"

There's no results when I search for "\wuniv\ikony\\". But when I search in forms the results are correct.

**Comment by klepetox** [comment]
My mistake again, there's no complete path in database file univcls.vcx, but relative "..\ikony\markall 16x16.bmp". That's the reason why I cannot find "\wuniv\ikony\markall 16x16.bmp". I close this topic.

**Comment by Jimrnelson** [comment]
> My mistake again, there's no complete path in database file univcls.vcx, but relative "..\ikony\markall 16x16.bmp". That's the reason why I cannot find "\wuniv\ikony\markall 16x16.bmp". I close this topic.

Yes, that was my first guess.
