### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#320]
## ℹ Computer information

- VFP version: 9 SP2
- GoFish version: 7.1.34

## 📝 Provide detailed reproduction steps (if any)
While trying to get past a previous error, I tried closing the application's  vcx and using Go Fish search in 'Project(s) in CurDir()
That throws a "Class definition GF_FILERESULT is not found error

### ✔️ Expected result
Search w/o error

### ❌ Actual result
Error as stated above.
As expected, Ignoring the error is fatal.

## 📷 Debugging Info
Please add screenshots of
![image](https://github.com/user-attachments/assets/33436a99-0f10-4eec-87d5-fcc0b689e350)

- Windows from the debugger
     - Trace window
 
![image](https://github.com/user-attachments/assets/cbdee401-91d4-4cf0-a4f7-7176f122fdf2)

     - Locals window
    
![image](https://github.com/user-attachments/assets/3c7cd3ff-650f-4d2a-b925-e15de86c6abc)

     - Call stack window
![image](https://github.com/user-attachments/assets/080e6135-33a0-4627-aca4-49dd31654573)

**Comment by Jimrnelson** [comment]
I am not surprised by this. 

If GF died on an error, it might not have been able to clean up its environment.
