### ISSUE TITLE
GoFish stopped searching results in cleanup procedure in menus

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#321]
I don't find any results in cleanup procedure in menus. This is a serious bug for me, because I replaced the procedure name (DELFILE) in the whole program.

And there's an error when I try to compile program with "Unable to find Unknown DELFILE" and GoFish cannot find any results for "DELFILE" (in cleanup procedure).

**Comment by Jimrnelson** [comment]
@klepetox 

Please attach all the files for this menu.

Also, where do you enter/edit this cleanup procedure (I had not heard of it until your message)

**Comment by klepetox** [comment]
My menu with "delfile" in cleanup code.



------ Původní zpráva ------
Od "Jimrnelson" ***@***.***>
Komu "VFPX/GoFish" ***@***.***>
Kopie "Lubos Kopecny" ***@***.***>; "Mention" 
***@***.***>
Datum 04.12.2024 20:46:35
Předmět Re: [VFPX/GoFish] GoFish stopped searching results in cleanup 
procedure in menus (Issue #321)

**Comment by klepetox** [comment]
I'm sending my menu to your mail. Try to search "delfile" - no results.

Then open menu in FoxPro (modify menu) and have it active. Then: FoxPro menu - View - General Options - Cleanup - OK - and Cleanup code snippet will open.

**Comment by Jimrnelson** [comment]
@klepetox 

I haven't received your menu in my personal email

**Comment by Jimrnelson** [comment]
Fixed in Version 7.1.36 - 2024-12-05
