### ISSUE TITLE
Bug report when trying to use Filter Form

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#36]
## ℹ Computer information

- VFP version: 
- GoFish version: 5.1.006
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

[1]  When opening the Filter form, the form settings file is no longer used ... the form is placed at 0,0 -- which is not where it had been before this version

[2]  When closing the Filter form, I get a hard error, which is trying to save the settings:

    File 'GF_Filter_PF_Form_Setttings.xml' does not exist.

![image](https://user-images.githubusercontent.com/81179335/203167365-da176fcc-8214-4501-89cb-1c15db2ff640.png)

There are multiple problems with this:
     1 - The file does not have to exist -- it should be created if it does not exist.
     2 - The file should be created, if anywhere in Home(7), not the current folder.
     3 - This, apparently, is a new file, replacing older versions?

    

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/81179335/203167391-d92db481-a1fa-4626-93a9-28ea1bd2812b.png)

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
@Jimrnelson I think the initial Top/Left  problem is related to the file issue, it just looks that the loadproperties fails too, but w/o error.

**Comment by lscheffler** [comment]
@Jimrnelson Somehow this form does not follow the inherited way to load the settings file ....
