### ISSUE TITLE
Filter Settings file 'GF_Filter_Settings.xml' is being saved in current folder instead of Home(7)

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#38]
## ℹ Computer information

- VFP version: 
- GoFish version:
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

ALL settings files should be saved in Home(7), not the current folder.  The property value should look like 

    = Home(7) + 'GF_Filter_Settings.xml'

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
@Jimrnelson FYI   
With the newer versions, the *cUISettingsFile* property only holds the name of the XML file, the location is determined later on. For this SCX, the inheritance of the storage seems to be violated, or called non standard, so it picks the `FULLPATH("","")` as location.

**Comment by lscheffler** [comment]
Can you tell me how to call this? For the moment I see no code calling the SCX ....

**Comment by Jimrnelson** [comment]
After doing a search, there is a Filter button:

![image](https://user-images.githubusercontent.com/81179335/203418039-f60a51cf-1787-4cc7-be93-df9acae69d24.png)

(It may be aligned differently on your computer.)

**Comment by lscheffler** [comment]
This raises   
![grafik](https://user-images.githubusercontent.com/27769909/203418809-41e9f8b7-52a8-4c84-a7a5-f95d35972caa.png)

and should write _GF_Filter_PF_Form_Settings.xml_ rather then _GF_Filter_Settings.xml_ The second one comes from this mask.   
![grafik](https://user-images.githubusercontent.com/27769909/203418529-f593855b-c855-4383-aadd-d93780417b1f.png)

I see not how to call this.

**Comment by lscheffler** [comment]
Anyway, you have the latest version? There was some oddness with  _GF_Filter_Settings.xml_ in 5.1.006, at least I see files as of this morning while I was fixing #36, but I can't reproduce with the recent version.

**Comment by Jimrnelson** [comment]
Lutz --

GF V 5.1.006 had the problem with file not found.

GF V 5.1.007, (today), which I have downloaded from Thor Check For Updates, has this problem resolved but the file is saved into the current folder rather than Home(7).

I don't know about the difference between the settings files for the two instances you showed, although I do wonder why the file names have changed.  

In any case, the problem remains that ANY settings file should be saved in Home(7).

**Comment by lscheffler** [comment]
@Jimrnelson    
- It is wrong to store to current path.
- No, Home(7) is just one option since 5.1, if you prefer this approach. Options/Advanced offers a storage depending on active FOXUSER now. You need to activate the *Code References* switch first. **I** dislike anything in Home(7), it's the wrong drive, it scatters searches between projects, it's simply odd to me. I like my projects contained. One of the reasons to work on GoFish at all is to change this. Anyway, Home(7) is default. The bugs are related to the solution of this problem. Sorry. Let's say we store to *GF settings folder*.
- the Filter form stores to two files, the storage place of one was set up wrong.

**Comment by Jimrnelson** [comment]
Lutz --

As long as the default for all GF settings files is in Home(7), all is well.

For me, if I were interested in saving settings by project, I would want that to apply only to some settings, not all.  Certainly, the size and position of forms, column settings (widths and order), and so on, I would always want the same across my universe, and only things like search history would make sense to keep by project.  

However, I'm happy enough with Home(7) -- actually, way too late in the game, I wish Matt would have stuck all GF settings files in a sub-folder of Home(7) instead.  Same for me and PEMEditor settings.

**Comment by lscheffler** [comment]
@Jimrnelson I see this like you, but my problems are
- Home(7) is by M$ default on C: somewhere, I dislike data there
- even for the comps I have changed the default for user path, it's nowhere near to my development
- to have the global / local stuff splited like you wrote is an idea. Just set up an issue, maybe somebody find it a good thing. 
- with GF 6.0, - in development on my comp - the whole GF settings / history will go to a subdirectory of Home(7) by default. I dissed the way it was too. Also I found a way to speed up the history, keeping old stuff. I like it CodeReference style, with the tree showing the old stuff on startup, so I need to do this anyway. Again, all visual stuff as option.

**Comment by Jimrnelson** [comment]
Sounds good, although not something I would take advantage of.

With GF 6.0, just make sure that the previous settings files and history are all still in effect (even if that means GF would have to move them to the new folder).

Do you have other plans for 6.0?

**Comment by lscheffler** [comment]
@Jimrnelson    
Yes, I keep the settings and history.    
In general, I try to make the UI more CodeReferences like - all  optional
- Options etc per project (... active resource file)
- Open GoFish by default for recent project or folder if no project active as scope
- Let the History form follow scope (just results fitting to recent scope)
- Show search History in Search combo per scope
- Show History in tree with some sub options
- Simple tree, just search + filenames,  with a sorting option

Additional right click function for the tree, as Refresh, Delete - like CodeReferences.
