### ISSUE TITLE
Memowidth should be to a higher value

### ISSUE THREAD

**Issue by CarlosYohn** [VFPX/GoFish#43]
## ℹ Computer information

- VFP version: VFPA32
- GoFish version: 5.0.205
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. …Suposse you are looking for forms that uses 'legaliza.dbc' database in dataenviro; and one form's cursor has this line on his properties:
Database = ..\..\..\..\..\datosvfp\legaliza\datos_zar\legaliza.dbc
Having memowidth setting of 50 (default), gofish wouldn't find it because line will be divided in this way:
line 1 = "..\..\..\..\..\datosvfp\legaliza\datos_zar\legaliz"
line 2 = "a.dbc"
So atcline returns 0

SET MEMOWIDTH TO 8192 && or any high value, will solve it

**Comment by lscheffler** [comment]
@CarlosYohn I understand what you mean, but I see not where this is used. There is one place where GoFish uses `MLINE()` and one `ATLINE()`. Can you provide an example file?

Anyway, there is `ALINES()` for this.. (－‸ლ)

**Comment by CarlosYohn** [comment]
Hello,
I must apologyze. I've dowloaded again original app and problem does not happens. Actually don't know what i did to find it.
Anyway, i am very sorry. If i found it again, I will send a sample.
Regards.

**Comment by lscheffler** [comment]
@CarlosYohn Never mind. Try to install GoFish via Thor, updates are available there more easily.

**Comment by CarlosYohn** [comment]
Hi again.

Now, I come back with this thread.
One folder with just one prg file (attached txt its a .prg); search for 'bz_adapta'; no results. But there are.
Seems to not has nothing to do with memowidth.

[ver51.TXT](https://github.com/VFPX/GoFish/files/10673887/ver51.TXT)

**Comment by lscheffler** [comment]
Moved to new issue
