### ISSUE TITLE
String not found while existing

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#44]
Hi again.

Now, I come back with this thread.
One folder with just one prg file (attached txt its a .prg); search for 'bz_adapta'; no results. But there are.
Seems to not has nothing to do with memowidth.

[ver51.TXT](https://github.com/VFPX/GoFish/files/10673887/ver51.TXT)

_Originally posted by @CarlosYohn in https://github.com/VFPX/GoFish/issues/43#issuecomment-1420526806_

**Comment by lscheffler** [comment]
Using the app as published, I found `do bz_adapta.prg` on line 20.
Would you mind to zip files `%AppData%\Microsoft\Visual FoxPro 9\GF*.*` or `%AppData%\Microsoft\Visual FoxPro Advanced\GF*.*`? **Do not include** folder _GF_Saved_Search_Results_ from this folder.

**Comment by CarlosYohn** [comment]
Sent. Thanks for answering.
[Visual FoxPro Advanced.zip](https://github.com/VFPX/GoFish/files/10677981/Visual.FoxPro.Advanced.zip)

**Comment by lscheffler** [comment]
I do not know what exactly is corrupted, but something is gone with your GoFish settings. There are more failures to find.   
Close VFPA, remove the GF*.* files from the folder mentioned, restart, at least this fixed the problem with me.

Let me know the result

**Comment by CarlosYohn** [comment]
Hi,
Yes. That solved the issue.
Many Thanks.
