### ISSUE TITLE
Advanced Settings does not open under certain conditions 

### ISSUE THREAD

**Issue by rschummer** [VFPX/GoFish#45]
## ℹ Computer information

- VFP version: 9.0.0.7423
- GoFish version: 5.1.009 (1/31/2023)
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Start GoFish
2. Click Advanced button with binoculars
3. Crash 
Property GNVIRTUALTOP is not found.

### ✔️ Expected result

To open the Advanced Settings dialog.

### ❌ Actual result

MessageBox with error displayed.

Actually, stepping through the code, none of the properties in this section of code for the variable loMonitor are defined in the object.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/6232082/219129518-41ced2d3-57d6-485a-bc22-da45fbc1c452.png)

**Comment by rschummer** [comment]
Same issue with the Options dialog.

**Comment by lscheffler** [comment]
@rschummer At least consistent, the forms inheriting the same class.   

To circumvent the problem, you might try to reset desktop setting. This is in `HOME(7)\GF_Results_Form_Settings.xml` the property _lDesktop_ , set to False.

Anyway, this problem is strange. Do you have, by any chance, a procedure `GetMonitorStatistics` somewhere in your path that get precedence over the one shipped with GoFish? Can you breakpoint the function call and step into? The code that should run is in _.\source\prg\gofishproc.prg_ and simply creates the properties asked in code, not the ones you see. None of the ones in LOCAL window are declared in GoFish.

**Comment by lscheffler** [comment]
@rschummer  Check https://github.com/VFPX/GoFish/blob/master/Source/Prg/gofishproc.prg  at the very end, this is the code that should run.

**Comment by rschummer** [comment]
Your recommendation to reset the desktop setting is what I did to move past this. I recognized this was what needed to be done when I was stepping through the code. The weird part is, it was set to false to begin. I toggled it true and back to false to get past the erroring code.

**Comment by lscheffler** [comment]
You don't have a backup of the original files?  

The lDesktop does only change the behaviour of the main form.  `DESKTOP` must be set at design time, and the main prg selects the form to start. For the _secondary forms_ like advanced or options, `DOCKABLE` is the culprit. What changed while switching lDesktop is not very clear.

Have you tried to step into the function? The settings are not the real problem.

**Comment by rschummer** [comment]
I did step through the code, as I showed the debugger in my original post. I understand why the program crashed for me with regards to the object not having the proper properties. I'm sure the program will work once this object is properly defined, or the code is corrected to the proper names of the properties.

**Comment by lscheffler** [comment]
What I mean, can you step **into**  `GetMonitorStatistics` and create a screenshot of the code, or compare with 
```
Procedure GetMonitorStatistics
************************************************************************
* GetMonitorStatistics
****************************************
***  Function: Returns information about the desktop screen
***            Can be used to check for desktop width and size
***            and determine when a second monitor is disabled
***            and layout needs to be adjusted to keep the
***            window visible.
***      Pass:
***    Return:  Monitor Object
***
*** From https://west-wind.com/wconnect/weblog/ShowEntry.blog?id=836
*** Handling Multiple Screens in Visual FoxPro Desktop Applications
***
************************************************************************

	#Define SM_CXFULLSCREEN		16
	#Define SM_CYFULLSCREEN		17

	#Define SM_XVIRTUALSCREEN	76
	#Define SM_YVIRTUALSCREEN	77
	#Define SM_CXVIRTUALSCREEN	78
	#Define SM_CYVIRTUALSCREEN	79
	#Define SM_CMONITORS		80

	#Define SM_XVIRTUALSCREEN	76
	#Define SM_YVIRTUALSCREEN	77
	#Define SM_CXVIRTUALSCREEN	78
	#Define SM_CYVIRTUALSCREEN	79


	Declare Integer GetSystemMetrics In user32 Integer nIndex

	loMonitor = Createobject("EMPTY")
*	AddProperty(loMonitor, "gnMonitors",      GetSystemMetrics(SM_CMONITORS))

	AddProperty(loMonitor, "gnVirtualLeft",   GetSystemMetrics(SM_XVIRTUALSCREEN))
	AddProperty(loMonitor, "gnVirtualTop",    GetSystemMetrics(SM_YVIRTUALSCREEN))

	AddProperty(loMonitor, "gnVirtualWidth",  GetSystemMetrics(SM_CXVIRTUALSCREEN))
	AddProperty(loMonitor, "gnVirtualHeight", GetSystemMetrics(SM_CYVIRTUALSCREEN))

	AddProperty(loMonitor, "gnVirtualRight",  m.loMonitor.gnVirtualWidth -  Abs(m.loMonitor.gnVirtualLeft) - 10)
	AddProperty(loMonitor, "gnVirtualBottom", m.loMonitor.gnVirtualHeight - Abs(m.loMonitor.gnVirtualTop)  -  5)

*ADDPROPERTY(loMonitor, "gnScreenHeight",  GetSystemMetrics(SM_CYFULLSCREEN))
*ADDPROPERTY(loMonitor, "gnScreenWidth",   GetSystemMetrics(SM_CXFULLSCREEN))

	Return m.loMonitor

Endproc &&GetMonitorStatistics

```
the code in https://github.com/VFPX/GoFish/blob/master/Source/Prg/gofishproc.prg (at the very end) ?

This is the code expected to run - and there is none of the properties visible in your screenshot. All wisdom left to me is that you somehow run a different PROCDURE.

**Comment by lscheffler** [comment]
@rschummer  Try the latest version. The code is the same, only the **name** of the procedure is changed.

**Comment by rschummer** [comment]
The two dialogs are opening, but I tried to toggle the desktop setting to check that way too, and it crashed. See new issue reported.
