### ISSUE TITLE
Thor issue

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#59]
@Jimrnelson I have problems with the Thor menu of GoFish. There is a *Discussion Group* entry, and there is some code about it in [GoFish.prg](https://github.com/VFPX/GoFish/blob/master/Source/gofish.prg), around line 510, but I have no idea to alter the existing so that Thors menu links to github issues rather then google? I do not use google, and the forum is not maintained, so discussions and issues should be better here.

Thank you

**Comment by Jimrnelson** [comment]
I think you just change the link in this code to point to github

![image](https://user-images.githubusercontent.com/81179335/224492571-7a084016-7b50-4cab-baf6-5e1c5b0a7393.png)

**Comment by lscheffler** [comment]
If you follow the link above and look at line 512 you see the recent code - altered. Does change nothing on my comp when updating via Thor. Thor still links to google. I know nothing about the Thor mimics - and there seems to be a lot ways to deal with Thor.

**Comment by Jimrnelson** [comment]
> If you follow the link above and look at line 512 you see the recent code - altered. Does change nothing on my comp when updating via Thor. Thor still links to google. I know nothing about the Thor mimics - and there seems to be a lot ways to deal with Thor.

When you say "updating via Thor", what exactly do you mean?

When you run CFU in Thor for GF, it recreates a number of Thor tools; this is one of them.

**Comment by lscheffler** [comment]
Thor -> Check for Updates, Update GoFish via the form.

Any idea how to check what Thor is doing without exposing a new version to anybody?

What is CFU?

If you updated GoFish, where do you end up with Thor Tools -> Applications -> GoFish -> GoFish Discussion Group?

**Comment by Jimrnelson** [comment]
> Thor -> Check for Updates, Update GoFish via the form.
> 
> Any idea how to check what Thor is doing without exposing a new version to anybody?
> 
> What is CFU?
> 
> If you updated GoFish, where do you end up with Thor Tools -> Applications -> GoFish -> GoFish Discussion Group?

CFU = Check For Updates.

When running Check For Updates for GF, it should be re-creating a bunch of Thor tools in Thor\Tools.  Within each of those tools there are properties that cause them to appear as you are seeing them.  (These tools, visible somehow in the GF source code, should all have file creation timestamps matching the last GF update).

There actually IS a way to do fake Thor out so that you have can test installing an update, but it would not be worth it for this small issue.

**Comment by lscheffler** [comment]
I would agree - if it would run. But yes, it's not a big deal. Except I like to rename from GoFish5.app to GoFish6.app or simple GoFish.app and I hate things I can not test. It fails enough with test. And debugging Thor - not this wonder of calls, if I can avoid it.

**Comment by Jimrnelson** [comment]
> I would agree - if it would run. But yes, it's not a big deal. Except I like to rename from GoFish5.app to GoFish6.app or simple GoFish.app and I hate things I can not test. It fails enough with test. And debugging Thor - not this wonder of calls, if I can avoid it.

Oh, you like to test before releasing to production?  I've heard of people like you.

I suggest submitting an issue in Thor (rather than here in GF) on how to test-release to CFU.

**Comment by lscheffler** [comment]
oki I just do not know if the  problem is GoFish or Thor. :)
