### ISSUE TITLE
Does options form works?

### ISSUE THREAD

**Issue by CarlosYohn** [VFPX/GoFish#6]
## 📝 Provide detailed reproduction steps (if any)

1. … Just click on 'Options' button

### ❌ Actual result
Error

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/113931137/191080246-f251e3b8-908b-4b47-a544-99a9dae4e87a.png)

**Comment by DougHennig** [comment]
Are you using the latest version of GoFish? It works properly for me.

**Comment by DougHennig** [comment]
That sounds like an older version: the app and pjx should be dated August 2022.

**Comment by CarlosYohn** [comment]
Thanks, Doug. Ur right. Don´t know why my release was so old.

Saludos.

Carlos Yohn Zubiría - ***@***.*** <https://www.agpsoftware.com/>  - 94 480 23 45

De: Doug Hennig ***@***.***>
Enviado el: martes, 20 de septiembre de 2022 22:20
Para: VFPX/GoFish ***@***.***>
CC: Carlos Yohn Zubiría ***@***.***>; Author ***@***.***>
Asunto: Re: [VFPX/GoFish] Does options form works? (Issue #6)


That sounds like an older version: the app and pjx should be dated August 2022.
