### ISSUE TITLE
Update to GoFish 6 was a mess

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#63]
## ℹ Computer information

- VFP version: 9 build 7423
- GoFish version: 6.0
- Last GoFish version w/o bug (if available): 5.?

## 📝 Provide detailed reproduction steps (if any)

Thor updates ran today, bringing in the new GoFish. When I first opened it, it needed to do all kinds of updates. But SET CONFIRM was on. After confirming more than 1000 changes, I finally gave up. I SET CONFIRM OFF in the Command Window and tried again. GoFish opened right up, but after a search, I got an error about a missing DBF.

### ✔️ Expected result

Necessary updates would ask a few questions, but not require confirmation of 1000s of changes.

### ❌ Actual result

Required confirmation of 1000s of changes.

Note: I solved it all by deleting all my GoFish files from HOME(7), and trying again.

**Comment by lscheffler** [comment]
This is basically #35.

Please, what subversion of 6.0*?  

Did you manage to store a backup as suggested in the pre-update screen?   
For some this problems happens and I have no idea why. I urgently need a Backup of the pre v6 to look it up.

**Comment by lscheffler** [comment]
On initial start of v 6.0.6 there is a screen  expected to run, but somehow I managed to remove it from startup. V 6.0.7 will follow soon, just to provide this screen.

What I'm looking for is the folder `HOME(7)+"GoFish_Backup"`. Possibly you didn't delete this or delete to recycle bin?

**Comment by lscheffler** [comment]
This  screen
![grafik](https://user-images.githubusercontent.com/27769909/225069051-4b1f953e-7c98-4dee-8485-b5236d2afbba.png)

**Comment by TamarEGranor** [comment]
> On initial start of v 6.0.6 there is a screen expected to run, but somehow I managed to remove it from startup. V 6.0.7 will follow soon, just to provide this screen.
> 
> What I'm looking for is the folder `HOME(7)+"GoFish_Backup"`. Possibly you didn't delete this or delete to recycle bin?

It was in the Recycle bin. I restored it, zipped it up, put it in Dropbox and shared it with you. (Not comfortable uploading it publicly.)

**Comment by lscheffler** [comment]
Thank you. I would be uncomfortable as well. You shared to the address mentioned above?

**Comment by TamarEGranor** [comment]
Shared to your personal email. You should have an email from DropBox.

**Comment by lscheffler** [comment]
Yes, I received it now. Thank you

**Comment by lscheffler** [comment]
Heisenbug. It migrates your settings number one fine.   
Would you please  try:
1. go to Home(7)
2. rename *GoFish_* to something different
3. unzip the files and GF_Saved_Search_Results folder (this is not the GoFish_Backup) directly to Home(7)
4. rerun GoFish 6.0.6
5. It starts to migrate, and prints item numbers to your screen. If you got the confirm dialogue, would you please post the item?

If it runs through, all is fine, you kept your history. If not, I can send it to you.

**Comment by TamarEGranor** [comment]
Just want to clarify what I'm unzipping where. Are you saying that both the files and the folder that's in the zip file I sent you should go directly into HOME(7), not into a folder within HOME(7), for this test.

**Comment by lscheffler** [comment]
Yes. All the files and folder in "GoFishBackup.zip\GoFish_Backup\*.*" must be copied to HOME(7)

We try a rerun of the update from 5 to 6 and try if we see something more specific.

note, this will recreate the GoFish_Backup in Home(7)

**Comment by lscheffler** [comment]
@TamarEGranor Any further results? Else I will close this issue.

**Comment by TamarEGranor** [comment]
Finally getting a chance to try this again. As happened the first time, I'm being asked to confirm stuff. I've attached a few screen shots. I'm going to try to stick it out through all 60 jobs this time.

![GoFish1](https://user-images.githubusercontent.com/30271640/226446660-23ee601a-b692-4542-a61c-aa3f9e2ce579.jpg)
![GoFish2](https://user-images.githubusercontent.com/30271640/226446663-a8c99add-8d14-456d-a5ea-be0f9b18bd64.jpg)
![GoFish3](https://user-images.githubusercontent.com/30271640/226446664-12505324-0402-4fb4-b181-dd4767aa5eed.jpg)

I don't know what the item counts in the third shot are supposed to refer to, but they definitely don't match with the number of files I'm being asked to overwrite in each group.

Anyway, after 25 minutes or so, and only being up to item number 13, I'm giving up.

**Comment by TamarEGranor** [comment]
Sending the registry info you asked for to your email.

**Comment by lscheffler** [comment]
Since there is nobody with this problem for a long time I close this issue.
