### ISSUE TITLE
GoFish 6.0 is not active by default

### ISSUE THREAD

**Issue by nmpetkov** [VFPX/GoFish#66]
## ℹ Computer information

- VFP version: VFP 9 SP2
- GoFish version: 6.0.007
- Last GoFish version w/o bug (if available): 5.1

## 📝 Provide detailed reproduction steps (if any)
On initial launch of Gofish, I expect that I can immediately type in the search box with it selected. Strange why the screen appears but is not active and the field is not selected for writing immediately. If I click on the VFP desktop and then on the Gofish title bar - the box activates and highlights.
If the window is not closed, another window is being worked on, and with the shortcut (in my case F8) I call it, the screen activates normally as expected.
If the Gofish window is closed and called again (for example with the shortcut), the problem repeats itself.

I found some solution to the problem without finding the cause by putting the following lines after the block with Do Form GoFish_Results in gofish.prg:
`LOCAL oForm`
FOR EACH oForm IN _Screen.Forms
`	IF LOWER(oForm.Class) = 'gf_resultsform'`
`		oForm.editSearch.SetFocus`
`		EXIT`
`	ENDIF`
`ENDFOR`

**Comment by lscheffler** [comment]
For some reasons the *grid* has initial focus. So there is little help in TAB too.   The focus by re-entering the form is a bit more tricky.   
Just a `This.editSearch.SetFocus()` at the very end of gf_resultsform.init will do.

**Comment by nmpetkov** [comment]
Works in 6.0.008. Nice!
