### ISSUE TITLE
Treating continuation lines as a single line

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#67]
## 📝 Provide a description of the new feature

GF allows searching within physical lines.  It allows further filtering for continuation lines (which, incidentally, is one of the reasons for considerable bloat in search history files), but in some cases this is quite unsatisfactory.

I find at times that I would like to be able for the initial search to go across continuation lines.  An example would be to look for SELECT statements that refer to a specific file (which would be on a different physical line).

It would seem to me that the option for using regular expressions could be enhanced to recognize continuation lines.  I know just enough about regular expressions to recognize that this would be an ideal use (without being able to write the code myself).

Of course, regular expressions are quite a bit slower than the other search options, but would be worth it.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by lscheffler** [comment]
Some thoughts about it
- The Regexp would be rather complex, since it need to deal with the inline comments one might have on lines continued. 
- Should it search in the inline comments?
- I think it might be better (while slower) to first connect the lines continued to one long expression and search this.
Code doing this might be found for example in BeautifyX
- consider to use C# regexp, it's more powerful then the VB one

**Comment by lscheffler** [comment]
I try to imagine the regexp that is cool enough to find "^SELECT" + *From\s*MyTable* in
```
SELECT;
Cur1.*;
From  ;   && This is FROM
; && Just because I can do it && I'm cool
MyTable AS Cur1
```
You know MyTable should be in FROM, not JOIN, and in a SELECT not in an UPDATE, so not like
```
UPDATE Cur1 SET ... FROM MyTable INNER JOIN (;
SELECT;
Cur1.*;
From  ;   && This is FROM
; && Just because I can do it && I'm cool
MyTable AS Cur1) ON ...
```

**Comment by Jimrnelson** [comment]
Cool indeed ... now all we need is a little RegExp code!

**Comment by lscheffler** [comment]
To be true, I don't see a solution aside removing / replacing the inline comments, removing / replacing ;CRLF an deal with it as a line. This as a proprocess.
One might think to replace with the same number of spaces instead of remove, so the counting of chars in go fish is kept.
And even then, a two step approach might be faster then a complex regexp

**Comment by Jimrnelson** [comment]
There is a significant problem with such pre-processing.

GF is many times faster than Code References -- my simple test this morning took 14 seconds using GF and 10 minutes using CR, so  GF was about 40 times faster.

Of all the improvements that Matt employed to optimize GF, the most significant (by far) was to eliminate the pre-processing done in CR.

My guess is that the approach you outline here (which I assume would work) would be so slow as to be not worth the effort.

The reason for my original suggestion of using RegExp was to avoid this altogether, guessing that the time invested to get RegExp to do all the dirty work would result in timings not significantly different than what we currently see when using RegExp.

Just observed:

- Plain search - 5.4 sec
- Wildcard - 5.5
- RegExp - 28.3  (approximately 5 times longer)

I would not have made this suggestion at all if it could not be handled using RegExp.

**Comment by Jimrnelson** [comment]
And maybe why this is not feasible.

**Comment by lscheffler** [comment]
It's only **if** one need such an result, then time might be not the problem, compared with scanning every result. I never had the need for it the last 25a or so, it's more an intellectual challenge right now.    
And I think preprocessing might be best, because one can use simple expressions what are much faster then complex ones. Complex regexp patterns are slow down fast.   
Only thing - to repeat - is the number of chars to replace, so GoFish can use it's way to locate and store locations.   
;)

**Comment by lscheffler** [comment]
@Jimrnelson While looking up the issues list, what do we do with this?

**Comment by Jimrnelson** [comment]
@lscheffler 

This is a topic that Matt Slay and I spent a lot of time on at a time when his all consuming interest in GF was finally beginning to diminish.  He was clearly of the mind that he did not want to muck with the search engine unless he felt there was a compelling reason to do so.

Before investigating what changes would be necessary in the search engine, we decided to look for alternative solutions.  Thus, the "GoFish Filter Builder" form was born (one of the few places in GF where I contributed code).

We found that the "Within Same Statement" filter was easy to implement and covered all the cases we considered.  (I have a hard time recalling the last time I did not find it sufficient -- I do know it's been quite a few years.)

I think that the Filter form is one of the most powerful yet under-used features of GF.

I am sure it would be an interesting challenge to implement this request, but likely to be one of the special case features that is very rarely used, and thus not worth your effort.  

I suggest you decide not to pursue this.

**Comment by lscheffler** [comment]
While I still think preprocessing and then using GoFish like normal might work, I agree it's to exotic for such a complicated task. If there is a real need for it, we can rethink.

**Comment by lscheffler** [comment]
> There is a significant problem with such pre-processing.
> 
> GF is many times faster than Code References -- my simple test this morning took 14 seconds using GF and 10 minutes using CR, so GF was about 40 times faster.
> 
> Of all the improvements that Matt employed to optimize GF, the most significant (by far) was to eliminate the pre-processing done in CR.
> 
> My guess is that the approach you outline here (which I assume would work) would be so slow as to be not worth the effort.
> 
> The reason for my original suggestion of using RegExp was to avoid this altogether, guessing that the time invested to get RegExp to do all the dirty work would result in timings not significantly different than what we currently see when using RegExp.
> 
> Just observed:
> 
>     * Plain search - 5.4 sec
> 
>     * Wildcard - 5.5
> 
>     * RegExp - 28.3  (approximately 5 times longer)
> 
> 
> I would not have made this suggestion at all if it could not be handled using RegExp.

Hi @Jimrnelson ,

While I was working on #8 and looking up the use of RegExp in GoFish, I found that **any** search in GoFish is a RegExp. The option (Plain/Like/RegExp) is more what is wrapped to be not a RegExp specific expression. (Plain: all is wrapped; Like: All is wrapped, but *? is transformed to RegExp equivalent; RegExp: as is).   
So your result above is a bit odd. Was there a more complex RegExp in use, or just turned on?)

Anyway, I learned a bit more RegExp - in special the DotNet flavour - so the topic might be a bit closer to solve. :)

**Comment by Jimrnelson** [comment]
@lscheffler 

> While I was working on #8 and looking up the use of RegExp in GoFish, I found that **any** search in GoFish is a RegExp. 

I am quite surprised by this, but then again I am not looking at the code.  I do recall that Matt achieved significant optimization for the non RegExp cases and my result of RegExp being a lot slower has been consistent over time (and is exactly what Matt observed.)

If  RegExp were equivalent to non Regexp, I would use it all the time, but it's not.

I just tried a test again, searching for the simple text "times" in my code base.  There were 761 matches.  Timing results:

- Plain search  7.9 seconds
- Wildcards     8.3
- Regexp       46.7

So it certainly seems like there is some significant savings that Matt obtained for non-RegExp searches.  Possibly he found a way to pre-determine the circumstances in which there were any matches; I don't know.

In any case, I am sure that being able to do "whole statement" searches instead of "same line" searches is valuable, but if the cost would be a significant degradation in search time, I would want to see it as an option rather than standard behavior.

**Comment by Jimrnelson** [comment]
@lscheffler 

Lutz --

Ah, I have a better recollection now of what is going on.

Of course RegExp is called for every match, that is how the entire line is extracted for display in the grid.

Since RegExp is many times slower that either simple or wild card match (using LIKE), in the non-RegExp search Matt first uses simple or wild card match on an entire code string to see if there are any matches.  

He only uses RegExp if there are any matches, bypassing the use of RegExp against code that will not yield any results.

**Comment by lscheffler** [comment]
Sure, this need to be an option. It needs either a preprocessing or a complex pattern, and for a simple search both are slow.

**Comment by lscheffler** [comment]
> 

That means, depending on the distribution, *Plain* might even be slower. On my test pattern - a hit on each file. :D

**Comment by Jimrnelson** [comment]
This feature has been implemented in Version 7, released 2024-03-08.

Regular Expressions were not used to achieve this and the effect on execution is barely noticeable.
