### ISSUE TITLE
Scope disappears after a project search

### ISSUE THREAD

**Issue by rikaye** [VFPX/GoFish#69]
## ℹ Computer information

- VFP version: Visual FoxPro 09.00.0000.7423 for Windows
- GoFish version: 6.0.007
- 5.x

## 📝 Provide detailed reproduction steps (if any)

1. Enter a search term
2. Use Project browse button to select a PJX
3. Run search
4. Scope field is cleared when results are returned.
5. The dropdown does not contain the project just searched. 

### ✔️ Expected result

The Scope textbox should not be cleared when results are returned.

### ❌ Actual result

The Scope field is cleared. Taking a wild guess here that GF is confused about where its metadata lives. i have tried to reset everything... It is also inconsistent in how the Scope textbox gets populated from various places.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/28717887/226010784-1f125948-655c-4a77-98dc-5ebc13c3516b.png)

![image](https://user-images.githubusercontent.com/28717887/226011247-ced61971-b3b9-471c-b427-0694cb80ff14.png)

![image](https://user-images.githubusercontent.com/28717887/226012131-296f5470-d4cc-49f0-b08d-7913acf873ae.png)

**Comment by rikaye** [comment]
folder search seems to behave much better (iow like v5) than project search

**Comment by lscheffler** [comment]
There is a change in what scope is used for. Possibly the restore is mixed up. I will take a look.

**Comment by rikaye** [comment]
Trying a little debugging. This is in the OpenTable method. The table being processed is GF_Search_Scope_History.dbf

```
If !Used(Juststem(lcTable))  
		Select 0  
		Try  
			Use (lcSearchExpressionTable) Exclusive  
			Pack  
			Use  
		Catch  
		Endtry  

```  

lcSearchExpressionTable is not in scope so the attempt to pack the table always fails. Presumably this should be lcTable as the first thing that happens after the try..catch block is a USE (lctable).

I doubt this has anything to do with the odd behavior with project search I'm seeing but figure it's worth mentioning.

**Comment by rikaye** [comment]
OK, one last comment. I went through that gf_result!gf_search_scope_history table, deleted a bunch of project refs I just didn't care about and packed the table. GF is now properly showing the last project I used. There must be something buried in the gf_combosearchscope  class but that's about as much time as I'm willing to spend on a Friday night. :-)

**Comment by lscheffler** [comment]
> Trying a little debugging. This is in the OpenTable method. The table being processed is GF_Search_Scope_History.dbf

This is *gf_combosearchscope.OpenTable*, looks like an copy'n'paste error compared from *gf_combosearchexpressionhistory.OpenTable*

> OK, one last comment. I went through that gf_result!gf_search_scope_history table, deleted a bunch of project refs I just didn't care about and packed the table. GF is now properly showing the last project I used. There must be something buried in the gf_combosearchscope class but that's about as much time as I'm willing to spend on a Friday night. :-)

You did not an accidental backup of the table? Else it's hard to trace. ;)

If you do not have a copy of this file, will there be something in Home(7)+"GoFish_Backup" ?

**Comment by rikaye** [comment]
Ah, you mean VB inheritance... ;-) 

I'll check on Monday to see fi there's a pre-migration copy of that table.

My working theory at the moment is the filtering for the MRU list is improperly clearing the value for a project row which is in the table but not within the MRU limit.

**Comment by lscheffler** [comment]
The problem is a bit odd. There is a number of scopes in the list, and the one you are looking for is **stored** but not on **display** (there are distinct settings on the number of items). Setting it as scope should move the item on top of the list - it should become visible by this. This fails. After the run the combo is told to make item xyz visible what is not on the list, that's why it is blank - on some values. It fails on startup too. I just found it using GoFish on an environment with many pjx's open ...

Since deleting from the table will shorten the list, it will kind of repair the problem.

I will fix the sorting.
