### ISSUE TITLE
Red outlines on checkbox in Selection pane are inconsistent

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#7]
Per Jim Nelson, the red outlines are supposed to go around any checkboxes that are checked. But:

- a.	The Limit to Home/Subdirectories checkbox never gets a red box.
- b.	The Comments checkbox has it exactly reversed—it’s there when unchecked and gone when checked.

**Comment by DougHennig** [comment]
If you let me know what changes to make, I'll implement them.

**Comment by Jimrnelson** [comment]
Correction to Tamar's comments --

The red lines are actually supposed to indicate non-default behavior.

Those, the comment checkbox does not have it wrong, as the default behavior is for it be checked.

Also, adding to her list, the "Whole Word" checkbox never gets a red box either, so this should be the new item b.

**Comment by lscheffler** [comment]
@Jimrnelson For the *Whole Word* checkbox. The code is there, exactly like let's say *Match Case*. Only the valid does not fire on click, so the container shows no border.  
If you set it true, close GoFish and restart, the border is there. Only now you can't turn it off.   
An other way to activate:
1. Check *Replace View*
2. Check *View Replace History*
3. Uncheck *View Replace History*   

Now the border is set. It changes with refresh by the value of 1*Whole Word*.

I have no idea why the VALID event does not fire.

**Comment by lscheffler** [comment]
For some reasons there was an additional checkbox for *Whole Word*.   
@Jimrnelson, The other points are feature as expected, so we can close this if the fix is pushed?

**Comment by lscheffler** [comment]
*Whole Word* is working now, other fields as expected. Closing issue.
