### ISSUE TITLE
News item for GF version 6

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#76]
GF version 6 has been around now for a few weeks.

I suggest you write a Thor News item describing all the new features.  This would show up for anybody using Check For Updates.

Doing so is quite straightforward.  Create an MD file and paste it in here and I will publish it in the News.

P.S.: -- I am working on making Thor News a separate VFPX repository that would simplify this process.

**Comment by lscheffler** [comment]
All done on v6.0.0   
See Readme.md -> Changes -> [Changes on V6](https://github.com/VFPX/GoFish/blob/master/docs/New_6.md) (\*.\*)

**Comment by Jimrnelson** [comment]
@lscheffler 

I think that document would work well as the next Thor News item.

If it's OK with you, I would like to make some minor modifications to some grammar and vocabulary and make it available sometime soon.  

With all the work you've done on this, your upgrades should get all the attention they deserve.

**Comment by lscheffler** [comment]
That's perfectly fine.
