### ISSUE TITLE
When searching, it reports an error in some cases

### ISSUE THREAD

**Issue by KuceraJanSupport** [VFPX/GoFish#78]
## ℹ Computer information

- VFP version: 9.0 SP2
- GoFish version: 6.0.010
- Last GoFish version w/o bug (if available):

When searching, it reports an error in some cases. The error does not always appear.

![obrazek](https://user-images.githubusercontent.com/30229034/231080083-29499c94-8be9-4b78-a6e0-a45e8b94f95c.png)
![obrazek](https://user-images.githubusercontent.com/30229034/231080515-b773f8c2-f692-4a0a-8465-ce6309aed73d.png)

**Comment by lscheffler** [comment]
@KuceraJanSupport 
It says the base node of the node to create is missing, so the question is why, there must be something special to it.   
If you issue the same call, does the error repeat?   
Can you provide the *Call Stack* and the values that are used in the *DO CASE* as well as *lcFileName*? 

Thanks

**Comment by KuceraJanSupport** [comment]
Hallo.

 

If an error occurs for a given expression, then it is repeated each time it is called. Above the same project,

the error appears for some expressions, but not for others. I've been using GoFish every day for several years and it only does this for the last few versions.

For me, GoFish is an excellent component without which I cannot imagine my work at all. Thank you so much for maintaining and developing it.

**Comment by lscheffler** [comment]
@KuceraJanSupport I really like to fix the problem, but I need the information mentioned above:

> Can you provide the *Call Stack* and the values that are used in the *DO CASE* as well as *lcFileName*?

It looks like some of your searches found files that are not found by other searches and therefore something with the node is wrong. I need to figure out the difference.

**Comment by KuceraJanSupport** [comment]
I'm sorry, I was sending the pictures as an email attachment, but somehow it didn't get here.
![obrazek](https://user-images.githubusercontent.com/30229034/231996798-e2191228-225e-44a4-9354-ca97708c4db7.png)
![obrazek](https://user-images.githubusercontent.com/30229034/231996837-931bd8d4-c66b-4581-b005-9de46c39c961.png)

**Comment by lscheffler** [comment]
The problem is a file without extension, then.    
What are your settings to include a file without extension into the search? I can add such a file to my pjx, but it is ignored by GoFish, and I have no idea to include.    
Would you mind to zip `"HOME(7)+GoFish_"` without the subfolders?

**Comment by KuceraJanSupport** [comment]
I send
[GoFish_.zip](https://github.com/VFPX/GoFish/files/11231304/GoFish_.zip)

**Comment by lscheffler** [comment]
It's very simple. Your filename is to long. And the program uses two ways to determine the same thing
- the column *FileType*
- *Justext(FileName)*   
Since Justext returns no extension, the name is simply longer then 50 chars, it likes to put the file under node **\*Root_OTHER**. Since there is no EMPTY(FileType), this node is not created above.

So there are two problems, the too short field and the double handling. Then one is easy to change the other not.
