### ISSUE TITLE
Export failure

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#79]
## ℹ Computer information

- VFP version: 9 SP2
- GoFish version: 6.0.006

## 📝 Provide detailed reproduction steps (if any)

Not sure if this is a bug or "user error"...
In either event, need a tutorial, pls, on using the 'Export' option.
In all the years I've been using GF, this is the first time I needed to export search results, but its apparently not intuitively obvious how to do so...

After search results are displayed, I click the Export option.
I get a dialog that asks for:
	To  'DBF or XLSX'; 'Cursor'; 'View in browser'
	Select 'DBF..."
	Enter file name of  'abc.xlsx' and click 'Export to', but no output file is created.
Upon return to the GF form, the Export option is disabled or has no effect so I can't do another export until I close and reopen GF.

If I select 'Cursor' there is also no output file and GF errors in the gf_ResultsForm1.ExportToExcel method at the
Goto Top line as no table is open.

Within the debugger,
	If I set lcFile to the file name
	and set lcFilter to ""
	the code runs to the Goto Top line and opens a GetFile dialog, which is bogus
	Bypass that and the file is created.

**Comment by lscheffler** [comment]
@BobWilkes New version is pushed, please check the export.

**Comment by BobWilkes** [comment]
Latest update seems to have fixed the issue.
TNX.
