### ISSUE TITLE
gf_search_history.dbf Not Found

### ISSUE THREAD

**Issue by Steingo** [VFPX/GoFish#80]
## ℹ Computer information

- VFP version: 9
- GoFish version: 6.0.007
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Enter a term and click GoFish
2  Series of error messages appear, starting with <default folder>\gf_search_history.dbf 
3.  Click Ignore multiple times to get past the errors
4.  Search is completed successfully and results are displayed

### ✔️ Expected result

_What is the expected result of the above steps?_
Default searches should run without errors
### ❌ Actual result

_What is the actual result of the above steps?_
Error boxes as noted above
## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
![image](https://user-images.githubusercontent.com/38174426/231810033-a473a77b-508f-44ba-96f2-eb1c00eb22dd.png)

**Comment by Steingo** [comment]
I assume this is just a matter of creating the gr_search_history.dbf table and placing it in the correct location.   I could do that if I knew what the table structure was supposed to be.

**Comment by lscheffler** [comment]
Please run last version as provided through Thor, it helps me to have only one version to maintain. (The failure will remain in the most recent version, but just to have the same stuff)   
It should create the table on it's own, the question is why it looks the table up in this folder.
- This is the first run of v6.?
- This is the first run of this session?
- Will it run if you close VFP and rerun?

If nothing helps, please try to delete whole folder `Home(7) + "GoFish_"` and rerun

**Comment by Jimrnelson** [comment]
@Steingo 

Is this still and issue or can I mark this as complete?

**Comment by Steingo** [comment]
This went away after reinstalling GF.  Thanks, and sorry for not following up.

**Comment by Jimrnelson** [comment]
This bug fixed in Version 7.0.14 - 2024-03-15.

Related errors in #126, #181.
