### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#81]
## ℹ Computer information

- VFP version: 9.2
- GoFish version: 6.0.006

## 📝 Provide detailed reproduction steps (if any)

When I search a pjx that's not in the 'normal' folder, I get an error (after search results are displayed):
File not found: C:\BUDEVELOP\TOOLS\THOR\THOR\TOOLS\THOR_TOOL_PEME_LAUNCHPEMEDITOR.PRG
The 'BUDEVELOP' folder is the location of the PJX GF is looking at.
It does not contain the TOOLS folder, hence the error.
The 'normal' path is C;\Develop which does contain the Tools subfolder.

If I then open a project that's in a subfolder of the 'normal' path, everything is AOK.
FYI: The 'normal' structure is
c:\Develop
    <App 1>
   <App 2>
    Tools
        <Thor>
BUDevelop is the folder in which I copy an App x folder for backups.

**Comment by lscheffler** [comment]
Just for my understanding
You have a folder -structure like
- c:\Develop
- c:\Develop\<App 1>
- c:\Develop\<App 2>
- c:\Develop\Tools

And you set the search PJX like *C:\BUDEVELOP\my.pjx*?

- What is your path in the moment you start the search (`CD` will do)
- GoFish is in a subfolder of *c:\Develop\Tools*?
- Is this the first search of GoFish in this session?

**Comment by Jimrnelson** [comment]
@BobWilkes 

Is this still and issue or can I mark this as complete?

**Comment by BobWilkes** [comment]
I haven't seen it recently, so go ahead and close.

**Comment by Jimrnelson** [comment]
Ok, thanks.
