### ISSUE TITLE
Alternative display in "Code Window" for matches found in menus

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#87]
I find the display in the "Code Window" for matches in menus to be of little value.

That is why there's this little button, which helps you find what option a match corresponds to:

![image](https://user-images.githubusercontent.com/81179335/233384154-6ffa2ceb-79e3-4335-b68b-7891a3882db5.png)

(Note that this shows up in a separate window)

I suggest that it show up in the code window instead and the little button shown above be removed.

**Comment by lscheffler** [comment]
Sounds logical.

**Comment by lscheffler** [comment]
See #101.
Possibly we should think about a better interface in general.   

- at least partial tree view (iow the path to the hit)
- some information where on the entry it is found

Volunteers?

**Comment by Jimrnelson** [comment]
> See #101. Possibly we should think about a better interface in general.
> 
> * at least partial tree view (iow the path to the hit)

**My comments here apply only to MNX files**

The simple little text file in #101 shows the path to the hit, and is sufficient for my needs.  I would not want to see a partial tree view crammed into the grid when the text file provides enough information.  

Unless you're suggesting that the text file appear in the Code View window -- that would be pretty nice, actually, and certainly more obvious than using the button.  It should be relatively straightforward to implement, too.

> * some information where on the entry it is found

What information are you looking  for that is not already visible in the grid?

**Comment by lscheffler** [comment]
Yes, this is all is about mnx.

----
Like the text in the file from the button, but possibly only the part that ends up to the (let's call it) menu item, not the whole structure.

----
For example, if the hit is in SKIP,  then somehow show that it is in the skip part of the definition. Not that just-show-what-GF-found-somewhere thing.

Example:   

If the file is like
```
*   dcPad_Datei
*      dcBar_Datei_C01
*      dcDivider
*   dcPad_Tabellen
*      dcBar_02_C01
*      dcBar_02_C02
```
and the hit is somewhere in the skip of dcBar_02_C02, then just like
`Hit in:   dcPad_Tabellen / dcBar_02_C02 (skip);  the-hit`

**Comment by Jimrnelson** [comment]
A few questions:

1. Where are you suggesting this new text be shown?  
2. What are `dcPad_Tabellen` and `dcBar_02_C02`?  They don't look like captions.  Menu Bar names?  If so, how would that help anybody who accepts randomly assigned names?
3. The type of match is already displayed in the grid in the "Match Type" column.  It shows as `<SkipFor>`.  Why do you need to display it anywhere else?

**Comment by lscheffler** [comment]
> A few questions:
> 
> Where are you suggesting this new text be shown?   

In the HTML box 
> What are `dcPad_Tabellen` and `dcBar_02_C02`?  They don't look like captions.  Menu Bar names?  If so, how would that help anybody who accepts randomly assigned names?   

Giggle. Just the normal output of the little button. Pad / Bar captions by \#DEFINE, I tweaked GenMenu to accept strings (`"BarCaption"`) or defines / expressions instead of non-delimited literals. Nice for multilingual menues. Since all my menu look like this, just a pick from a random search.    
![grafik](https://github.com/VFPX/GoFish/assets/27769909/91a9bc90-50cb-45ee-b8be-7610b8d988b6)

> The type of match is already displayed in the grid in the "Match Type" column.  It shows as `<SkipFor>`.  Why do you need to display it anywhere else?    

Because I do not use a GoFish as wide as you, I focus on the HTML box. I only turn the *Default* columns (in Options) on. Normally enough. But thanks for the tip. (\*.*)

**Comment by Jimrnelson** [comment]
If there is anything to be improved here, I think of combining a few of the suggestions, like this:

1. Make the contents of the text file that shows the entire menu definition (with captions) visible in the HTML Code View area instead
2. Eliminate the button that now brings up that text file
3. Add to the line in the text that currently highlights the match any other desired information.  My guess is that the contents of the Match Type field might be sufficient.

I think I might be willing to take a shot at this, altho not promising when.

**Comment by lscheffler** [comment]
Hm, I'm soso.   
To bring up the text file was the idea to search the mpr additional from https://github.com/VFPX/GoFish/issues/101#issuecomment-1602210322, so there is no need to fiddle with the mnx display. What will be a pain to position, it feels like a lot of work to find the right position in it. Or to create the single definition line. What still does not tell me where to look inside the mnx.

And if I go for me, I need to figure out *where* in the mnx I need to change something. To analyse the mpr for this is a pain, I need the path through the mnx form.

The little button. I would keep it for fun. It does no harm, and better to keep it then do harm while removing it.

**Comment by lscheffler** [comment]
In general, it would be cool to have Rick Schummers proposed *MenuDesigner Pro* as an option here.

**Comment by Jimrnelson** [comment]
The Code View pane for matches in MNX files has been enhanced so provide more complete information on the match.

![image](https://github.com/VFPX/GoFish/assets/81179335/197b70f1-cafc-4d59-b874-509e50a00a92)
