### ISSUE TITLE
Code View window mangles the start of PRG files.

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#90]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Look at these two images  ... the Code View image has the top lines of the PRG wrong.

(Am realizing this should have been reported as a bug, not an feature request.)

As far as I can tell, this happens with PRG files where the match is to a file name, rather than the contents of the PRG.  Not sure if there are other cases.

![image](https://user-images.githubusercontent.com/81179335/233663684-4de28d12-9ee2-46e8-b198-39d30336c921.png)


![image](https://user-images.githubusercontent.com/81179335/233663602-73d3235d-9ede-497d-85d6-80cb39718420.png)

**Comment by lscheffler** [comment]
@Jimrnelson Do you have insight into the search engine? I work just the UI ...

**Comment by lscheffler** [comment]
The problem goes with *prg* and *other* files like h or css, here the filename is STUFFed from pos 1.  A VCX/SCX will show a record with just the filename.

**Comment by Jimrnelson** [comment]
It is only the UI.  The search works fine, but the UI mangled what it puts in the code window.  Sent from my iPhoneOn Apr 21, 2023, at 11:30 AM, Lutz Scheffler ***@***.***> wrote:﻿
@Jimrnelson Do you have insight into the search engine? I work just the UI ...

**Comment by Jimrnelson** [comment]
It shouldn’t be stuffed.  It should be inserted.  Sent from my iPhoneOn Apr 21, 2023, at 11:57 AM, Lutz Scheffler ***@***.***> wrote:﻿
The problem goes with prg and other files like h or css, here the filename is STUFFed from pos 1.  A VCX/SCX will show a record with just the filename.

**Comment by Jimrnelson** [comment]
Update:It shouldn’t be stuffed or inserted.  That code should be removed.  There is no need to put the file name into the Code View window, as the file name appears just above it.So just remove the stuffing!Sent from my iPhoneOn Apr 21, 2023, at 12:19 PM, Jim Nelson ***@***.***> wrote:﻿It shouldn’t be stuffed.  It should be inserted.  Sent from my iPhoneOn Apr 21, 2023, at 11:57 AM, Lutz Scheffler ***@***.***> wrote:﻿
The problem goes with prg and other files like h or css, here the filename is STUFFed from pos 1.  A VCX/SCX will show a record with just the filename.

**Comment by lscheffler** [comment]
I will not remove remove. Somebody had an idea why to put the `file name = "blabla"` stuff there at all. It's not to bad to have it, so I can go with it. Only the code is wrong.

**Comment by Jimrnelson** [comment]
Wait --

That filename was stuffed into the beginning of the text when the match is on a file (rather than text within a file) very early in the development of GF.  It was put there because at that time there was no clear way to see the name of the file.

That has changed.  The file name now appears right above the Code View window:

![image](https://user-images.githubusercontent.com/81179335/233711368-e0887eec-6478-4f13-a4f6-3679901990d8.png)

The original reason has disappeared (actually, disappeared a long time ago), and you can remove the gibberish from the Code View window by removing the statement that does the STUFF.

BTW, this is a very common and annoying problem.

**Comment by lscheffler** [comment]
I looked it up right now - and it is the engine. The engine fills *ProcCode* and *Code* fields for the text files, but not for SCV/VCX (and I guess other table based sources)   
The `ShowHtmlCodeView` method does not care, it blindly stuffs the result on a given position, here 0, adds the divs and so on and sends to the browser window. This method works the same way for any result.

This is a rather complex problem, no fast fix.    
Also, for the VCX, you find it coloured, what is wrong too.

**Comment by Jimrnelson** [comment]
I understand your issue, but it's not as hard to correct as you think.

For matches to file names, the field MatchLen is 0; for all other match types, MatchLen = Len(MatchLine).

I am pretty sure you can adjust the call to ShowHtmlCodeView when MatchLen = 0 so that no substitution is necessary.  I'd guess two new statements in the Procedure would handle it.  No need for any major alterations anywhere.

**Comment by lscheffler** [comment]
Accept that the fields cause bloat. Must be fixed as well.

Anyway, if you are sure with it (I don't, would need to look this up in the engine), it's a short fix? We can open a branch merge-only, so we don't need to go over a new version. ;)

**Comment by Jimrnelson** [comment]
My suggestion has nothing to do with modifying the results grid, only with how ShowHtmlCodeView uses it.  

I believe that if the following line of code is modified appropriately when MatchLen is zero to use slightly modified parameters it should work OK

![image](https://user-images.githubusercontent.com/81179335/233723984-8ab607ed-d5c9-42fc-9361-7aeafa603deb.png)


P.S.:  Unfortunately, I am not actually able to get in to write or test anything, but can certainly continue to write emails in the interim.

**Comment by Jimrnelson** [comment]
> I understand your issue, but it's not as hard to correct as you think.
> 
> For matches to file names, the field MatchLen is 0; for all other match types, MatchLen = Len(MatchLine).
> 
> I am pretty sure you can adjust the call to ShowHtmlCodeView when MatchLen = 0 so that no substitution is necessary. I'd guess two new statements in the Procedure would handle it. No need for any major alterations anywhere.

> Accept that the fields cause bloat. Must be fixed as well.
> 

Yup, memo fields cause bloat, but modifying this part of GF would be a pretty big headache I think.  I disagree with the "must be fixed" interpretation, but I am not the support person, so I respect your feeling on this one (and others).

**Comment by lscheffler** [comment]
It's not big a deal, if I know reliable how to find this records, there is a place in the UI that deals with the memos anyway. 

This is part dealing with the render, but it's more then this. This is also not to syntax colour.

I need to think this through, I need to check the table for information I understand, this will take a while, the bug is old as the world and just ugly, so this is not urgent.

**Comment by lscheffler** [comment]
I have no time to implement this. Since it is as this all the time, I will not change. You are free to fork if you need a change.

**Comment by lscheffler** [comment]
I will try - but this is not easy to fix, for all I remember. I dislike the quick fix to the display code.

So it just stands that you can jury-rig this for now and keep the issue open, so I can do it right later. Or you must wait.

**Comment by Jimrnelson** [comment]
@lscheffler 

Glad you are keeping this open.  I agree that tinkering with the engine has to be done with extreme care (just like tinkering with CFU).

My guess, however, is that this is a fix requiring only a few lines of code.  The trick is to find that place.

**Comment by lscheffler** [comment]
One have to both store the right stuff and to display the right stuff. This must be synced somehow. Without causing trouble to the *normal* behaviour. This special case - find a file name - is between the code-from-a-file-part and not, as one would do those days, in a distinct place.

**Comment by Jimrnelson** [comment]
@lscheffler 

I have just verified that the search engine captures the correct information, which is to say that it captures the entire procedure code, including that part is truncated off the front.

So nothing needs change in the search engine at all, as all the needed information is there.

All that does need to be fixed is the code the renders the HTML.  I am not saying that is simple, just that it should be simpler than touching the search engine, something you want certainly want to avoid.

**Comment by lscheffler** [comment]
We run in circles. As I stated above, the code does not belong into the record at all.

But, let me repeat.
- I understand the result is ugly right now, but for me not in a closer sense wrong.
- If I do it, I will do it complete, starting in the engine not storing the wrong stuff. And from there I look what to do with the display. I do not like to go twice over this. But not in near future.
- If it really annoys you, just fix the display and push. No bad feelings, I'll send PM in close time

**Comment by Jimrnelson** [comment]
@lscheffler 

[1]  This is for later, when you (or anybody) gets to it.  No hurries.  

[2]  I have determined that there is nothing to change in the search engine for this.  Only the HTML rendering needs modification.

[3]  I would not dream of pushing anything while you are doing major remodeling.

**Comment by Jimrnelson** [comment]
@lscheffler 

When the time comes (that is, one of us has the time to take a shot on this), there is a one line fix.  

Unfortunately it's in the search engine.

![image](https://github.com/VFPX/GoFish/assets/81179335/cb91834c-1a14-494b-ae5a-7049a07d9cb4)

So this doesn't get lost, here's the suggested code (although I do not know how you represent CRLF)

```
		If This.IsTextFile(tcFile)
			loSearchResultObject.Code = loSearchResultObject.MatchLine + CRLF + Filetostr(tcFile)
		Endif

```
In any case, should be easy enough to test.

Cheers

**Comment by lscheffler** [comment]
Thanks for the snippet.

> [3] I would not dream of pushing anything while you are doing major remodeling.

One reason more to bring this in line. It simply should be possible to change, whatever somebody else is doing.

**Comment by Jimrnelson** [comment]
This bug has been fixed in Version 7, released 2024-03-08.

For instance:

![image](https://github.com/VFPX/GoFish/assets/81179335/2fbc2fcf-4ddd-49e1-86b2-bcf0248c76bc)
