### ISSUE TITLE
Sorting in results grid fails ... sometimes

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#91]
## ℹ Computer information

- VFP version: 9 build 7423
- GoFish version: 6.0.006
- Last GoFish version w/o bug (if available): Not sure

## 📝 Provide detailed reproduction steps (if any)

1) Do a search in Toolbox.PJX for string "item" (without the quotes)
2) Click Match Line column header in the results grid.

### ✔️ Expected result

Grid is sorted by the matched line.

### ❌ Actual result

Grid is not sorted. Actually, looks like it may be sorted within the file, but I expect a complete sort, so all similar commands sort together.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/30271640/234379194-52b26e72-5d3f-4aec-93c0-8385355f188f.png)

**Comment by lscheffler** [comment]
Intended. There was a reason for this - something was running havoc without this. I need to look it up.   
My first guess is, you can have the same file (name) in different folders, and it was simply no way to figure what was going on in the grid.

**Comment by TamarEGranor** [comment]
That makes the sort of the Matched Line column useless. This used to work. I used it all the time when trying to find all occurrences of a particular command. Please fix this.
