### ISSUE TITLE
Restoring a previous search doesn't update the Search and Scope fields

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#92]
## ℹ Computer information

- VFP version: 9 build 74234
- GoFish version: 6.0.006
- Last GoFish version w/o bug (if available): Don't know

## 📝 Provide detailed reproduction steps (if any)

1. Restore a search from history

### ✔️ Expected result

The entire UI would reflect the restored search

### ❌ Actual result

The Search and Scope fields at the top still show the previous search rather than the restored search.

**Comment by lscheffler** [comment]
There might be something with this and the options. I guess you use it like
- CR options of
- or at  least *Show history in tree* is off
- Open a previous session from the history form

In this case it might make sense to set (search settings) of the form to the previous state.

Try to use the history-in-tree, it allows to refresh via right-click, and check multiple results.

**Comment by TamarEGranor** [comment]
I think you're misunderstanding what I'm seeing. I've done a search, say this:

![image](https://user-images.githubusercontent.com/30271640/234588875-0399a564-48c1-4b8a-9cd0-2fd82579a425.png)

Then, I click History, highlight a different search (a different string in a different project), and click Load Results. I get this:

![image](https://user-images.githubusercontent.com/30271640/234589334-256aff2b-d9b1-416b-8177-37c446e55e96.png)

**Comment by TamarEGranor** [comment]
Oops, that first image doesn't show what I wanted. Here's the first one again:

![image](https://user-images.githubusercontent.com/30271640/234589762-3aa04d15-b16f-4179-bd51-5eec435a6ef1.png)

**Comment by TamarEGranor** [comment]
No, the scope and search where I highlighted are wrong. The search term as "hap" and the scope was a different project in a different folder. 

This used to work.

**Comment by lscheffler** [comment]
Your three examples show all the same, that is what I wrote, only you like to see what was in the history, what I wrote too. And I've expressed that this is only true in your mode, that I have changed something not checking for this very mode.

**Comment by TamarEGranor** [comment]
All I know is this used to work correctly. As far as I know, I haven't changed any settings having to do with history. Can you suggest what settings might be involved and where I'd find them? 

Anybody else seeing this?

**Comment by lscheffler** [comment]
I repeat. I have a new way to use GoFish - show the history in tree, like CR -, where it would be wrong to restore the Search and the Scope, and this works wrong now for the way inherited.

So explicit.   
Yes, there is a problem. Yes, I know where to look this up. And logically, yes, it will be fixed.
