### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#93]
Having decided (finally) to move to version 6 today, I tried Thor's Check For Updates and received this message:

![image](https://user-images.githubusercontent.com/81179335/235734542-e908707d-5459-412e-a5f9-4e25cc8104ba.png)

I assumed it meant I should delete all files in the folder, which I did.

When I then tried to run GoFish, it simply hung.  Nothing visually happened; I had to kill my session.

So, I'm still back in GF 5

**Comment by lscheffler** [comment]
Must be my English. Clear the folder as delete the *whole* folder. Not remove the files inside the folder.   I will change the message.

**Comment by Jimrnelson** [comment]
This is not closed.

After deleting that folder, I tried again.

It balked at having a problem with another folder, which I erased.

When I run GF6 now I get this:

![image](https://user-images.githubusercontent.com/81179335/235785398-3da46d2a-2da3-4dc3-955f-5880b4bcb6cf.png)

**Comment by Jimrnelson** [comment]
And on question on this -- is this saying that the search history goes into my current folder?

I certainly do not want that (others may, I do not)

My searches having nothing to do with the current folder.

**Comment by lscheffler** [comment]
Would be nice to know the other folder. :(

Would you mind to suspend at the error and give me a snapshot of the debugger including trace and locals? And the result of `CD` or` JUSTPATH("","")`. The one shown in the error message? This is an intended location to work?

-----
Default is just one storage for your Windows-Logon `Home(7)+"GoFish_"`, similar to that from V5.   
There is an option to go local relative to the foxuser.dbf. That is, if you use different foxuser for different projects, as I do, you can set GoFish special for this, including all settings and history. But it would need you a two step process to turn it on, and GoFish is clearly not in that state.    
The current folder should be avoided to write GoFish data, for all I remember initially it likes initially an empty folder to write to.

**Comment by lscheffler** [comment]
Since I can only work the problem by assistance of a foreign computer and nobody is willing to spend the time, this is closed.
There is no other way then removing all gofish related stuff from HOME(7), restart VFP and rerun, then.
