### ISSUE TITLE
Type mismatch error on instantiation and after search

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/GoFish#96]
## ℹ Computer information

- VFP version: 9.2
- GoFish version: 6.2.000
- Last GoFish version w/o bug (if available): n/a

## 📝 Have been getting this error for the past couple of updates.
Pops up on initial open and again after search completes.
Type mismatch. gf_ResultsForm1, PopulateView, line: loTree.SeletedItem = m.loNode
![image](https://github.com/VFPX/GoFish/assets/34778960/71af7b1e-57ef-4720-9032-465bf2c9e481)
loNode is an object
If I ignore the error (and the two following "SelectedItem does not evaluate to an object" errors, the search runs as expected.

**Comment by lscheffler** [comment]
Please try latest version *6.0.010* first. There was a problem like this.    
If it is not of help, I would need your settings, this is the DBC and there tables in HOME(7)\GoFish_ Or simple this folder, without the subfolders.

**Comment by BobWilkes** [comment]
Now using v 6.2
Still getting OLE Type mismatch error...
What setting values do you want?
Home(7) points to my AppData\Roaming\Microsoft\Visual FoxPro 9 folder
     which has a GoFish_ folder, which has a bunch of files in it.

**Comment by lscheffler** [comment]
This GoFish_ Folder zipped, but you please skip the subfolders. They are half of your code cached, and large, and I guess this is not good to populate.

**Comment by BobWilkes** [comment]
see attached

**Comment by lscheffler** [comment]
Looks like attachment has not worked

**Comment by BobWilkes** [comment]
Looks like GitHub can't handle 7z files. Too bad as the zip is about 
150% larger.

**Comment by lscheffler** [comment]
@BobWilkes This seems still to be open. Would you mind to retry your upload? I learned: as zip. 7z is not working here.

**Comment by BobWilkes** [comment]
Haven't gotten it recently.
I'd say close it.
If it happens again, I'll resubmit.


------ Original Message ------
From "Lutz Scheffler" ***@***.***>
To "VFPX/GoFish" ***@***.***>
Cc "BobWilkes" ***@***.***>; "Mention" 
***@***.***>
Date 12/17/2023 11:11:24 AM
Subject Re: [VFPX/GoFish] Type mismatch error on instantiation and after 
search (Issue #96)

**Comment by lscheffler** [comment]
o.k. #116 as well?

**Comment by BobWilkes** [comment]
Yes. GF seemns to be behaving properly now. 😁


------ Original Message ------
From "Lutz Scheffler" ***@***.***>
To "VFPX/GoFish" ***@***.***>
Cc "BobWilkes" ***@***.***>; "Mention" 
***@***.***>
Date 12/17/2023 12:01:20 PM
Subject Re: [VFPX/GoFish] Type mismatch error on instantiation and after 
search (Issue #96)
