### ISSUE TITLE
"Invalid file or Path name" error upon GoFish 6 startup

### ISSUE THREAD

**Issue by FoxInCloud** [VFPX/GoFish#99]
## ℹ Computer information

- VFP version: Visual FoxPro 09.00.0000.7423 for Windows [Feb 23 2009 13:20:28]
- GoFish version: 6.2.001
- Last GoFish version w/o bug (if available): 5

## 📝 Provide detailed reproduction steps (if any)

1. start Go Fish using a keyboard shortcut (ctrl+F10 in my case)
2. error pops in
3. after choosing 'ignore' GF main window displays normally

### ✔️ Expected result

_start GF_

### ❌ Actual result

_Error_

this seems erroneous (see debugger screenshot below) :
__sf_regexpath = "(X86)\VFP9\TOOLS\THOR\TOOLS\APPS\GOFISH5\SF_RegExp"

## 📷 Screenshots

![GoFish6_error1](https://github.com/VFPX/GoFish/assets/8310516/2264d861-6653-4e8f-b975-1bdb76aa80d2)

![GoFish6_error](https://github.com/VFPX/GoFish/assets/8310516/197967e9-0795-4317-b995-79c581cd543d)

**Comment by lscheffler** [comment]
Hi @FoxInCloud , does this directory exist?

**Comment by FoxInCloud** [comment]
`lcPath = Right(m.lcPath,Len(m.lcPath)-At(" ",m.lcPath,2))`

this line makes the bug ; can't figure why `At(" ",m.lcPath,2)`… should it be `Rat("\",m.lcPath,2)`?

can't reproduce in IDE because of missing lib (my.vcx)

**Comment by FoxInCloud** [comment]
I think `lcPath = Right(m.lcPath,Len(m.lcPath)-At(" ",m.lcPath,2))` expects this kind of sys16 : `procedure xxx in yyy`

maybe we can test whether `lcPath` starts with `"procedure"`

**Comment by FoxInCloud** [comment]
I confirm, I have this code in one of my utilities :

` 	llProc = left(upper(m.tcSys16), lenc('PROCEDURE ')) == 'PROCEDURE '`
` 	lcAddr = iif(m.llProc;`
 `		, substr(m.tcSys16, atc(' ', m.tcSys16, 2) + 1);`
 `		, m.tcSys16;`
 `		)`

**Comment by lscheffler** [comment]
Try new version, please.

**Comment by FoxInCloud** [comment]
Tested, Fixed, congrats and thanks !

**Comment by lscheffler** [comment]
> I think `lcPath = Right(m.lcPath,Len(m.lcPath)-At(" ",m.lcPath,2))` expects this kind of sys16 : `procedure xxx in yyy`
> 
> maybe we can test whether `lcPath` starts with `"procedure"`

I think this is the general solution, but here it's the main prg of the app, so we try the lazy way for quick fix.
